<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>
        <?php if (not_empty($me['new_notifs'])): ?>
        (<?php echo fetch_or_get($me['new_notifs']); ?>)
        <?php endif; ?>

        <?php echo fetch_or_get($cl["page_title"],$cl["config"]["title"]); ?>
    </title>

    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <meta name="title" content="<?php echo fetch_or_get($cl["page_title"], $cl["config"]["title"]); ?>" />
    <meta name="description" content="<?php echo fetch_or_get($cl["page_desc"], $cl["config"]["description"]); ?>" />
    <meta name="keywords" content="<?php echo fetch_or_get($cl['page_kw'], $cl["config"]["keywords"]);?>" />
    <meta name="image" content="<?php echo fetch_or_get($cl['page_img'], $cl["config"]["site_logo"]);?>" />
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <?php if ($cl["pn"] == 'thread'): ?>
    <meta property="og:type" content="article" />
    <meta property="og:image" content="<?php echo fetch_or_get($cl["page_image"], ''); ?>" />
    <meta property="og:image:secure_url" content="<?php echo fetch_or_get($cl["page_image"], ''); ?>" />
    <meta property="og:description"
        content="<?php echo fetch_or_get($cl["page_desc"], $cl["config"]["description"]); ?>" />
    <meta property="og:title" content="<?php echo fetch_or_get($cl["page_title"], $cl["config"]["title"]); ?>" />
    <meta property="og:url" content="<?php echo fetch_or_get($cl["page_url"], $cl["config"]["url"]); ?>" />
    <meta name="twitter:card" content="summary">
    <meta name="twitter:title" content="<?php echo fetch_or_get($cl["page_title"], $cl["config"]["title"]); ?>" />
    <meta name="twitter:description"
        content="<?php echo fetch_or_get($cl["page_desc"], $cl["config"]["description"]); ?>" />
    <meta name="twitter:image" content="<?php echo fetch_or_get($cl["page_image"], ''); ?>" />
    <?php endif; ?>

    <?php if (in_array($cl["pn"], array("profile", "connections"))): ?>
    <?php if ($cl['prof_user']['index_privacy'] == 'N'): ?>
    <meta name="robots" content="noindex">
    <meta name="googlebot" content="noindex">
    <?php endif; ?>
    <?php endif; ?>

    <link rel="stylesheet" href="{%config theme_url%}/statics/css/libs/animate.min.css?v={%config version%}">
    <link rel="stylesheet" href="{%config theme_url%}/statics/css/css-libs.css">
    <link rel="stylesheet" href="{%config theme_url%}/statics/css/master.styles.css?v={%config version%}">

    <?php if ($cl["curr_lang"]["lang_data"]["is_rtl"] == "Y"): ?>
    <!-- RTL IS TEMPORARILY NOT SUPPORTED. 
			IF YOU HAVE QUESTIONS ABOUT THIS, 
			PLEASE CONTACT THE DEVELOPER OF THIS SCRIPT (MANSUR_TL| vayart.help@gmail.com) 
		-->
    <?php endif; ?>

    <link rel="stylesheet" href="{%config theme_url%}/statics/css/libs/jquery.fancybox.css?v={%config version%}">
    <link rel="icon" href="{%config site_fav%}" type="image/png">
    <link rel="icon" href="{%config site_fav%}" type="image/x-icon">

    <!-- <script src="{%config theme_url%}/statics/js/libs/jquery-3.5.1.min.js?v={%config version%}"></script> -->
    <?php if ($cl["server_mode"] == 'dev'): ?>
    <!-- <script src="{%config theme_url%}/statics/js/libs/vuejs/vue-v2.6.11.dev.min.js?v={%config version%}"></script> -->
    <?php else: ?>
    <!-- <script src="{%config theme_url%}/statics/js/libs/vuejs/vue-v2.6.11.min.js?v={%config version%}"></script> -->
    <?php endif; ?>

    <!-- <script src="{%config theme_url%}/statics/js/libs/vuejs/vue-plugins/validators.min.js?v={%config version%}"></script> -->
    <!-- <script src="{%config theme_url%}/statics/js/libs/vuejs/vue-plugins/vuelidate.min.js?v={%config version%}"></script> -->
    <!-- <script src="{%config theme_url%}/statics/js/libs/jquery-plugins/jquery.form-v4.2.2.min.js?v={%config version%}"></script> -->
    <!-- <script src="{%config theme_url%}/statics/js/libs/popper.1.12.9.min.js?v={%config version%}"></script> -->
    <!-- <script src="{%config theme_url%}/statics/js/libs/bootstrap.v4.0.0.min.js?v={%config version%}"></script> -->
    <!-- <script src="{%config theme_url%}/statics/js/libs/afterglow/afterglow.min.js?v={%config version%}"></script> -->
    <!-- <script src="{%config theme_url%}/statics/js/libs/sticky-sidebar/source/jquery.sticky-sidebar.js?v={%config version%}"></script> -->
    <!-- <script src="{%config theme_url%}/statics/js/master.script.js?v={%config version%}"></script> -->
    <link rel="stylesheet" href="{%config theme_url%}/bootstrap.min.css">
    <!-- <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"> -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous">
    </script>

    <link rel="stylesheet" href="{%config theme_url%}/Site Admin_files/animate.min.css">
    <link rel="stylesheet" href="{%config theme_url%}/Site Admin_files/css-libs.css">
    <link rel="stylesheet" href="{%config theme_url%}/Site_Admin.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">


    <?php if ($cl["server_mode"] == 'dev'): ?>
    <!-- <script>document.write('<script src="http://' + (location.host || 'localhost').split(':')[0] + ':35729/livereload.js?snipver=1"></' + 'script>')</script> -->
    <?php endif; ?>

    <?php if ($cl["pn"] == "guest" && $cl["auth_type"] == "signup"): ?>
    <?php if ($cl["config"]["google_recaptcha"] == "on"): ?>
    <script src='https://www.google.com/recaptcha/api.js' async defer></script>
    <?php endif; ?>
    <?php endif; ?>

</head>

<body <?php if ($cl["curr_lang"]["lang_data"]["is_rtl"] == "Y"){echo('dir="ltr"');} else{echo('dir="ltr"');} ?>
    class="cl-app-<?php echo fetch_or_get($cl["pn"], "none"); ?>"
    data-page-tab="<?php echo fetch_or_get($cl["page_tab"], "none"); ?>"
    data-skin="<?php if($cl["pn"] != "guest") {echo($cl["display_set"]["color_scheme"]);} else{echo("default");} ?>"
    data-bg="<?php if($cl["pn"] != "guest") {echo($cl["display_set"]["background"]);} else{echo("default");} ?>">
    <nav class="navbar navbar-expand-sm navbar-dark bg-dark fixed-top">
        <div class="container-fluid">
            <a class="navbar-brand" href="" style="position: relative; left:160px;margin: unset; padding: unset;">
                <div class="pubbox-avatar col-sm-2" style="top: -9px;">
                    <img src="{%config theme_url%}/Homepage_files/firefox.png" style="width: 70px; height:70px;">
                </div>
                <div class="pubbox-input col-sm-3" style="padding-top: 4px; padding-left:35px;">
                    <p style="font-size: 33px; margin-bottom: unset; padding-left: 37px;">TORIFY</p>
                    <P style="font-size: 17px; color: #b974dd; padding-top: 9px;">Tweet for the DN Community </P>
                </div>
            </a>
            <div class="col-sm-3"></div>
            <div class="collapse navbar-collapse" id="mynavbar">
                <div class="form " style="left: -45px;">
                    <i class="fa fa-search" style="z-index: 10;"></i>
                    <input type="text" class="form-control form-input" placeholder="Search anything...">
                    <span class="left-pan"><i class="fa fa-microphone"></i></span>
                </div>
                <div class="col-sm-4"></div>
                <ul class="navbar-nav me-auto" style="">
                    <li class="nav-item">
                        <a class="nav-link" href="">/c/Torify</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="">#Explore</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href=""><img src="https://img.icons8.com/material/24/737373/topic--v1.png"
                                style="width:20px; height:20px;" /></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href=""><img src="https://img.icons8.com/material/24/737373/bell--v1.png"
                                style="width:20px; height:20px;" /></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href=""><img src="https://img.icons8.com/material/24/737373/shield--v1.png"
                                style="width:20px; height:20px;" /></a>
                    </li>
                </ul>

            </div>
        </div>
    </nav>


    <div data-el="main-content-holder" class="main_body">
        <main class="main-content-container <?php echo (($cl["is_logged"]) ? "" : "guest-mode" ); ?>">
            <?php if ($cl["pn"] == "guest"): ?>
            <?php echo $cl["http_res"]; ?>
            <?php else: ?>
            <div class="main-content-container-inner" style="margin-left:330px;">
                <?php if (not_empty($cl["sbl"])): ?>
                <?php if (not_empty($cl["is_logged"])): ?>
                <?php echo cl_template('main/left_sidebar'); ?>
                <?php else: ?>
                <?php echo cl_template('main/left_sidebar_guest'); ?>
                <?php endif; ?>
                <?php endif; ?>

                <div data-el="timeline-container-wrapper" class="timeline-container-wrapper"
                    style="top:17px; min-width:970px;">
                    <div data-el="timeline-content" class="timeline-container-inner">
                        <?php echo $cl["http_res"]; ?>
                    </div>

                    <div data-el="spa-preloader" class="spa-preloader d-none">
                        <div class="spa-preloader-inner">
                            <span class="spinner-icon">
                                <?php echo cl_icon("spinner-icon"); ?>
                            </span>
                        </div>
                    </div>
                </div>

                <?php if (not_empty($cl["sbr"])): ?>
                <?php echo cl_template('main/right_sidebar'); ?>
                <?php endif; ?>
            </div>
            <?php endif; ?>
        </main>

        <?php if (not_empty($cl["is_logged"]) && in_array($cl["pn"], array("conversation")) != true): ?>
        <?php echo cl_template('main/bottom_navbar'); ?>
        <?php endif; ?>

        <input id="csrf-token" type="hidden" class="hidden d-none"
            value="<?php echo fetch_or_get($cl['csrf_token'],'none'); ?>">

        <?php if ($cl['is_logged']): ?>
        <div class="modal fade modal-pubbox " data-app="modal-pubbox" id="add_new_post" tabindex="-1" role="dialog"
            aria-hidden="false">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <div class="modal-header__inner">
                            <h5 class="modal-title" data-an="modal-title">
                                <?php echo cl_translate('New post'); ?>
                            </h5>
                            <span class="dismiss-modal" data-dismiss="modal">
                                <?php echo cl_icon('close'); ?>
                            </span>
                        </div>
                    </div>
                    <div class="modal-body">
                        <?php $cl['pb_id'] = 2; echo cl_template('timeline/pubbox'); ?>
                    </div>
                </div>
            </div>
        </div>
        <?php // echo cl_template('timeline/scripts/pubbox_master_script'); ?>
        <?php endif; ?>
        <div data-app="black-hole"></div>
        <?php if (not_empty($cl['config']['google_analytics'])): ?>
        <?php echo htmlspecialchars_decode($cl['config']['google_analytics']); ?>
        <?php endif; ?>

        <?php if ($cl["pn"] != 'guest'): ?>
        <?php //echo cl_template("main/scripts/app_master_script"); ?>
        <?php endif; ?>

        <?php if ($cl['is_logged']): ?>
        <?php if (in_array($cl["pn"], array("bookmarks", "home", "profile", "search", "thread"))): ?>
        <?php //echo cl_template("main/modals/report_post"); ?>
        <?php endif; ?>

        <?php //echo cl_template("main/modals/display_settings"); ?>
        <?php endif; ?>
    </div>

    <?php if ($cl['config']['cookie_warning_popup'] == "on"): ?>
    <?php if (empty($_COOKIE['__c_u_a__'])): ?>
    <?php if ($cl["pn"] != "stat_pages"): ?>
    <?php echo cl_template("main/modals/cookies_alert"); ?>
    <?php endif; ?>
    <?php endif; ?>
    <?php endif; ?>

    <?php if ($cl["server_mode"] == "dev"): ?>
    <!-- <div class="bootstrap-bp-display">
		    <div class="d-block d-sm-none">Extra Small (xs)</div>
		    <div class="d-none d-sm-block d-md-none">Small (sm)</div>
		    <div class="d-none d-md-block d-lg-none">Medium (md)</div>
		    <div class="d-none d-lg-block d-xl-none">Large (lg)</div>
		    <div class="d-none d-xl-block d-xxl-none" >X-Large (xl)</div>
		    <div class="d-none d-xxl-block" >XX-Large (xxl)</div>
		</div> -->
    <?php endif; ?>
</body>

</html>