<section class="side-bar-l flex col nd gap-1">
    <div class="User-target flex col target">
        <div class="user-front-page-image absolute">
            <?php if (not_empty($me['avatar'])) : ?>
            <img src="<?php convert_into_base64($me['cover']); ?>" alt="Avatar">
            <?php endif; ?>
        </div>
        <div class="user-data-content flex nd col center">
            <div class="user-image s-1 circle">
                <?php if (not_empty($me['avatar'])) : ?>
                <img src="<?php convert_into_base64($me['avatar']); ?>" alt="Avatar">
                <?php endif; ?>
            </div>
            <span class="user-name">@<?php echo $me['username'] ?></span>
            <img class="t-color-3 user-karma" src="https://badgen.net/badge/karma/1234/46B8DF">
            <span class="t-color-3 user-member-since">
                <img class="" src="<?php convert_into_base64("themes/default/statics/img/cake.png"); ?>">

                Member Since :
                <?php $now = new DateTime();
                $date = new DateTime("@{$me['joined']}");
                //echo $date->diff($now)->format("%h Hours %i Minute %s Seconds");
                $year =  $date->diff($now)->format("%y");
                $day = $date->diff($now)->format("%d");
                $hour = $date->diff($now)->format("%h");
                $min = $date->diff($now)->format("%i");
                $sec = $date->diff($now)->format("%s");
                if ($year != "0") echo $year . " Years Ago";
                elseif ($day != "0") echo $day . " Days Ago";
                elseif ($hour != "0") echo $hour . " Hours Ago";
                elseif ($min != "0") echo $min . " Mins Ago";
                else echo $sec . " Seconds Ago";

                ?>
            </span>
        </div>
        <div class="account-summary grid">
            <div class="tweets-conunt flex col  center"><span>6,634</span><span>Tweets</span></div>
            <div class="comments-conunt flex col  center"><span>9,991</span><span>Comments</span></div>
            <div class="folowing-conunt flex col center"><span>5,253</span><span>Following</span></div>
            <div class="folowers-conunt flex col center"><span>4,532</span><span>Followers</span></div>

        </div>
        <?php if ($me['id'] != $cl['me']['id']) : ?>
        <div class="btns-content grid gap-1">
            <a href="native_api/profile/new_conversation?user_id=<?php echo $me['id']; ?>">
                <div class="Big-button btn round">
                    Contact</div>
            </a>
            <?php if (not_empty($cl['following_people'])) : ?>
            <a href="native_api/profile/unfollow?user_id=<?php echo $me['id']; ?>">
                <div class="Big-button btn round">
                    Unfollow</div>
            </a>
            <?php else : ?>
            <a href="native_api/profile/follow?user_id=<?php echo $me['id']; ?>">
                <div class="Big-button btn round">
                    Follow</div>
            </a>
            <?php endif; ?>

        </div>

        <?php endif; ?>
    </div>
    <div class="Comunity-target target">
        <h4 class="title">COMMUNITIES YOU HAVE FOLLOWED</h4>
        <hr>
        <div class="comunyties-content flex col">
            <?php shuffle($cl['communities_followed']); ?>

            <?php if (count($cl['communities_followed']) > 5) : ?>
            <?php $count = 5; ?>
            <?php else : ?>
            <?php $count = count($cl['communities_followed']); ?>
            <?php endif; ?>

            <?php for ($x = 0; $x < $count; $x++) {
                $community = $cl['communities_followed'][$x];
            ?>
            <div class="Comunity-display grid">
                <div class="comunity-image-content">
                    <div class="user-image s-2 circle">
                        <?php if (!empty($community['icon'])) : ?>
                        <img src="<?php convert_into_base64($community['icon']); ?>" alt="Avatar">
                        <?php endif; ?>
                    </div>
                </div>
                <div class="comunity-data-content">
                    <a href="<?php echo ("community" . "?community_id=" . $community['community_id']); ?>">
                        <h4><?php echo $community['name'] ?></h4>
                    </a>
                    <p class="t-color-3 mintext"><?php echo $community['members']; ?> Members</p>
                </div>
                <form method="POST" action="native_api/profile/leave">
                    <input type="hidden" name="community_id" value="<?php echo $community['community_id']; ?>">
                    <input type="hidden" name="user_id" value="<?php echo $me['id']; ?>">
                    <div class="comunkarity-action-content flex center">
                        <button class="follow-btn highlight_button_dark mintext btn" type="submit">Leave</button>
                    </div>
                </form>
            </div>

            <?php  } ?>

        </div>
    </div>
    <div class="Big-button btn round">AWARD STORE</div>
    <div class="Big-button btn round">DONATORS</div>
</section>