<?php global $community; ?>
<section class="side-bar-l flex col nd gap-1">
    <div class="Comunity-detail-target flex col target gap-2">
        <div class="user-front-page-image absolute">
            <?php if (not_empty($community['banner'])) : ?>
            <img src="<?php convert_into_base64($community['banner']); ?>" alt="Avatar">
            <?php endif; ?>
        </div>
        <div class="user-data-content community flex nd col center">
            <div class="user-image circle">
                <?php if (not_empty($community['icon'])) : ?>
                <img src="<?php convert_into_base64($community['icon']); ?>" alt="Avatar">
                <?php endif; ?>

            </div>
            <span class="user-name">
                <?php echo $community['name']; ?>
            </span>
            <span class="t-color-3 user-description mintext t-center">
                Lorem ipsum dolor sit amet consectetur adipisicing elit.
                Totam ducimus distinctio mollitia doloribus ea, blanditiis
                neque dolor quaerat aspernatur aliquid saepe et repudiandae
                magnam nulla natus explicabo officia ab placeat!</span>
        </div>

        <div class="btns-content content-h">
            <?php if (not_empty($cl['menu_links'])) : ?>
            <?php foreach ($cl['menu_links'] as $menu_link) : ?>
            <div class="grid-h">
                <a href="<?php echo $menu_link['url']; ?>" target="_blank">
                    <div class="Big-button btn round" style="color: <?php echo $cl['display_set']['link_color']; ?>">
                        <div><?php echo $menu_link['tapTitle']; ?></div>
                    </div>
                </a>
            </div>
            <?php endforeach; ?>
            <?php endif; ?>
        </div>

        <div class="account-summary grid">
            <div class="tweets-conunt flex col center"><span>1</span><span>Members</span></div>
            <div class="members-conunt flex col center"><span>1</span><span>Tweets</span></div>
        </div>
        <div class="comunity-mods-content">
            <h4 class="t-center">Community Mods</h4>
            <ul>
                <li><a href="profile?user_id=<?php echo $community['moderator'] ?>">
                        <h3
                            style="color: <?php if (not_empty($cl['display_set']['link_color'])) echo $cl['display_set']['link_color']; ?>">
                            @<?php echo $community['moderator_name'] ?></h3>
                    </a></li>
                <!-- <li><a href="#">
                        <h3>@someone</h3>
                    </a></li> -->
            </ul>
        </div>
        <div class="theme-switcher-content flex nd">
            <div>
                Created by :
                <a href="profile?user_id=<?php echo $community['moderator'] ?>">
                    <h3 style="color: <?php echo $cl['display_set']['link_color']; ?>">
                        @<?php echo $community['moderator_name'] ?></h3>
                </a>
            </div>
        </div>
        <hr>
        <div class="mod_mail">
            <a href="native_api/community_settings/mod_mail_user?community_id=<?php echo $_GET['community_id']; ?>"><?php echo $community['name'] ?>
                Mod Mail</a>
        </div>
    </div>
    <div class="Comunity-target target">
        <h4>COMMUNITIES YOU HAVE FOLLOWED</h4>
        <hr>
        <div class="comunyties-content flex col">
            <?php shuffle($cl['communities_followed']); ?>

            <?php if (count($cl['communities_followed']) > 5) : ?>
            <?php $count = 5; ?>
            <?php else : ?>
            <?php $count = count($cl['communities_followed']); ?>
            <?php endif; ?>

            <?php for ($x = 0; $x < $count; $x++) {
                $com = $cl['communities_followed'][$x];
            ?>
            <div class="Comunity-display grid">
                <div class="user-image s-2 circle">
                    <?php if (!empty($com['icon'])) : ?>
                    <img src="<?php convert_into_base64($com['icon']); ?>" alt="Avatar">

                    <?php endif; ?>
                </div>
                <div class="comunity-data-content">
                    <a href="<?php echo ("community" . "?community_id=" . $com['community_id']); ?>">
                        <h4><?php echo $com['name'] ?></h4>
                    </a>
                    <p class="t-color-3 mintext"><?php echo $com['members']; ?> Members</p>
                </div>
                <form method="POST" action="native_api/main/join">
                    <input type="hidden" name="community_id" value="<?php echo $com['community_id'] ?>">
                    <div class="comunkarity-action-content flex center">
                        <button class="follow-btn mintext btn" type="submit"
                            style="background-color: #c14848;">Leave</button>
                    </div>
                </form>
            </div>

            <?php  } ?>

        </div>
    </div>
    <?php if ($cl['page_title'] == cl_translate("Community")) : ?>
    <?php if (not_empty($cl['community_list_widget'])) : ?>
    <div class="Comunity-target target">
        <h4 class="title"><?php echo $cl['community_list_widget'][0]['widgetTitle']; ?></h4>
        <hr>
        <?php foreach ($cl['community_list_widget'] as $widget) : ?>
        <?php if (not_empty($widget['name'])) : ?>
        <div class="community_container">
            <div class="user-image s-2 circle">
                <?php if (!empty($widget['icon'])) : ?>
                <img src="<?php convert_into_base64($widget['icon']); ?>" alt="Avatar">
                <?php endif; ?>
            </div>
            <div class="comunity-data-content">
                <a href="<?php echo ("community" . "?community_id=" . $widget['community_id']); ?>">
                    <h4><?php echo $widget['name'] ?></h4>
                </a>
            </div>
        </div>
        <?php endif; ?>
        <?php endforeach; ?>
    </div>
    <?php endif; ?>
    <?php if (not_empty($cl['textarea_widget'])) : ?>
    <?php if ($cl['textarea_widget']['position'] == "leftsidebar" && not_empty($cl['textarea_widget'])) : ?>
    <div class="Comunity-target target">
        <h4 class="title"><?php echo $cl['textarea_widget']['widgetTitle']; ?></h4>
        <hr>
        <div class="comunyties-content flex col">
            <?php echo $cl['textarea_widget']['widgetContent']; ?>
        </div>
    </div>
    <?php endif; ?>
    <?php endif; ?>
    <?php if (not_empty($cl['image_widget'])) : ?>
    <?php if ($cl['image_widget']['position'] == "leftsidebar") : ?>
    <div class="Comunity-target target">
        <h4 class="title"><?php echo $cl['image_widget']['widgetTitle']; ?></h4>
        <hr>
        <div class="comunyties-content flex col">
            <img class="image_widget" src="<?php echo $cl['image_widget']['image_path']; ?>">
        </div>
    </div>
    <?php endif; ?>
    <?php endif; ?>
    <?php endif; ?>

    <div class=" Big-button btn round">AWARD STORE
    </div>
    <div class="Big-button btn round">DONATORS</div>
</section>