<?php global $community; ?>
<section class="side-bar-l flex col nd gap-1">
    <div class="Comunity-detail-target flex col target gap-2">
        <div class="user-front-page-image absolute">
            <?php if (not_empty($community['banner'])) : ?>
            <img src="<?php echo ($community['banner']); ?>" alt="Avatar">
            <?php endif; ?>
        </div>
        <div class="user-data-content community flex nd col center">
            <div class="user-image circle">
                <?php if (not_empty($community['icon'])) : ?>
                <img src="<?php if (not_empty($community['icon'])) echo ($community['icon']); ?>" alt="Avatar">
                <?php endif; ?>

            </div>
            <span class="user-name">
                <?php echo $community['name']; ?>
            </span>
            <span class="t-color-3 user-description mintext t-center">
                Lorem ipsum dolor sit amet consectetur adipisicing elit.
                Totam ducimus distinctio mollitia doloribus ea, blanditiis
                neque dolor quaerat aspernatur aliquid saepe et repudiandae
                magnam nulla natus explicabo officia ab placeat!</span>
        </div>

        <div class="btns-content grid gap-1">
            <?php if (not_empty($cl['menu_links'])) : ?>
            <?php foreach ($cl['menu_links'] as $menu_link) : ?>
            <a href="<?php echo $menu_link['url']; ?>" target="_blank">
                <div class="Big-button btn round" style="color: <?php echo $cl['display_set']['link_color']; ?>">
                    <?php echo $menu_link['tapTitle']; ?></div>
                <?php endforeach; ?>
                <?php endif; ?>
        </div>
        </a>

        <div class="account-summary grid">
            <div class="tweets-conunt flex col center"><span>1</span><span>Members</span></div>
            <div class="members-conunt flex col center"><span>1</span><span>Tweets</span></div>
        </div>
        <div class="comunity-mods-content">
            <h4 class="t-center">Community Mods</h4>
            <ul>
                <li><a href="#">
                        <h3 style="color: <?php echo $cl['display_set']['link_color']; ?>">@codeX</h3>
                    </a></li>
                <!-- <li><a href="#">
                        <h3>@someone</h3>
                    </a></li> -->
            </ul>
        </div>
        <div class="theme-switcher-content flex nd">
            <div>
                Created by :
                <a href="#">
                    <h3 style="color: <?php echo $cl['display_set']['link_color']; ?>">@codeX</h3>
                </a>
            </div>
        </div>
    </div>
    <div class="Comunity-target target">
        <h4>COMMUNITIES YOU HAVE FOLLOWED</h4>
        <hr>
        <div class="comunyties-content flex col">
            <?php shuffle($cl['communities_followed']); ?>

            <?php if (count($cl['communities_followed']) > 5) : ?>
            <?php $count = 5; ?>
            <?php else : ?>
            <?php $count = count($cl['communities_followed']); ?>
            <?php endif; ?>

            <?php for ($x = 0; $x < $count; $x++) {
                $com = $cl['communities_followed'][$x];
            ?>
            <div class="Comunity-display grid">
                <div class="comunity-image-content">
                    <div class="user-image s-2 circle">
                        <?php if (!empty($com['icon'])) : ?>
                        <img src="<?php echo $com['icon']; ?>" alt="Avatar">
                        <?php endif; ?>
                    </div>
                </div>
                <div class="comunity-data-content">
                    <a href="<?php echo ("community" . "?community_id=" . $com['community_id']); ?>">
                        <h4><?php echo $com['name'] ?></h4>
                    </a>
                    <p class="t-color-3 mintext"><?php echo $com['members']; ?> Members</p>
                </div>
                <form method="POST" action="native_api/main/join">
                    <input type="hidden" name="community_id" value="<?php echo $com['community_id'] ?>">
                    <div class="comunkarity-action-content flex center">
                        <button class="follow-btn mintext btn" type="submit"
                            style="background-color: #c14848;">Leave</button>
                    </div>
                </form>
            </div>

            <?php  } ?>

        </div>
    </div>
    <div class="Big-button btn round">AWARD STORE</div>
    <div class="Big-button btn round">DONATORS</div>
</section>