<section class="side-bar-l flex col nd gap-1">
    <div class="User-target flex col target">
        <div class="user-front-page-image absolute">
            <?php if (not_empty($me['avatar'])) : ?>
            <img src="<?php convert_into_base64($me['cover']); ?>" alt="Avatar">
            <?php endif; ?>
        </div>
        <div class="user-data-content flex nd col center">
            <div class="user-image s-1 circle">
                <?php if (not_empty($me['avatar'])) : ?>
                <img src="<?php convert_into_base64($me['avatar']); ?>" alt="Avatar">
                <?php endif; ?>
            </div>
            <span class="user-name">@<?php echo $me['username'] ?></span>
            <img class="t-color-3 user-karma" src="https://badgen.net/badge/karma/1234/46B8DF">
            <span class="t-color-3 user-member-since">
                <img class="" src="<?php convert_into_base64("themes/default/statics/img/cake.png"); ?>">

                Member Since :
                <?php $now = new DateTime();
                $date = new DateTime($me['joined']);
                //echo $date->diff($now)->format("%h Hours %i Minute %s Seconds");
                $year =  $date->diff($now)->format("%y");
                $day = $date->diff($now)->format("%d");
                $hour = $date->diff($now)->format("%h");
                $min = $date->diff($now)->format("%i");
                $sec = $date->diff($now)->format("%s");
                if ($year != "0") echo $year . " Years Ago";
                elseif ($day != "0") echo $day . " Days Ago";
                elseif ($hour != "0") echo $hour . " Hours Ago";
                elseif ($min != "0") echo $min . " Mins Ago";
                else echo $sec . " Seconds Ago";
                // echo $date->diff($now)->format("%y years %d days %h hours %i minutes"); 
                ?>
            </span>
        </div>
        <div class="account-summary grid">
            <div class="tweets-conunt flex col  center"><span>6,634</span><span>Tweets</span></div>
            <div class="comments-conunt flex col  center"><span>9,991</span><span>Comments</span></div>
            <div class="folowing-conunt flex col center"><span>5,253</span><span>Following</span></div>
            <div class="folowers-conunt flex col center"><span>4,532</span><span>Followers</span></div>

        </div>

    </div>
    <div class="Comunity-target target">
        <h4>COMMUNITIES YOU HAVE FOLLOWED</h4>
        <hr>
        <div class="col">
            <?php shuffle($cl['communities_followed']); ?>

            <?php if (count($cl['communities_followed']) > 5) : ?>
            <?php $count = 5; ?>
            <?php else : ?>
            <?php $count = count($cl['communities_followed']); ?>
            <?php endif; ?>

            <?php for ($x = 0; $x < $count; $x++) {
                $community = $cl['communities_followed'][$x];
            ?>
            <div class="row flex">
                <div class="col-lg-3 col-md-3 col-sm-3 col-xs-3">
                    <div class="user-image circle">
                        <?php if (!empty($community['icon'])) : ?>
                        <img src="<?php convert_into_base64($community['icon']); ?>" alt="Avatar">
                        <?php endif; ?>
                    </div>
                </div>
                <div class="col-lg-6 col-md-6 col-sm-4 col-xs-4">
                    <a href="<?php echo ("community" . "?community_id=" . $community['community_id']); ?>">
                        <h4><?php echo $community['name'] ?></h4>
                    </a>
                    <p class="t-color-3 mintext"><?php echo $community['members']; ?> Members</p>
                </div>
                <div class="col-lg-3 col-md-3 col-sm-5 col-xs-5">
                    <form method="POST" action="native_api/main/join">
                        <input type="hidden" name="community_id" value="<?php echo $community['community_id'] ?>">
                        <div class="comunkarity-action-content flex center">
                            <button class="follow-btn mintext btn" type="submit"
                                style="background-color: #c14848;">Leave</button>
                        </div>
                    </form>
                </div>
            </div>

            <?php  } ?>

        </div>
    </div>
    <div class="Big-button btn round">AWARD STORE</div>
    <div class="Big-button btn round">DONATORS</div>
</section>
<style>
.Management-dislplay li,
.comunyties-content .Comunity-display .comunity-data-content h4 {
    color: <?php echo $cl['display_set']['link_color'];
    ?>;
}

.Management-target .t-center,
.Rules-target .t-center,
.side-bar-l .Comunity-target h3,
.Comunity-detail-target .comunity-mods-content .t-center {
    color: <?php echo $cl['display_set']['base_color'];
    ?>;
}
</style>