<div class="right-sb-container sidebar" data-app="right-sidebar">
    <div class="sidebar__inner; padding-left:unset; ">
        <div class="right-sidebar">

            <div class="card" style="font-size: 17px">

                <div
                    style="font-size:13px;background-color:<?php echo $cl["display_set"]["base"]; ?>; color:white;padding-left:10px;padding-top:5px;padding-bottom:5px;display: flex;justify-content: space-between;padding-right:10px;">
                    About Community
                    <button
                        style="border:none; background-color:<?php echo $cl["display_set"]["base"]; ?>;color:white;">
                        <svg xmlns="http://www.w3.org/2000/svg" height="24px" viewBox="0 0 24 24" width="24px"
                            fill="#ffffff">
                            <path d="M0 0h24v24H0V0z" fill="none"></path>
                            <path
                                d="M6 10c-1.1 0-2 .9-2 2s.9 2 2 2 2-.9 2-2-.9-2-2-2zm12 0c-1.1 0-2 .9-2 2s.9 2 2 2 2-.9 2-2-.9-2-2-2zm-6 0c-1.1 0-2 .9-2 2s.9 2 2 2 2-.9 2-2-.9-2-2-2z">
                            </path>
                        </svg>

                    </button>
                </div>
                <div class="header">
                    <?php if (not_empty($me['community_icon'])) : ?>
                    <img src="<?php echo $me['community_icon']; ?>"
                        style="height: 70px; width:70px;border: 3px solid white;border-radius: 34px;z-index: 300;">
                    <?php else : ?>
                    <div
                        style="font-size:50px; color:white; background-color: <?php echo $cl["display_set"]["base"]; ?>;height: 70px; width:70px;border: 3px solid white;border-radius: 34px;z-index: 300;">
                        <div class="icon_name">r/</div>
                    </div>
                    <?php endif; ?>
                    <h4>
                        <span class="user-name-holder">
                            <span class="user-name-holder__name" style="font-weight:bold">

                                <?php echo $me['community']; ?>

                            </span>


                        </span>
                    </h4>
                </div>
                <div style="font-size:13px;padding-left:10px;padding-right:10px;padding-top:10px;">
                    A place for major news from around the world, excluding US-internal news.
                </div>
                <div
                    style="left:10px;position:relative;border-bottom:1px solid #e4eaef;padding-bottom:10px;font-weight:bold;font-size:13px;line-height:normal;width:90%;padding-top:10px;display:flex;">
                    <div>
                        29.3m<br>Members
                    </div>
                    <div style="padding-left:60px;">
                        61.4k<br>Online
                    </div>
                </div>
                <!-- /.card-header -->
                <div style="font-size: 13px;padding-left:10px;padding-bottom:10px;">
                    <img style="height: 15px;width:15px;"
                        src="https://img.icons8.com/external-bearicons-flat-bearicons/64/000000/external-DATE-capsule-hotel-bearicons-flat-bearicons.png" />
                    Created July 28, 2022
                </div>
                <div
                    style="text-align-last: center; position: relative;left:10px;width:90%; padding-bottom:10px;border-bottom:1px solid #e4eaef;">

                    <a href="<?php echo cl_link("create_post"); ?>"> <button type="button" class="btn btn-primary"
                            style="border-radius: 16px;background-color:<?php echo $cl["display_set"]["highlight"]; ?>;
											text-align: center;
											font-size: 15px;
											width: 100%;
											height: 31px;
											padding-top: 0px;
											padding-bottom: 0px;">Create Post</button></a>
                    <!-- <div style="font-size:10px;"><br></div>
                    <button type="button" class="btn btn-outline-primary" style="border-radius: 16px;
											text-align: center;
											font-size: 19px;
											width: 256px;
											height: 31px;
											padding-top: 0px;
											padding-bottom: 0px;">Create Community</button> -->

                </div>
                <div class="dropdown" style="font-size:13px;">
                    <button data-bs-toggle="collapse" data-bs-target="#demo" class="dropdown-toggle" type="button"
                        id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false"
                        style="font-size:13px;background-color:white;color:black;border:0px;padding-left:10px;width:100%; ">
                        Community Options
                    </button>
                    <div id="demo" class="collapse" style="border:0px;">
                        Lorem ipsum dolor text....
                    </div>
                </div>

            </div>
            <div class="card-header"
                style="margin-top:10px;margin-bottom:10px;background-image: url({%config theme_url%}/Homepage_files/banner.png);height: 60px;">
            </div>

            <div class="card" style="font-size: 17px">

                <div
                    style="font-size:13px;background-color:<?php echo $cl["display_set"]["base"]; ?>; color:white;padding-left:10px;padding-top:10px;padding-bottom:10px;display: flex;justify-content: space-between;padding-right:10px;">
                    r/worldnews Rules

                </div>



                <div
                    style="position:relative; left:10px; width:93%; border-bottom:1px solid #e4eaef; padding-top:5px; padding-bottom:5px;">
                    <div class="dropdown" style="font-size:13px;border-bottom:1px;">
                        <button data-bs-toggle="collapse" data-bs-target="#first" type="button" id=""
                            data-bs-toggle="dropdown" aria-expanded="false"
                            style="text-align: -webkit-left;justify-content: space-between;display:flex;font-size:13px;background-color:white;color:black;border:0px;width:100%; ">
                            1. No US InternalNews or Politics
                            <img src="https://img.icons8.com/officel/16/000000/expand-arrow.png" />
                        </button>
                        <div id="first" class="collapse" style="border:0px;">
                            Lorem ipsum dolor text....
                        </div>
                    </div>
                </div>
                <div
                    style="position:relative; left:10px; width:93%; border-bottom:1px solid #e4eaef; padding-top:5px; padding-bottom:5px;">
                    <div class="dropdown" style="font-size:13px;border-bottom:1px;">
                        <button data-bs-toggle="collapse" data-bs-target="#second" type="button" id=""
                            data-bs-toggle="dropdown" aria-expanded="false"
                            style="text-align: -webkit-left;justify-content: space-between;display:flex;font-size:13px;background-color:white;color:black;border:0px;width:100%; ">
                            2. No Editorialized or Misleading &nbsp;&nbsp;&nbsp;Titles
                            <img src="https://img.icons8.com/officel/16/000000/expand-arrow.png" />
                        </button>
                        <div id="second" class="collapse" style="border:0px;">
                            Lorem ipsum dolor text....
                        </div>
                    </div>
                </div>
                <div
                    style="position:relative; left:10px; width:93%; border-bottom:1px solid #e4eaef; padding-top:5px; padding-bottom:5px;">
                    <div class="dropdown" style="font-size:13px;border-bottom:1px;">
                        <button data-bs-toggle="collapse" data-bs-target="#third" type="button" id=""
                            data-bs-toggle="dropdown" aria-expanded="false"
                            style="text-align: -webkit-left;justify-content: space-between;display:flex;font-size:13px;background-color:white;color:black;border:0px;width:100%; ">
                            3. No Feature stories
                            <img src="https://img.icons8.com/officel/16/000000/expand-arrow.png" />
                        </button>
                        <div id="third" class="collapse" style="border:0px;">
                            Lorem ipsum dolor text....
                        </div>
                    </div>
                </div>
                <div
                    style="position:relative; left:10px; width:93%; border-bottom:1px solid #e4eaef; padding-top:5px; padding-bottom:5px;">
                    <div class="dropdown" style="font-size:13px;border-bottom:1px;">
                        <button data-bs-toggle="collapse" data-bs-target="#fourth" type="button" id=""
                            data-bs-toggle="dropdown" aria-expanded="false"
                            style="text-align: -webkit-left;justify-content: space-between;display:flex;font-size:13px;background-color:white;color:black;border:0px;width:100%; ">
                            4. No Editorials, Opinion or Analysis Pieces
                            <img src="https://img.icons8.com/officel/16/000000/expand-arrow.png" />
                        </button>
                        <div id="fourth" class="collapse" style="border:0px;">
                            Lorem ipsum dolor text....
                        </div>
                    </div>
                </div>
                <div
                    style="position:relative; left:10px; width:93%; border-bottom:1px solid #e4eaef; padding-top:5px; padding-bottom:5px;">
                    <div class="dropdown" style="font-size:13px;border-bottom:1px;">
                        <button data-bs-toggle="collapse" data-bs-target="#fifth" type="button" id=""
                            data-bs-toggle="dropdown" aria-expanded="false"
                            style="text-align: -webkit-left;justify-content: space-between;display:flex;font-size:13px;background-color:white;color:black;border:0px;width:100%; ">
                            5. No Articles In Languages Other Than English
                            <img src="https://img.icons8.com/officel/16/000000/expand-arrow.png" />
                        </button>
                        <div id="fifth" class="collapse" style="border:0px;">
                            Lorem ipsum dolor text....
                        </div>
                    </div>
                </div>
                <div
                    style="position:relative; left:10px; width:93%; border-bottom:1px solid #e4eaef; padding-top:5px; padding-bottom:5px;">
                    <div class="dropdown" style="font-size:13px;border-bottom:1px;">
                        <button data-bs-toggle="collapse" data-bs-target="#sixth" type="button" id=""
                            data-bs-toggle="dropdown" aria-expanded="false"
                            style="text-align: -webkit-left;justify-content: space-between;display:flex;font-size:13px;background-color:white;color:black;border:0px;width:100%; ">
                            6. No Images, Videos or Audio Clips
                            <img src="https://img.icons8.com/officel/16/000000/expand-arrow.png" />
                        </button>
                        <div id="sixth" class="collapse" style="border:0px;">
                            Lorem ipsum dolor text....
                        </div>
                    </div>
                </div>
                <div
                    style="position:relative; left:10px; width:93%; border-bottom:1px solid #e4eaef; padding-top:5px; padding-bottom:5px;">
                    <div class="dropdown" style="font-size:13px;border-bottom:1px;">
                        <button data-bs-toggle="collapse" data-bs-target="#seventh" type="button" id=""
                            data-bs-toggle="dropdown" aria-expanded="false"
                            style="text-align: -webkit-left;justify-content: space-between;display:flex;font-size:13px;background-color:white;color:black;border:0px;width:100%; ">
                            7. No Bigotry or Other Offensive Content
                            <img src="https://img.icons8.com/officel/16/000000/expand-arrow.png" />
                        </button>
                        <div id="seventh" class="collapse" style="border:0px;">
                            Lorem ipsum dolor text....
                        </div>
                    </div>
                </div>
                <div
                    style="position:relative; left:10px; width:93%; border-bottom:1px solid #e4eaef; padding-top:5px; padding-bottom:5px;">
                    <div class="dropdown" style="font-size:13px;border-bottom:1px;">
                        <button data-bs-toggle="collapse" data-bs-target="#eightth" type="button" id=""
                            data-bs-toggle="dropdown" aria-expanded="false"
                            style="text-align: -webkit-left;justify-content: space-between;display:flex;font-size:13px;background-color:white;color:black;border:0px;width:100%; ">
                            8. No Personal Attacks On Other Users
                            <img src="https://img.icons8.com/officel/16/000000/expand-arrow.png" />
                        </button>
                        <div id="eightth" class="collapse" style="border:0px;">
                            Lorem ipsum dolor text....
                        </div>
                    </div>
                </div>
                <div
                    style="position:relative; left:10px; width:93%; border-bottom:1px solid #e4eaef; padding-top:5px; padding-bottom:5px;">
                    <div class="dropdown" style="font-size:13px;border-bottom:1px;">
                        <button data-bs-toggle="collapse" data-bs-target="#nineth" type="button" id=""
                            data-bs-toggle="dropdown" aria-expanded="false"
                            style="text-align: -webkit-left;justify-content: space-between;display:flex;font-size:13px;background-color:white;color:black;border:0px;width:100%; ">
                            9. No Memes, Gifs, unlabeled NSFW images
                            <img src="https://img.icons8.com/officel/16/000000/expand-arrow.png" />
                        </button>
                        <div id="nineth" class="collapse" style="border:0px;">
                            Lorem ipsum dolor text....
                        </div>
                    </div>
                </div>
                <div
                    style="position:relative; left:10px; width:93%; border-bottom:1px solid #e4eaef; padding-top:5px; padding-bottom:5px;">
                    <div class="dropdown" style="font-size:13px;border-bottom:1px;">
                        <button data-bs-toggle="collapse" data-bs-target="#tenth" type="button" id=""
                            data-bs-toggle="dropdown" aria-expanded="false"
                            style="text-align: -webkit-left;justify-content: space-between;display:flex;font-size:13px;background-color:white;color:black;border:0px;width:100%; ">
                            10. No Old News Articles (> 1 Week old)
                            <img src="https://img.icons8.com/officel/16/000000/expand-arrow.png" />
                        </button>
                        <div id="tenth" class="collapse" style="border:0px;">
                            Lorem ipsum dolor text....
                        </div>
                    </div>
                </div>
            </div>
            <div class="card-header"
                style="margin-top:10px;margin-bottom:10px;background-image: url({%config theme_url%}/Homepage_files/banner.png);height: 60px;">
            </div>
            <div class="card" style="font-size: 17px">

                <div
                    style="font-size:13px;background-color:<?php echo $cl["display_set"]["base"]; ?>; color:white;padding-left:10px;padding-top:10px;padding-bottom:10px;display: flex;justify-content: space-between;padding-right:10px;">
                    Moderators
                </div>
                <div style="text-align-last: center; position: relative;left:10px;width:90%;
                    padding-bottom:10px;border-bottom:1px solid #e4eaef;padding-top:10px;">
                    <button type="button" class="btn btn-outline-primary" style="border-radius: 16px;
											text-align: center;
											font-size: 15px;
											width: 100%;
											height: 31px;
											padding-top: 0px;
											padding-bottom: 0px;"><i class="fa fa-envelope-o" style="font-size:20px;padding-right:5px;"></i>Message the
                        mods
                    </button>
                    <div style="text-align-last: left;padding-top:10px;padding-bottom:10px; color:#3a719c;">
                        u/green_flash
                    </div>
                    <div style="text-align-last: left;padding-top:10px;padding-bottom:10px;color:#3a719c;">
                        u/PraiseBeToScience
                    </div>
                    <div style="text-align-last: left;padding-top:10px;padding-bottom:10px;color:#3a719c;">
                        u/WorldNewsMods
                    </div>
                </div>

            </div>
        </div>
        <div class="right-sidebar__footer">
            <?php //echo cl_template('main/footer'); 
            ?>
        </div>
        <?php if (not_empty($cl["gads_vert"])) : ?>
        <div class="right-sidebar__ads">
            <div class="cl-google-ads">
                <?php echo $cl["gads_vert"]; ?>
            </div>
        </div>
        <?php endif; ?>
    </div>
</div>
</div>