<?php global $community; ?>
<section class="side-bar-r flex col nd gap-2">
    <div class="Advertisement"></div>
    <div class="Rules-target target">
        <h2 class="t-center">Lorem, ipsum.</h2>
        <hr>
        <div class="rues-content mintext t-color-3">
            <ol class="flex col gap-1">
                <li>
                    <input class="hidden" id="rule-1-control" type="checkbox">
                    <label class="flex btn bg-3" for="rule-1-control">Lorem ipsum dolor sit amet</label>
                    <div class="rule-description-content">
                        <h4> Lorem ipsum dolor sit amet</h4>
                        <p>
                            Lorem ipsum dolor sit amet consecteturadipisicing elit. Deleniti cum magni
                            exercitationem facilis. Neque molestias
                            similique pariatur quasi! Consectetur
                            ea quas a rem excepturi, dicta dolores
                            temporibus explicabo sunt? Consequatur.
                        </p>
                    </div>
                </li>
                <li>
                    <input class="hidden" id="rule-2-control" type="checkbox">
                    <label class="flex btn bg-3" for="rule-2-control">Lorem ipsum dolor sit amet</label>
                    <div class="rule-description-content">
                        <h4> Lorem ipsum dolor sit amet</h4>
                        <p>
                            Lorem ipsum dolor sit amet consecteturadipisicing elit. Deleniti cum magni
                            exercitationem facilis. Neque molestias
                            similique pariatur quasi! Consectetur
                            ea quas a rem excepturi, dicta dolores
                            temporibus explicabo sunt? Consequatur.
                        </p>
                    </div>
                </li>
                <li>
                    <input class="hidden" id="rule-3-control" type="checkbox">
                    <label class="flex btn bg-3" for="rule-3-control">Lorem ipsum dolor sit amet</label>
                    <div class="rule-description-content">
                        <h4> Lorem ipsum dolor sit amet</h4>
                        <p>
                            Lorem ipsum dolor sit amet consecteturadipisicing elit. Deleniti cum magni
                            exercitationem facilis. Neque molestias
                            similique pariatur quasi! Consectetur
                            ea quas a rem excepturi, dicta dolores
                            temporibus explicabo sunt? Consequatur.
                        </p>
                    </div>
                </li>
                <li>
                    <input class="hidden" id="rule-4-control" type="checkbox">
                    <label class="flex btn bg-3" for="rule-4-control">Lorem ipsum dolor sit amet</label>
                    <div class="rule-description-content">
                        <h4> Lorem ipsum dolor sit amet</h4>
                        <p>
                            Lorem ipsum dolor sit amet consecteturadipisicing elit. Deleniti cum magni
                            exercitationem facilis. Neque molestias
                            similique pariatur quasi! Consectetur
                            ea quas a rem excepturi, dicta dolores
                            temporibus explicabo sunt? Consequatur.
                        </p>
                    </div>
                </li>
            </ol>
        </div>
    </div>
    <div class="Advertisement"></div>
    <div class="Management-target target">
        <h3 class="t-center t-color-3">
            <img src="<?php convert_into_base64("themes/default/statics/img/management.png"); ?>">
            Management
        </h3>
        <hr>
        <div class="management-content flex col gap-1">
            <div class="Management-dislplay">
                <h4>🎆 QUEUES</h4>
                <ul style="color: <?php echo $cl['display_set']['link_color']; ?>">
                    <a href="mod_mail?community_id=<?php echo $_GET['community_id']; ?>">
                        <li class="t-color-3">Mod Mail</li>
                    </a>
                    <li class="t-color-3">Unmoderated Posts</li>
                    <li class="t-color-3">Reports</li>
                    <li class="t-color-3">Spam</li>
                </ul>
            </div>
            <div class="Management-dislplay">
                <h4>🎆 USER MANAGEMENT</h4>
                <ul style="color: <?php echo $cl['display_set']['link_color']; ?>">
                    <li class="t-color-3">Banning</li>
                    <li class="t-color-3">Moderators</li>
                    <li class="t-color-3">Approved Users</li>
                </ul>
            </div>
            <div class="Management-dislplay">
                <h4>🎆 FLAIR EMOJIS</h4>
                <ul style="color: <?php echo $cl['display_set']['link_color']; ?>">
                    <li class="t-color-3">Grant Use Flair</li>
                    <a href="post_flairs?community_id=<?php echo $cl['community_id']; ?>">
                        <li class="t-color-3">Post Flairs</li>
                    </a>
                </ul>
            </div>
            <div class="Management-dislplay">
                <h4>🎆 RULES AND REGULATIONS</h4>
                <ul style="color: <?php echo $cl['display_set']['link_color']; ?>">
                    <li class="t-color-3">Community Rules</li>
                    <li class="t-color-3">Automod</li>
                </ul>
            </div>
            <div class="Management-dislplay">
                <h4>🎆 OTHER</h4>
                <ul style="color: <?php echo $cl['display_set']['link_color']; ?>">
                    <?php if ($community['moderator'] == $me['id']) : ?>
                    <a href="community_appearance?community_id=<?php echo $cl['community_id']; ?>">
                        <li class="t-color-3">Community Appearance</li>
                    </a>
                    <?php endif; ?>
                    <a href="sidebar_widget?community_id=<?php echo $cl['community_id']; ?>">
                        <li class="t-color-3">Sidebar Widget</li>
                    </a>
                    <li class="t-color-3">Community Settings</li>
                    <a href="community_menu?community_id=<?php echo $cl['community_id']; ?>">
                        <li class="t-color-3">Menu</li>
                    </a>
                    <a href="post_settings?community_id=<?php echo $cl['community_id']; ?>">
                        <li class="t-color-3">Post Settings</li>
                    </a>
                    <li class="t-color-3">Traffic Statistics</li>
                    <li class="t-color-3">Moderation log</li>

                </ul>
            </div>
        </div>
    </div>
    <?php if (not_empty($cl['textarea_widget'])) foreach ($cl['textarea_widget'] as $widget) : ?>
    <?php if ($widget['position'] == "rightsidebar") : ?>
    <div class="Comunity-target target">
        <h4 class="title"><?php echo $widget['widgetTitle']; ?></h4>
        <hr>
        <div class="comunyties-content flex col">
            <?php echo $widget['widgetContent']; ?>
        </div>
    </div>
    <?php endif; ?>
    <?php endforeach; ?>
    <?php if (not_empty($cl['image_widget'])) foreach ($cl['image_widget'] as $widget) : ?>
    <?php if ($widget['position'] == "rightsidebar") : ?>
    <div class="Comunity-target target">
        <h4 class="title"><?php echo $widget['widgetTitle']; ?></h4>
        <hr>
        <div class="comunyties-content flex col">
            <img class="image_widget" src="<?php echo $widget['image_path']; ?>">
        </div>
    </div>
    <?php endif; ?>
    <?php endforeach; ?>
</section>

<style>
.Management-dislplay li,
.comunyties-content .Comunity-display .comunity-data-content h4 {
    color: <?php echo $cl['display_set']['link_color'];
    ?>;
}

.Management-target .t-center,
.Rules-target .t-center,
.side-bar-l .Comunity-target h3,
.Comunity-detail-target .comunity-mods-content .t-center {
    color: <?php echo $cl['display_set']['base_color'];
    ?>;
}
</style>