<section class="side-bar-r flex col nd gap-2">
    <div class="Advertisement"></div>
    <div class="Rules-target target">
        <h2 class="t-center">Lorem, ipsum.</h2>
        <div class="rues-content mintext t-color-3">
            <ol class="flex col gap-1">
                <li>
                    <input class="hidden" id="rule-1-control" type="checkbox">
                    <label class="flex btn bg-3" for="rule-1-control">Lorem ipsum dolor sit amet</label>
                    <div class="rule-description-content">
                        <h4> Lorem ipsum dolor sit amet</h4>
                        <p>
                            Lorem ipsum dolor sit amet consecteturadipisicing elit. Deleniti cum magni
                            exercitationem facilis. Neque molestias
                            similique pariatur quasi! Consectetur
                            ea quas a rem excepturi, dicta dolores
                            temporibus explicabo sunt? Consequatur.
                        </p>
                    </div>
                </li>
                <li>
                    <input class="hidden" id="rule-2-control" type="checkbox">
                    <label class="flex btn bg-3" for="rule-2-control">Lorem ipsum dolor sit amet</label>
                    <div class="rule-description-content">
                        <h4> Lorem ipsum dolor sit amet</h4>
                        <p>
                            Lorem ipsum dolor sit amet consecteturadipisicing elit. Deleniti cum magni
                            exercitationem facilis. Neque molestias
                            similique pariatur quasi! Consectetur
                            ea quas a rem excepturi, dicta dolores
                            temporibus explicabo sunt? Consequatur.
                        </p>
                    </div>
                </li>
                <li>
                    <input class="hidden" id="rule-3-control" type="checkbox">
                    <label class="flex btn bg-3" for="rule-3-control">Lorem ipsum dolor sit amet</label>
                    <div class="rule-description-content">
                        <h4> Lorem ipsum dolor sit amet</h4>
                        <p>
                            Lorem ipsum dolor sit amet consecteturadipisicing elit. Deleniti cum magni
                            exercitationem facilis. Neque molestias
                            similique pariatur quasi! Consectetur
                            ea quas a rem excepturi, dicta dolores
                            temporibus explicabo sunt? Consequatur.
                        </p>
                    </div>
                </li>
                <li>
                    <input class="hidden" id="rule-4-control" type="checkbox">
                    <label class="flex btn bg-3" for="rule-4-control">Lorem ipsum dolor sit amet</label>
                    <div class="rule-description-content">
                        <h4> Lorem ipsum dolor sit amet</h4>
                        <p>
                            Lorem ipsum dolor sit amet consecteturadipisicing elit. Deleniti cum magni
                            exercitationem facilis. Neque molestias
                            similique pariatur quasi! Consectetur
                            ea quas a rem excepturi, dicta dolores
                            temporibus explicabo sunt? Consequatur.
                        </p>
                    </div>
                </li>
            </ol>
        </div>
    </div>
    <div class="Advertisement"></div>
    <div class="Management-target target">
        <h2 class="t-center t-color-3">🛠 Management</h2>
        <div class="management-content flex col gap-1">
            <div class="Management-dislplay">
                <h3>🎆 some text</h3>
                <ul>
                    <li class="t-color-3">Lorem, ipsum.</li>
                    <li class="t-color-3">Lorem, ipsum.</li>
                    <li class="t-color-3">Lorem, ipsum.</li>
                    <li class="t-color-3">Lorem, ipsum.</li>
                </ul>
            </div>
            <div class="Management-dislplay">
                <h3>🎆 some text</h3>
                <ul>
                    <li class="t-color-3">Lorem, ipsum.</li>
                    <li class="t-color-3">Lorem, ipsum.</li>
                    <li class="t-color-3">Lorem, ipsum.</li>
                    <li class="t-color-3">Lorem, ipsum.</li>
                </ul>
            </div>
            <div class="Management-dislplay">
                <h3>🎆 some text</h3>
                <ul>
                    <li class="t-color-3">Lorem, ipsum.</li>
                    <li class="t-color-3">Lorem, ipsum.</li>
                    <li class="t-color-3">Lorem, ipsum.</li>
                    <li class="t-color-3">Lorem, ipsum.</li>
                </ul>
            </div>
            <div class="Management-dislplay">
                <h3>🎆 some text</h3>
                <ul>
                    <li class="t-color-3">Lorem, ipsum.</li>
                    <li class="t-color-3">Lorem, ipsum.</li>
                    <li class="t-color-3">Lorem, ipsum.</li>
                    <li class="t-color-3">Lorem, ipsum.</li>
                </ul>
            </div>
        </div>
    </div>
</section>