<section class="side-bar-r flex col nd gap-1">
    <div class="Advertisement"></div>
    <div class="Trends-target target">
        <h4 class="title">Lorem, ipsum dolor.</h4>
        <h4>Lorem, ipsum dolor.</h4>
        <div class="conconfig-btn btn absolute">⚙</div>
        <div class="trending-content flex col">
            <div class="Trend-display flex nd">
                <div class="trend-data-content"><a class="tag" href="#">#SomeTag</a>
                    <p class="tweets-conunt t-color-3 mintext">97.7 k tweets</p>
                </div>
                <div class="options-btn-content flex nd center">
                    <div class="Option-button flex center btn">
                        <div class="circle"></div>
                        <div class="circle"></div>
                        <div class="circle"></div>
                    </div>
                </div>
            </div>
            <div class="Trend-display flex nd">
                <div class="trend-data-content"><a class="tag" href="#">#SomeTag</a>
                    <p class="tweets-conunt t-color-3 mintext">97.7 k tweets</p>
                </div>
                <div class="options-btn-content flex nd center">
                    <div class="Option-button flex center btn">
                        <div class="circle"></div>
                        <div class="circle"></div>
                        <div class="circle"></div>
                    </div>
                </div>
            </div>
            <div class="Trend-display flex nd">
                <div class="trend-data-content"><a class="tag" href="#">#SomeTag</a>
                    <p class="tweets-conunt t-color-3 mintext">97.7 k tweets</p>
                </div>
                <div class="options-btn-content flex nd center">
                    <div class="Option-button flex center btn">
                        <div class="circle"></div>
                        <div class="circle"></div>
                        <div class="circle"></div>
                    </div>
                </div>
            </div>
            <div class="Trend-display flex nd">
                <div class="trend-data-content"><a class="tag" href="#">#SomeTag</a>
                    <p class="tweets-conunt t-color-3 mintext">97.7 k tweets</p>
                </div>
                <div class="options-btn-content flex nd center">
                    <div class="Option-button flex center btn">
                        <div class="circle"></div>
                        <div class="circle"></div>
                        <div class="circle"></div>
                    </div>
                </div>
            </div>
            <div class="Trend-display flex nd">
                <div class="trend-data-content"><a class="tag" href="#">#SomeTag</a>
                    <p class="tweets-conunt t-color-3 mintext">97.7 k tweets</p>
                </div>
                <div class="options-btn-content flex nd center">
                    <div class="Option-button flex center btn">
                        <div class="circle"></div>
                        <div class="circle"></div>
                        <div class="circle"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="Advertisement"></div>
    <a href="create_community">
        <div class="Big-button btn round" style="color: <?php echo $cl['display_set']['link_color']; ?>">CREATE
            COMMUNITY</div>
    </a>
    <div class="Big-button btn round" style="color: <?php echo $cl['display_set']['link_color']; ?>">EXPLORE TWITTOR
    </div>
    <div class="Comunity-target target">
        <h4 class="title">COMMUNITIES TO FOLLOW</h4>
        <hr>
        <div class="comunyties-content flex col">
            <?php if (count($cl['communities_can_follow']) > 5) : ?>
            <?php $random = array_rand($cl['communities_can_follow'], 5); ?>
            <?php else : ?>
            <?php $random = array_rand($cl['communities_can_follow'], count($cl['communities_can_follow']));
                shuffle($cl['communities_can_follow']); ?>
            <?php endif; ?>

            <?php foreach ($random as  $index) {
                $community = $cl['communities_can_follow'][$index];
            ?>
            <div class="Comunity-display grid">
                <div class="comunity-image-content">
                    <div class="user-image s-2 circle">
                        <?php if (!empty($community['icon'])) : ?>
                        <img src="<?php convert_into_base64($community['icon']); ?>" alt="Avatar">
                        <?php endif; ?>
                    </div>
                </div>
                <div class="comunity-data-content">
                    <a href="<?php echo ("community" . "?community_id=" . $community['community_id']); ?>">
                        <h4><?php echo $community['name'] ?></h4>
                    </a>
                    <p class="t-color-3 mintext"><?php echo $community['members']; ?> Members</p>
                </div>
                <form method="POST" action="native_api/main/follow">
                    <input type="hidden" name="community_id" value="<?php echo $community['community_id'] ?>">
                    <div class="comunkarity-action-content flex center">
                        <button class="follow-btn mintext btn" type="submit">Join</button>
                    </div>
                </form>
            </div>

            <?php  } ?>

        </div>
    </div>
    <div class="Comunity-target target">
        <h4 class="title">PEOPLE YOU MAY KNOW</h4>
        <hr>
        <div class="comunyties-content flex col">


            <?php shuffle($cl['users']); ?>

            <?php if (count($cl['users']) > 5) : ?>
            <?php $count = 5; ?>
            <?php else : ?>
            <?php $count = count($cl['users']); ?>
            <?php endif; ?>

            <?php for ($x = 0; $x < $count; $x++) {
                $user = $cl['users'][$x];
            ?>

            <div class="Comunity-display grid">
                <div class="comunity-image-content">
                    <div class="user-image s-2 circle">
                        <?php if (!empty($user['avatar'])) : ?>
                        <img src="<?php convert_into_base64($user['avatar']); ?>" alt="Avatar">
                        <?php endif; ?>
                    </div>
                </div>
                <div class="comunity-data-content">
                    <a href="">
                        <h4><?php echo $user['username'] ?></h4>
                    </a>
                </div>
                <form method="POST" action="native_api/main/follow">
                    <div class="comunkarity-action-content flex center">
                        <button class="follow-btn mintext btn" type="submit">Follow</button>
                    </div>
                </form>
            </div>

            <?php  } ?>

        </div>
    </div>

</section>