<section class="side-bar-r flex col nd gap-2">
    <div class="Advertisement"></div>
    <div class="Rules-target target">
        <h2 class="t-center">Lorem, ipsum.</h2>
        <div class="rues-content mintext t-color-3">
            <ol class="flex col gap-1">
                <li>
                    <input class="hidden" id="rule-1-control" type="checkbox">
                    <label class="flex btn bg-3" for="rule-1-control">Lorem ipsum dolor sit amet</label>
                    <div class="rule-description-content">
                        <h4> Lorem ipsum dolor sit amet</h4>
                        <p>
                            Lorem ipsum dolor sit amet consecteturadipisicing elit. Deleniti cum magni
                            exercitationem facilis. Neque molestias
                            similique pariatur quasi! Consectetur
                            ea quas a rem excepturi, dicta dolores
                            temporibus explicabo sunt? Consequatur.
                        </p>
                    </div>
                </li>
                <li>
                    <input class="hidden" id="rule-2-control" type="checkbox">
                    <label class="flex btn bg-3" for="rule-2-control">Lorem ipsum dolor sit amet</label>
                    <div class="rule-description-content">
                        <h4> Lorem ipsum dolor sit amet</h4>
                        <p>
                            Lorem ipsum dolor sit amet consecteturadipisicing elit. Deleniti cum magni
                            exercitationem facilis. Neque molestias
                            similique pariatur quasi! Consectetur
                            ea quas a rem excepturi, dicta dolores
                            temporibus explicabo sunt? Consequatur.
                        </p>
                    </div>
                </li>
                <li>
                    <input class="hidden" id="rule-3-control" type="checkbox">
                    <label class="flex btn bg-3" for="rule-3-control">Lorem ipsum dolor sit amet</label>
                    <div class="rule-description-content">
                        <h4> Lorem ipsum dolor sit amet</h4>
                        <p>
                            Lorem ipsum dolor sit amet consecteturadipisicing elit. Deleniti cum magni
                            exercitationem facilis. Neque molestias
                            similique pariatur quasi! Consectetur
                            ea quas a rem excepturi, dicta dolores
                            temporibus explicabo sunt? Consequatur.
                        </p>
                    </div>
                </li>
                <li>
                    <input class="hidden" id="rule-4-control" type="checkbox">
                    <label class="flex btn bg-3" for="rule-4-control">Lorem ipsum dolor sit amet</label>
                    <div class="rule-description-content">
                        <h4> Lorem ipsum dolor sit amet</h4>
                        <p>
                            Lorem ipsum dolor sit amet consecteturadipisicing elit. Deleniti cum magni
                            exercitationem facilis. Neque molestias
                            similique pariatur quasi! Consectetur
                            ea quas a rem excepturi, dicta dolores
                            temporibus explicabo sunt? Consequatur.
                        </p>
                    </div>
                </li>
            </ol>
        </div>
    </div>
    <div class="Advertisement"></div>
    <div class="Management-target target">
        <h2 class="t-center t-color-3">🛠 Management</h2>
        <div class="management-content flex col gap-1">
            <div class="Management-dislplay">
                <h3>🎆 QUEUES</h3>
                <ul>
                    <li class="t-color-3">Mod Mail</li>
                    <li class="t-color-3">Unmoderated Posts</li>
                    <li class="t-color-3">Reports</li>
                    <li class="t-color-3">Spam</li>
                </ul>
            </div>
            <div class="Management-dislplay">
                <h3>🎆 USER MANAGEMENT</h3>
                <ul>
                    <li class="t-color-3">Banning</li>
                    <li class="t-color-3">Moderators</li>
                    <li class="t-color-3">Approved Users</li>
                </ul>
            </div>
            <div class="Management-dislplay">
                <h3>🎆 FLAIR EMOJIS</h3>
                <ul>
                    <li class="t-color-3">Grant Use Flair</li>
                    <li class="t-color-3">Post Flair</li>
                </ul>
            </div>
            <div class="Management-dislplay">
                <h3>🎆 RULES AND REGULATIONS</h3>
                <ul>
                    <li class="t-color-3">Community Rules</li>
                    <li class="t-color-3">Automod</li>
                </ul>
            </div>
            <div class="Management-dislplay">
                <h3>🎆 OTHER</h3>
                <ul>
                    <li class="t-color-3">Menu</li>
                    <li class="t-color-3">Create Awards</li>
                    <li class="t-color-3">Wiki Pages</li>
                    <li class="t-color-3">Community Settings</li>
                    <li class="t-color-3">Community Appearance</li>
                    <li class="t-color-3">Post Settings</li>
                    <li class="t-color-3">Traffic Statistics</li>
                    <li class="t-color-3">Moderation log</li>

                </ul>
            </div>
        </div>
    </div>
</section>