<?php if ($cl["auth_type"] == "login") : ?>
<?php echo cl_template('auth/login'); ?>
<?php elseif ($cl["auth_type"] == "forgot_pass") : ?>
<?php echo cl_template('auth/reset_password'); ?>
<?php elseif ($cl["auth_type"] == "reset_pass" && not_empty($cl['em_code'])) : ?>
<?php echo cl_template('auth/new_password'); ?>
<?php else : ?>
<?php if ($cl['config']['user_signup'] == "on" || not_empty($cl["invite_code_status"])) : ?>
<?php echo cl_template('auth/register'); ?>
<?php else : ?>
<?php echo cl_template('auth/register_off'); ?>
<?php endif; ?>
<?php endif; ?>