<div class="content__inner">
    <h2>Search hashtags</h2>
    <p>
        Please use this <strong>(<?php echo cl_link("mobile_api/search_hashtags"); ?>)</strong> API to access hashtags searching endpoint
    </p>
    <br>
    <h4 class="table-title">Get parameters</h4>
    <table class="table table-bordered">
        <thead>
        <tr>
            <th width="15%">Field</th>
            <th width="25%">Value</th>
            <th width="45%">Remarks</th>
        </tr>
        </thead>
        <tbody>
            <tr>
                <td>query</td>
                <td>Search keywords</td>
                <td>
                    E.g. Covid19
                </td>
            </tr>
            <tr>
                <td>offset</td>
                <td>Last post offset ID</td>
                <td>
                    This is only needed when loading posts of the pagination system.
                </td>
            </tr>
            <tr>
                <td>session_id (Optional)</td>
                <td>​Access token ID</td>
                <td>
                    E.g. de25cc16eb00960f076...
                </td>
            </tr>
            <tr>
                <td>page_size</td>
                <td>​Total post limit for each request</td>
                <td>
                    Recommended: 20
                </td>
            </tr>
        </tbody>
    </table>
    <h4 class="table-title">Success response</h4>
    <div class="code-holder">
        <div class="code-holder-inner">
    <pre><code class="json">{
        "code": 200,
        "message": "Results found",
        "data":[
            {
                "id": 6,
                "posts": 1,
                "tag": "covid",
                "time": "1605781894",
                "hashtag": "#covid",
                "url": "http://colibri.loc/search/posts?q=covid",
                "total": "1"
            }
        ]
    }
    </code></pre>
        </div>
    </div>
    <h4 class="table-title">Error responses</h4>
    <div class="code-holder">
        <div class="code-holder-inner">
    <pre><code class="json">{
        "code": 204,
        "message": "No data found",
        "data": []
    }

    {
        "code": 400,
        "message": "The search term is invalid or missing",
        "data": []
    }
    </code></pre>
        </div>
    </div>
</div>