<div class="cp-app-container" data-app="account-verification">
    <div class="current-page-name">
        <div class="lp">
            <h2>
                Account verification
            </h2>
            <ol class="breadcrumb">
                <li>
                    <a href="<?php echo cl_link('admin_panel'); ?>">
                        Control panel
                    </a>
                </li>
                <li class="active">
                    <a href="">
                        Account verification
                    </a>
                </li>
            </ol>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card" id="vue-cpanel-account-verification-app">
                <div class="header">
                    <h2>
                        Account Verification requests - (<?php echo $cl['requests_total'] ?>)
                    </h2>
                </div>
                <div class="body">
                    <div class="regular-table">
                        <table class="table table-hover no-mb">
                            <thead>
                                <tr>
                                    <th>ID</th>
                                    <th>
                                        Username
                                    </th>

                                    <th>
                                        Last seen
                                    </th>

                                    <th>
                                        Status
                                    </th>
                                    <th>
                                        Requested at
                                    </th>
                                    <th>
                                        Action
                                    </th>
                                </tr>
                            </thead>
                            <tbody data-an="requests-list">
                                <?php if (not_empty($cl['requests'])) : ?>
                                <?php foreach ($cl['requests'] as $cl['li']) : ?>
                                <?php echo cl_template('cpanel/assets/account_verification/includes/list_item'); ?>
                                <?php endforeach; ?>
                                <?php else : ?>
                                <tr>
                                    <td colspan="7">
                                        <div class="empty-table">
                                            <span class="icon">
                                                <?php echo cl_ikon("verified"); ?>
                                            </span>
                                            <h4><?php echo ('No requests found'); ?></h4>
                                            <p>
                                                <?php echo ('It looks like there are no account verification requests in your database yet. All account verification requests will be displayed here.'); ?>
                                            </p>
                                        </div>
                                    </td>
                                </tr>
                                <?php endif; ?>
                            </tbody>
                        </table>
                        <div class="table-pagination">
                            <a <?php if ($_GET['page'] > 1) echo ("href='./users?page=" . (string)($_GET['page'] - 1) . "'"); ?>
                                class="pagination-ctrls prev">
                                <?php echo cl_ikon("chevron-left"); ?>
                            </a>
                            <a <?php if (count($cl['requests']) > 1) echo ("href='./users?page=" . (string)($_GET['page'] ? $_GET['page'] + 1 : 2) . "'"); ?>
                                class="pagination-ctrls prev">
                                <?php echo cl_ikon("chevron-right"); ?>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<?php //echo cl_template('cpanel/assets/account_verification/scripts/app_master_script'); 
?>