<section class="main flex col nd gap-1">

    <div class="Post-bar target flex timeline gap-1">

        <div class="controls-content">
            <p class="content_title">BOOKMARKS</p>
            <p class="subtitle">This is where all saved posts from communities you joined and members you followed will
                show
                up.</p>
        </div>

    </div>
    <?php if (not_empty($cl["bookmarks"])) : ?>
    <div class="timeline-posts-container">
        <div class="timeline-posts-ls gap-1 grid col nd" data-an="entry-list">
            <?php foreach ($cl["bookmarks"] as $cl['li']) : ?>
            <?php echo cl_template('timeline/post_bookmarks'); ?>
            <?php endforeach; ?>
        </div>

        <?php if (count($cl["bookmarks"]) == 30) : ?>
        <div class="timeline-data-loader">
            <button class="btn btn-custom main-outline lg" data-an="load-more">
                <?php echo cl_translate("Show more"); ?>
            </button>
        </div>
        <?php endif; ?>
    </div>
    <?php else : ?>
    <div class="timeline-placeholder">
        <div class="icon">
            <div class="icon__bg">
                <?php echo cl_icon('bookmark'); ?>
            </div>
        </div>
        <div class="pl-message">
            <h4>
                <?php echo cl_translate("No bookmarks yet!"); ?>
            </h4>
            <p>
                <?php echo cl_translate("It looks like you don't have any bookmarks yet. To add a post to the list of your bookmarks, open the menu at the bottom of the publication and click on (Add to Bookmarks)"); ?>
            </p>
        </div>
        <div class="c2action-single">
            <a href="<?php echo cl_link('/'); ?>" data-spa="true">
                <button class="btn btn-custom main-outline lg">
                    <?php echo cl_translate("Go to the homepage"); ?>
                </button>
            </a>
        </div>
    </div>
    <?php endif; ?>

    <?php //echo cl_template('bookmarks/scripts/app_master_script'); 
    ?>
</section>