<div class="cp-app-container" data-app="affiliates-settings">
    <div class="current-page-name">
        <div class="lp">
            <h2>
                Affiliates settings
            </h2>
            <ol class="breadcrumb">
                <li>
                    <a href="<?php echo cl_link('admin_panel'); ?>">
                        Control panel
                    </a>
                </li>
                <li class="active">
                    <a href="">
                        Affiliates settings
                    </a>
                </li>
            </ol>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card">
                <div class="header">
                    <h2>
                        Manage affiliates system settings
                    </h2>
                </div>
                <div class="body">
                    <form class="form" data-an="form">
                        <div class="row">
                            <div class="col-sm-12">
                                <div class="form-group" data-an="aff_bonus_rate-input">
                                    <label>
                                        Affiliate bonus rate
                                    </label>
                                    <div class="form-line">
                                        <input value="{%config aff_bonus_rate%}" name="aff_bonus_rate" type="text"
                                            class="form-control" placeholder="E. g. 0.50">
                                    </div>
                                </div>
                            </div>
                            <div class="col-sm-12">
                                <div class="form-group" data-an="aff_payout_min-input">
                                    <label>
                                        Affiliate payout min amount (Default <?php echo cl_money('50'); ?>)
                                    </label>
                                    <div class="form-line">
                                        <input value="{%config aff_payout_min%}" name="aff_payout_min" type="text"
                                            class="form-control" placeholder="E. g. <?php echo cl_money('50'); ?>">
                                    </div>
                                    <small class="info-feedback">
                                        This field defines the minimum amount of payments of the affiliate program
                                    </small>
                                </div>
                            </div>
                            <div class="col-sm-12">
                                <div class="form-group" data-an="affiliates_system-input">
                                    <label>
                                        Affiliates System
                                    </label>
                                    <div class="form-line">
                                        <select name="affiliates_system" class="form-control selectpicker">
                                            <option value="on"
                                                <?php if($cl['config']['affiliates_system'] == 'on') { echo('selected'); } ?>>
                                                Enabled
                                            </option>
                                            <option value="off"
                                                <?php if($cl['config']['affiliates_system'] == 'off') { echo('selected'); } ?>>
                                                Disabled
                                            </option>
                                        </select>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-sm-12 no-mb">
                                <button data-an="submit-ctrl" type="submit"
                                    class="btn bg-blue btn-block btn-lg waves-effect ttup">
                                    Save changes
                                </button>
                            </div>
                        </div>
                        <input type="hidden" class="d-none"
                            value="<?php echo fetch_or_get($cl['csrf_token'],'none'); ?>" name="hash">
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<?php // echo cl_template('cpanel/assets/affiliate_settings/scripts/app_master_script'); ?>