<form class="form" id="cl-login-vue-app" method="POST" action="native_api/auth/login" autocomplete="off">
    <div class="form-title">
        <h2>
            <?php echo cl_translate("Sign in"); ?>
        </h2>
    </div>
    <div class="form-group">
        <label class="input-label">
            <?php echo cl_translate("Username"); ?>
        </label>
        <input name="email" v-model.trim.lazy="$v.email.$model" type="text" class="form-control"
            placeholder="<?php echo cl_translate("Username"); ?>">
        <div class="invalid-main-feedback" v-if="is_valid_email">
        </div>
    </div>
    <div class="form-group">
        <label class="input-label">
            <?php echo cl_translate("Password"); ?>
        </label>
        <div class="password-ctrl">
            <input type="password" name="password" class="form-control"
                placeholder="<?php echo cl_translate("Password"); ?>">

            <button class="password-ctrl" type="button" v-on:click="password_display_toggle">
                <span v-if="password_display == 'password'">
                    <?php echo cl_icon("visibility"); ?>
                </span>

            </button>
        </div>
        <div class="invalid-main-feedback" v-if="is_valid_password">
        </div>
    </div>

    <div class="form-group">
        <button type="submit" class="btn btn-custom main-inline lg btn-block">
            <?php echo cl_translate("Login"); ?>
        </button>
    </div>


    <div class="form-group no-mb">
        <div class="form-cta-link">
            <span>
                <?php echo cl_translate("Don't have an account?"); ?>
            </span>
            <a href="<?php echo cl_link('guest?auth=signup'); ?>">
                <?php echo cl_translate("Sign up"); ?>
            </a>
        </div>
    </div>
    <input type="hidden" class="d-none" value="<?php echo fetch_or_get($cl['csrf_token'], 'none'); ?>" name="hash">
</form>