<!-- <form class="form" id="cl-signup-vue-app" method="POST" action="native_api/auth/signup" autocomplete="off">
    <div class="form-title">
        <h2>
            <?php echo cl_translate("Create an account"); ?>
        </h2>
        <p>
            <?php echo cl_translate("Please fill out this information to create an account!"); ?>
        </p>
    </div>
    <div class="form-group">
        <label><?php echo cl_translate("Username"); ?></label>
        <input name="uname" type="text" class="form-control"
            placeholder="<?php echo cl_translate("Choose your username"); ?>">
        <div class="invalid-main-feedback" v-if="is_valid_uname">

        </div>
    </div>

    <div class="form-group">
        <label>
            <?php echo cl_translate("Password"); ?>
        </label>
        <div class="password-ctrl">
            <input type="password" name="password" v-model.trim.lazy="$v.password.$model"
                v-bind:type="password1_display" class="form-control"
                placeholder="<?php echo cl_translate("Create a password for your account"); ?>">

            <button class="password-ctrl" type="button" v-on:click="password1_display_toggle">
                <span v-if="password1_display == 'password'">
                    <?php echo cl_icon("visibility"); ?>
                </span>

            </button>
        </div>
        <div class="invalid-main-feedback" v-if="is_valid_password">
        </div>
    </div>
    <div class="form-group">
        <label>
            <?php echo cl_translate("Confirm the password"); ?>
        </label>
        <div class="password-ctrl">
            <input type="password" name="conf_pass" v-model.trim="$v.password2.$model" v-bind:type="password2_display"
                class="form-control" placeholder="<?php echo cl_translate("Confirm the password"); ?>">

            <button class="password-ctrl" type="button" v-on:click="password2_display_toggle">
                <span v-if="password2_display == 'password'">
                    <?php echo cl_icon("visibility"); ?>
                </span>

            </button>
        </div>
        <div class="invalid-main-feedback" v-if="is_valid_password2">
        </div>
    </div>
    <div class="form-group">
        <div class="form-tos">
            <div class="form-check">
                <input v-model="tos_agree" class="form-check-input" type="checkbox" value="" id="tos-agree">
                <label class="form-check-label" for="tos-agree" style="margin-left:20px;">
                    <span>
                        <?php echo cl_translate("By continuing, you agree to {@site_name@}", array(
                            "site_name" => $cl["config"]["name"]
                        )); ?>
                    </span>
                    <a href="<?php echo cl_link('terms_of_use'); ?>"><?php echo cl_translate("Terms of Use"); ?></a>
                    <?php echo cl_translate("And"); ?> <a
                        href="<?php echo cl_link('privacy_policy'); ?>"><?php echo cl_translate("Privacy policy"); ?></a>
                </label>
            </div>
        </div>
    </div>

    <?php if ($cl["pn"] == "guest" && $cl["auth_type"] == "signup") : ?>
    <?php if ($cl["config"]["google_recaptcha"] == "on") : ?>
    <div class="form-group">
        <div class="d-flex justify-content-center">
            <div class="g-recaptcha" data-sitekey="<?php echo ($cl["config"]["google_recap_key1"]); ?>"></div>
        </div>
        <div v-if="grecaptcha_error" class="invalid-main-feedback text-center">
            <?php echo cl_translate("Please check reCAPTCHA to proceed with registration."); ?>
        </div>
    </div>
    <?php endif; ?>
    <?php endif; ?>

    <div class="form-group">

        <button type="submit" class="btn btn-custom main-inline lg btn-block">
            <?php echo cl_translate("Sign up"); ?>
        </button>

    </div>
    <div class="form-group no-mb">
        <div class="form-cta-link">
            <span>
                <?php echo cl_translate("Already have an account?"); ?>
            </span>
            <a href="<?php echo cl_link('guest'); ?>">
                <?php echo cl_translate("Login"); ?>
            </a>
        </div>
    </div>
    <input type="hidden" class="d-none" value="<?php echo fetch_or_get($cl['csrf_token'], 'none'); ?>" name="hash">
</form> -->
<div class="animated bounceInDown">
    <div class="container">
        <span class="error animated tada" id="msg"></span>
        <form name="form1" class="box" action="native_api/auth/signup" method="POST">
            <div class="form">
                <div class="header">
                    <h4>
                        Admin
                        <span>Dashboard</span>
                    </h4>
                    <h5>Sign up to your account.</h5>
                </div>
                <div class="body">
                    <input type="text" name="uname" placeholder="Username" autocomplete="off" />
                    <!-- <i class="typcn typcn-eye" id="eye"></i> -->
                    <input type="email" name="email" placeholder="Email" id="email" autocomplete="off" />
                    <div class="password">
                        <input type="password" name="password" placeholder="Password" id="password"
                            autocomplete="off" />
                        <input type="password" name="conf_pass" placeholder="Confirm" id="conf_pass"
                            autocomplete="off" />
                    </div>
                    <input type="submit" value="Sign up" class="btn1" />
        </form>
        <a href="<?php echo cl_link('guest?auth=login'); ?>" class="dnthave">Already have an account? Log in </a>

    </div>
</div>
</div>
<!-- <div class="footer">
        <span>Made with <i class="fa fa-heart pulse"></i> <a href="https://www.google.de/maps/place/Augsburger+Puppenkiste/@48.360357,10.903245,17z/data=!3m1!4b1!4m2!3m1!1s0x479e98006610a511:0x73ac6b9f80c4048f"><a href="https://codepen.io/lordgamer2354">By Anees Khan</a></span>
        </div> -->
</div>
<div class="square_box box_three"></div>
<div class="square_box box_four"></div>