<?php if ($cl['li']['advertising']) : ?>
<?php echo cl_template('timeline/ad'); ?>
<?php else :
    global $community;
?>
<div class="Tweet-target target">


    <div class="Option-button flex center btn">
        <div class="circle"></div>
        <div class="circle"></div>
        <div class="circle"></div>
    </div>
    <div class="teewt-data flex  gap-1">
        <div class="user-image-content">
            <div class="user-image s-2 circle">
                <img src="<?php convert_into_base64($cl['li']['owner']['avatar']); ?>" alt="Avatar">
            </div>
        </div>
        <div class="teewt-content">
            <h4>


                @<?php echo ($cl['li']['owner']['username']); ?>
            </h4>
            <div class="posted_title">
                <div class="posted-by t-color-3">
                    posted by
                    <a href="<?php echo ("community" . "?community_id=" . $cl['li']['community_id']); ?>">
                        <?php if (not_empty($cl['li']['community_name'])) echo $cl['li']['community_name'];
                            else echo $community['name']; ?>
                    </a>
                    ●
                    <?php
                        $now = new DateTime();

                        $date = new DateTime($cl['li']['time']);
                        $currentTimeinSeconds = time();

                        // converts the time in seconds to current date 
                        $currentDate = date('Y-m-d H:i:s ', $currentTimeinSeconds);

                        // prints the current date
                        // echo ($currentTimeinSeconds . " ");
                        // var_dump($date);
                        // echo $now->format('Y-m-d H:i:s ');
                        //echo $date->diff($now)->format("%h Hours %i Minute %s Seconds");
                        $year =  $date->diff($now)->format("%y");
                        $day = $date->diff($now)->format("%d");
                        $hour = $date->diff($now)->format("%H");
                        $min = $date->diff($now)->format("%i");
                        $sec = $date->diff($now)->format("%s");
                        if ($year != "0") echo $year . "years ago";
                        elseif ($day != "0") echo $day . "days ago";
                        elseif ($hour != "0") echo $hour . "hours ago";
                        elseif ($min != "0") echo $min . "mins ago";
                        else echo $sec . "seconds ago";
                        // echo $date->diff($now)->format("%y years %d days %h hours %i minutes"); 
                        ?>
                </div>
                <div><img src="<?php convert_into_base64("themes/default/statics/img/frame_picture.png"); ?>"></div>

                <div><img src="<?php convert_into_base64("themes/default/statics/img/lock.png"); ?>"></div>


            </div>
            <p><?php echo $cl['li']['description']; ?></p>


            <?php if ($cl['li']['type'] == 'poll' && not_empty($cl['li']['poll'])) : ?>
            <div class="publication-poll__inner">
                <?php foreach ($cl['li']['poll']['options'] as $i => $poll_data) : ?>

                <input type="radio" name="poll" id="poll_<?php echo $i; ?>" hidden>
                <?php endforeach; ?>
                <?php foreach ($cl['li']['poll']['options'] as $i => $poll_data) : ?>

                <label for="poll_<?php echo $i; ?>" id="for_poll_<?php echo $i; ?>">
                    <div>
                        <span class="circle"></span>
                        <?php if ($i == 0) : ?>
                        <span>Question/Subject</span>
                        <?php else : ?>
                        <span>Answer-<?php echo $i; ?></span>
                        <?php endif; ?>
                    </div>
                    <div class="content">
                        <?php echo ($poll_data['option']); ?>
                    </div>
                </label>
                <?php endforeach; ?>
            </div>
            <?php endif; ?>
            <div class="teewt-reactions-content flex nd">
                <div class="main-reactions-content flex">
                    <div class="teewt-likes-count-content">
                        <img src="<?php convert_into_base64("themes/default/statics/img/thumbs_up.png"); ?>">
                        <span><?php echo count(json_decode($cl['li']['upvote_count'])); ?></span>

                        <img src="<?php convert_into_base64("themes/default/statics/img/thumbs_down.png"); ?>">

                        <span><?php echo count(json_decode($cl['li']['downvote_count'])); ?></span>
                    </div>
                    <div class="teewt-shared-count-content">
                        <img
                            src="<?php convert_into_base64("themes/default/statics/img/refresh_" . $cl['display_set']['background'] . ".png"); ?>">

                        <span> 124</span>
                    </div>
                </div>
                <div class="teewt-comments-count-content mintext t-color-3"><span>45 Comments</span>
                </div>
            </div>
        </div>
    </div>
    <div class="reaction-btns-content flex nd wrap">
        <div class="r-action-btns-content flex">
            <?php if (!in_array($me['id'], json_decode($cl['li']['upvote_count']))) { ?>
            <a href="native_api/edit_post/up_vote?post_id=<?php echo $cl['li']['id']; ?>">
                <div class="r-action-btn btn bg-3">
                    <img
                        src="<?php convert_into_base64("themes/default/statics/img/up-arrow_" . $cl['display_set']['background'] . ".png");   ?>">


                </div>

            </a>
            <?php } else { ?>
            <div class="r-action-btn desabled btn bg-3">
                <img
                    src="<?php convert_into_base64("themes/default/statics/img/up-arrow_" . $cl['display_set']['background'] . ".png");   ?>">


            </div>
            <?php } ?>
            <?php if (!in_array($me['id'], json_decode($cl['li']['downvote_count']))) { ?>

            <a href="native_api/edit_post/down_vote?post_id=<?php echo $cl['li']['id'] ?>">

                <div class="r-action-btn btn bg-3">
                    <img
                        src="<?php convert_into_base64("themes/default/statics/img/down-arrow_" . $cl['display_set']['background'] . ".png"); ?>">
                </div>
            </a>
            <?php } else { ?>
            <div class="r-action-btn desabled btn bg-3">
                <img
                    src="<?php convert_into_base64("themes/default/statics/img/down-arrow_" . $cl['display_set']['background'] . ".png"); ?>">


            </div>
            <?php } ?>
        </div>
        <input type="checkbox" id="award_<?php echo $cl['li']['id'] ?>" class="award">
        <div class="award_window">
            <div class="award_window_body">
                <div class="award_image">
                    <div
                        style="background-image: url('themes/default/statics/img/Awards/7c2f679102faa666537fd6e9dfca15.png');">
                    </div>
                    <div
                        style="background-image: url('themes/default/statics/img/Awards/2b1705f353f6aa39c3ce8af75c0d53.png');">
                    </div>
                    <div
                        style="background-image: url('themes/default/statics/img/Awards/39ea697e96ea785feb5d7404023d97.png');">
                    </div>
                    <div
                        style="background-image: url('themes/default/statics/img/Awards/71a424fcea3aa44956d5d48cda4b00.png');">
                    </div>
                    <div
                        style="background-image: url('themes/default/statics/img/Awards/60265dff45ceb1d57ad22c14830cd8.png');">
                    </div>
                    <div
                        style="background-image: url('themes/default/statics/img/Awards/d50d9a0be45f9ca79ae545c889cc4b.png');">
                    </div>
                    <div
                        style="background-image: url('themes/default/statics/img/Awards/f48bb9fdc5e6832a8bda29dfd943ae.png');">
                    </div>
                    <div style="background-image: url('themes/default/statics/img/Awards/Screenshot_13.png');">
                    </div>
                    <div style="background-image: url('themes/default/statics/img/Awards/Screenshot_23.png');">
                    </div>
                </div>
                <div>
                    YOU HAVE NOT PURCHASED ANY AWARD YET, GO TO AWARD STORE TO BUY PACKS OF AWARD
                    BY CLICKING
                    <a href="#"> HERE</a>
                </div>
            </div>
        </div>
        <div class="r-action-btns-content flex">
            <div class="r-action-btn btn bg-3">
                <label for="award_<?php echo $cl['li']['id'] ?>">
                    <img src="<?php convert_into_base64("themes/default/statics/img/award.png"); ?>">
                </label>
            </div>
        </div>
        <div class="large-btns-content flex wrap">
            <div class="btn large bg-3">
                <img
                    src="<?php convert_into_base64("themes/default/statics/img/refresh_" . $cl['display_set']['background'] . ".png"); ?>">

                Retweet
            </div>
            <a href="native_api/edit_post/bookmark?post_id=<?php echo $cl['li']['id'] ?>">

                <div class="btn large bg-3">
                    <img
                        src="<?php convert_into_base64("themes/default/statics/img/file_" . $cl['display_set']['background'] . ".png"); ?>">
                    Save
                </div>
            </a>
        </div>
        <div class="r-action-btns-content flex">
            <div class="r-action-btn btn bg-3">
                <img src="<?php convert_into_base64("themes/default/statics/img/link.png"); ?>">
            </div>
        </div>
    </div>
    <div class="Comments-section flex col gap-2">
        <div class="user-account-comment-bar-content flex nd center gap-2">
            <div class="user-image s-3 circle"></div>
            <div class="form-control">
                <input class="bg-3" type="text" placeholder="lorem">
            </div>
            <div class="coomnet-btn btn bg-primary">comment</div>
        </div>
        <div class="comments-cotent flex col gap-2">
            <div class="user-comment-content">
                <h3>gola <span class="comment-time-ago mintext t-color-3">● 4hours ago</span></h3>
                <p>
                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse, provident! Tenetur,
                    officiis corporis iusto eum nesciunt,
                    ducimus sed assumenda minus itaque natus
                    temporibus. Iure sed itaque perferendis reiciendis commodi veniam!
                </p>
                <div class="comment-action-btns-content flex nd gap-2">
                    <div class="r-actions-content flex nd">
                        <div class="r-action-btn">▲</div>
                        <div class="r-action-btn">▼</div>
                    </div>
                    <div class="other-content flex center gap-2"><span class="r-a-count">15</span>
                        <div class="reply-btn btn">reply</div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<?php endif; ?>