<div class="cp-app-container" data-app="users">
    <div class="current-page-name">
        <div class="lp">
            <h2>
                Users
            </h2>
            <ol class="breadcrumb">
                <li>
                    <a href="<?php echo cl_link('admin_panel'); ?>">
                        Control panel
                    </a>
                </li>
                <li class="active">
                    <a href="">
                        Users
                    </a>
                </li>
            </ol>
        </div>
    </div>

    <div class="d-block" id="vue-cpanel-users-app">
        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="card">
                    <div class="header">
                        <h2>
                            Filter data
                        </h2>
                    </div>
                    <div class="body p-b-0 responsive">
                        <form class="form filter-data-form">
                            <div class="filter-data-form-option">
                                <div class="dropdown">
                                    <button class="btn dropdown-toggle" type="button" data-toggle="dropdown">
                                        <span>
                                            Status
                                        </span>
                                        <span>{{sorting.status.title}}</span>
                                    </button>
                                    <div class="dropdown-menu">
                                        <a v-on:click="apply_status($event)" data-value="all" class="dropdown-item"
                                            href="">
                                            All
                                        </a>
                                        <a v-on:click="apply_status($event)" data-value="active" class="dropdown-item"
                                            href="">
                                            Active
                                        </a>
                                        <a v-on:click="apply_status($event)" data-value="blocked" class="dropdown-item"
                                            href="">
                                            Blocked
                                        </a>
                                    </div>
                                </div>
                            </div>
                            <div class="filter-data-form-option">
                                <div class="dropdown">
                                    <button class="btn dropdown-toggle" type="button" data-toggle="dropdown">
                                        <span>
                                            Type
                                        </span>
                                        <span>{{sorting.type.title}}</span>
                                    </button>
                                    <div class="dropdown-menu">
                                        <a v-on:click="apply_type($event)" data-value="all" class="dropdown-item"
                                            href="">
                                            All
                                        </a>
                                        <a v-on:click="apply_type($event)" data-value="admin" class="dropdown-item"
                                            href="">
                                            Admin
                                        </a>
                                        <a v-on:click="apply_type($event)" data-value="user" class="dropdown-item"
                                            href="">
                                            User
                                        </a>
                                    </div>
                                </div>
                            </div>
                            <div class="filter-data-form-option">
                                <div class="dropdown">
                                    <button class="btn dropdown-toggle" type="button" data-toggle="dropdown">
                                        <span>
                                            Username
                                        </span>
                                        <span>{{sorting.username.title}}</span>
                                    </button>
                                    <div class="dropdown-menu dropdown-menu-input">
                                        <table>
                                            <tr>
                                                <td class="label">
                                                    <span>
                                                        Username
                                                    </span>
                                                </td>
                                                <td class="input">
                                                    <input v-model="sorting.username.value" type="text"
                                                        placeholder="Search for users by name">
                                                </td>
                                            </tr>
                                            <tr>
                                                <td class="apply-filter" colspan="2">
                                                    <button v-on:click="apply_username" type="button">
                                                        Apply
                                                    </button>
                                                </td>
                                            </tr>
                                        </table>
                                    </div>
                                </div>
                            </div>
                            <div class="filter-data-form-option">
                                <div class="dropdown">
                                    <button class="btn dropdown-toggle" type="button" data-toggle="dropdown">
                                        <span>
                                            E-mail address
                                        </span>
                                        <span>{{sorting.email.title}}</span>
                                    </button>
                                    <div class="dropdown-menu dropdown-menu-input">
                                        <table>
                                            <tr>
                                                <td class="label">
                                                    <span>
                                                        User e-mail
                                                    </span>
                                                </td>
                                                <td class="input">
                                                    <input v-model="sorting.email.value" type="text"
                                                        placeholder="Search for users by email">
                                                </td>
                                            </tr>
                                            <tr>
                                                <td class="apply-filter" colspan="2">
                                                    <button v-on:click="apply_email" type="button">
                                                        Apply
                                                    </button>
                                                </td>
                                            </tr>
                                        </table>
                                    </div>
                                </div>
                            </div>
                            <div class="filter-data-form-option">
                                <div class="dropdown">
                                    <button class="btn dropdown-toggle" type="button" data-toggle="dropdown">
                                        <span>
                                            IP
                                        </span>
                                        <span>{{sorting.ip.title}}</span>
                                    </button>
                                    <div class="dropdown-menu dropdown-menu-input">
                                        <table>
                                            <tr>
                                                <td class="label">
                                                    <span>
                                                        IP
                                                    </span>
                                                </td>
                                                <td class="input">
                                                    <input v-model="sorting.ip.value" type="text"
                                                        placeholder="Search for users by IP">
                                                </td>
                                            </tr>
                                            <tr>
                                                <td class="apply-filter" colspan="2">
                                                    <button v-on:click="apply_ip" type="button">
                                                        Apply
                                                    </button>
                                                </td>
                                            </tr>
                                        </table>
                                    </div>
                                </div>
                            </div>
                            <div class="filter-data-form-option">
                                <div class="dropdown">
                                    <button class="btn dropdown-toggle" type="button" data-toggle="dropdown">
                                        <span>
                                            Country
                                        </span>
                                        <span>{{sorting.country.title}}</span>
                                    </button>
                                    <div class="dropdown-menu dropdown-menu-list">
                                        <a v-on:click="apply_country($event)" data-value="any" class="dropdown-item"
                                            href="">
                                            Any
                                        </a>
                                        <?php foreach ($cl['countries'] as $cid => $cname): ?>
                                        <a v-on:click="apply_country($event)" data-value="<?php echo($cid); ?>"
                                            class="dropdown-item" href="">
                                            <?php echo($cname); ?>
                                        </a>
                                        <?php endforeach; ?>
                                    </div>
                                </div>
                            </div>
                            <div class="filter-data-form-option">
                                <button v-on:click="reset_form" type="button" v-bind:disabled="allow2reset != true"
                                    class="reset-filter">
                                    Reset filter
                                </button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>

            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="card" data-an="info-content">
                    <div class="header">
                        <h2>
                            Manage site users - ({{total_users}})
                        </h2>
                    </div>
                    <div class="body">
                        <div class="regular-table">
                            <table class="table table-hover no-mb">
                                <thead>
                                    <tr>
                                        <th>ID</th>
                                        <th>
                                            Username
                                        </th>
                                        <th>
                                            E-mail address
                                        </th>
                                        <th>
                                            Country
                                        </th>
                                        <th>IP</th>
                                        <th>
                                            Type
                                        </th>
                                        <th>
                                            Verified
                                        </th>
                                        <th>
                                            Status
                                        </th>
                                        <th>
                                            Last seen
                                        </th>
                                        <th>
                                            Action
                                        </th>
                                    </tr>
                                </thead>
                                <tbody data-an="users-list">
                                    <?php if (not_empty($cl['site_users'])): ?>
                                    <?php foreach ($cl['site_users'] as $cl['li']): ?>
                                    <?php echo cl_template('cpanel/assets/users/includes/list_item'); ?>
                                    <?php endforeach; ?>
                                    <?php else: ?>
                                    <?php echo cl_template('cpanel/assets/users/includes/empty_table'); ?>
                                    <?php endif; ?>
                                </tbody>
                            </table>

                            <div class="table-pagination">
                                <a v-if="show_ctrls" v-bind:class="{'disabled': dis_prev_ctrl}"
                                    v-on:click="paginate('up')" href="" class="pagination-ctrls prev">
                                    <?php echo cl_ikon("chevron-left"); ?>
                                </a>

                                <a v-if="show_ctrls" v-bind:class="{'disabled': dis_next_ctrl}"
                                    v-on:click="paginate('down')" href="" class="pagination-ctrls next">
                                    <?php echo cl_ikon("chevron-right"); ?>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<?php //echo cl_template('cpanel/assets/users/scripts/app_master_script'); ?>