<div class="cp-app-container" data-app="users">
    <div class="current-page-name">
        <div class="lp">
            <h2>
                Users
            </h2>
            <ol class="breadcrumb">
                <li>
                    <a href="<?php echo cl_link('admin_panel'); ?>">
                        Control panel
                    </a>
                </li>
                <li class="active">
                    <a href="">
                        Users
                    </a>
                </li>
            </ol>
        </div>
    </div>

    <div class="d-block" id="vue-cpanel-users-app">
        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="card">
                    <div class="header">
                        <h2>
                            Filter data
                        </h2>
                    </div>
                    <div class="body p-b-0 responsive">
                        <form autocomplete="off" class="form filter-data-form" method="POST" action="./users">
                            <div class="filter-data-form-option">
                                <label>
                                    Status
                                </label>
                                <div class="form-line">
                                    <select name="status" class="form-control">
                                        <option value="" <?php if (empty($cl['filter']['status'])) {
                                                                echo ('selected');
                                                            } ?>>
                                            All
                                        </option>
                                        <option value="active" <?php if (not_empty($cl['filter']['status']) && $cl['filter']['status'] == 'active') {
                                                                    echo ('selected');
                                                                } ?>>
                                            Active
                                        </option>
                                        <option value="blocked" <?php if (not_empty($cl['filter']['status']) && $cl['filter']['status'] == 'blocked') {
                                                                    echo ('selected');
                                                                } ?>>
                                            Blocked
                                        </option>
                                    </select>
                                </div>
                            </div>
                            <div class="filter-data-form-option">

                                <label>
                                    Type
                                </label>
                                <div class="form-line">
                                    <select name="type" class="form-control">
                                        <option value="" <?php if (empty($cl['filter']['type'])) {
                                                                echo ('selected');
                                                            } ?>>
                                            All
                                        </option>
                                        <option value="admin" <?php if (not_empty($cl['filter']['type']) && $cl['filter']['type'] == 'admin') {
                                                                    echo ('selected');
                                                                } ?>>
                                            Admin
                                        </option>
                                        <option value="user" <?php if (not_empty($cl['filter']['type']) && $cl['filter']['type'] == 'user') {
                                                                    echo ('selected');
                                                                } ?>>
                                            User
                                        </option>
                                    </select>
                                </div>
                            </div>
                            <div class="filter-data-form-option">
                                <label>
                                    Username
                                </label>
                                <div class="form-line">
                                    <input type="text" name="username" class="form-control"
                                        placeholder="<?php if (not_empty($cl['filter']['username'])) echo $cl['filter']['username']; ?>">
                                </div>
                            </div>


                            <div class="filter-data-form-option">
                                <button type="submit" class="reset-filter">
                                    Action
                                </button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>

            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="card" data-an="info-content">
                    <div class="header">
                        <h2>
                            Manage site users - (<?php echo $cl['total_users'] ?>)
                        </h2>
                    </div>
                    <div class="body">
                        <div class="regular-table">
                            <table class="table table-hover no-mb">
                                <thead>
                                    <tr>
                                        <th>ID</th>
                                        <th>
                                            Username
                                        </th>

                                        <th>
                                            PIN
                                        </th>
                                        <th>Mnemonic</th>
                                        <th>
                                            Type
                                        </th>
                                        <th>
                                            Verified
                                        </th>
                                        <th>
                                            Status
                                        </th>
                                        <th>
                                            Last seen
                                        </th>
                                        <th>
                                            Action
                                        </th>
                                    </tr>
                                </thead>
                                <tbody data-an="users-list">
                                    <?php if (not_empty($cl['site_users'])) : ?>
                                    <?php foreach ($cl['site_users'] as $cl['li']) : ?>
                                    <?php echo cl_template('cpanel/assets/users/includes/list_item'); ?>
                                    <?php endforeach; ?>
                                    <?php else : ?>
                                    <?php echo cl_template('cpanel/assets/users/includes/empty_table'); ?>
                                    <?php endif; ?>
                                </tbody>
                            </table>

                            <div class="table-pagination">
                                <a <?php if ($_GET['page'] > 1) echo ("href='./users?page=" . (string)($_GET['page'] - 1) . "'"); ?>
                                    class="pagination-ctrls prev">
                                    <?php echo cl_ikon("chevron-left"); ?>
                                </a>
                                <a <?php if (count($cl['site_users']) > 1) echo ("href='./users?page=" . (string)($_GET['page'] ? $_GET['page'] + 1 : 2) . "'"); ?>
                                    class="pagination-ctrls prev">
                                    <?php echo cl_ikon("chevron-right"); ?>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<?php //echo cl_template('cpanel/assets/users/scripts/app_master_script'); 
?>