<div class="timeline-placeholder">
	<div class="icon">
		<div class="icon__bg">
			<?php echo cl_icon('shield'); ?>
		</div>
	</div>

	<div class="pl-message">
		<h4>
			<?php echo cl_translate("This profile is protected"); ?>
		</h4>
		<p>
			<?php echo cl_translate("Only approved followers can see the posts and content of this profile, click the (Follow) button to see their posts!"); ?>
		</p>	
	</div>
	<div class="c2action-single">
		<a href="<?php echo cl_link('/'); ?>">
			<button class="btn btn-custom main-outline lg">
				<?php echo cl_translate("Go to the homepage"); ?>
			</button>
		</a>
	</div>
</div>