<div class="acp-main-left-sidebar" data-app="left-sidebar">
    <div class="admin-info">
        <div class="user-info">
            <div class="avatar">
                <img src="<?php echo ($me['avatar']); ?>" alt="Avatar">
            </div>
            <div class="uname">
                <h5>
                    <?php echo ($me['name']); ?>
                </h5>
                <div>
                    administrator
                </div>
            </div>
            <div class="menu-ctrl">
                <button class="btn" onclick="SMC_CPanel.menu_toggle();">
                    <?php echo cl_ikon("close"); ?>
                </button>
            </div>
        </div>
    </div>
    <ul class="menu-list">
        <li class="menu-list-item">
            <a href="<?php echo cl_link('home'); ?>" class="menu-list-item-link">
                <span class="icon">
                    <?php echo cl_ikon("home"); ?>
                </span>
                <span class="text">
                    Homepage
                </span>
            </a>
        </li>
        <li class="menu-list-item <?php if ($cl["cp_section"] == 'dashboard') {
                                        echo ('active');
                                    } ?>">
            <a href="<?php echo cl_link('admin_panel/dashboard'); ?>" class="menu-list-item-link">
                <span class="icon">
                    <?php echo cl_ikon("chart"); ?>
                </span>
                <span class="text">
                    Dashboard
                </span>
            </a>
        </li>
        <li class="menu-list-item <?php if ($cl["cp_section"] == 'gen_settings') {
                                        echo ('active');
                                    } ?>">
            <a href="<?php echo cl_link('admin_panel/gen_settings'); ?>" class="menu-list-item-link">
                <span class="icon">
                    <?php echo cl_ikon("settings"); ?>
                </span>
                <span class="text">
                    Settings
                </span>
            </a>
        </li>
        <li class="menu-list-item <?php if ($cl["cp_section"] == 'toggle_features') {
                                        echo ('active');
                                    } ?>">
            <a href="<?php echo cl_link('admin_panel/toggle_features'); ?>" class="menu-list-item-link">
                <span class="icon">
                    <?php echo cl_ikon("control-centre"); ?>
                </span>
                <span class="text">
                    Toggle functions <span class="badge">New</span>
                </span>
            </a>
        </li>


        <li class="menu-list-item <?php if (in_array($cl["cp_section"], array('users', 'wallet_balance'))) {
                                        echo ('active');
                                    } ?>">
            <a href="<?php echo cl_link('admin_panel/users'); ?>" class="menu-list-item-link">
                <span class="icon">
                    <?php echo cl_ikon("people"); ?>
                </span>
                <span class="text">
                    Users
                </span>
            </a>
        </li>

        <li class="menu-list-item <?php if ($cl["cp_section"] == 'publications') {
                                        echo ('active');
                                    } ?>">
            <a href="<?php echo cl_link('admin_panel/publications'); ?>" class="menu-list-item-link">
                <span class="icon">
                    <?php echo cl_ikon("feed"); ?>
                </span>
                <span class="text">
                    Publications
                </span>
            </a>
        </li>

        <li class="menu-list-item <?php if ($cl["cp_section"] == 'display_settings') {
                                        echo ('active');
                                    } ?>">
            <a href="<?php echo cl_link('admin_panel/display_settings'); ?>" class="menu-list-item-link">
                <span class="icon">
                    <?php echo cl_ikon("colours"); ?>
                </span>
                <span class="text">
                    Display settings
                </span>
            </a>
        </li>
        <li class="menu-list-item <?php if (in_array($cl["cp_section"], array('account_verification'))) {
                                        echo ('active open');
                                    } ?>">
            <input type="checkbox" id="user_tickets" hidden <?php if (in_array($cl["cp_section"], array('account_verification'))) {
                                                                echo ('checked');
                                                            } ?>>
            <label for="user_tickets">
                <a data-toggle-menu="1" class="menu-list-item-link">
                    <span class="icon">
                        <?php echo cl_ikon("inbox-alt"); ?>
                    </span>
                    <span class="text">
                        User Tickets
                    </span>
                    <span class="chevron-down">
                        <?php echo cl_ikon("chevron-down"); ?>
                    </span>
                </a>
            </label>
            <div class="submenu-list">
                <a class="submenu-list-item <?php if ($cl["cp_section"] == 'account_verification') {
                                                echo ('active');
                                            } ?>" href="<?php echo cl_link('admin_panel/account_verification'); ?>">
                    Account verification
                </a>
            </div>
        </li>

        <li class="menu-list-item <?php if (in_array($cl["cp_section"], array('ads_settings', 'manage_ads'))) {
                                        echo ('active open');
                                    } ?>">
            <input type="checkbox" id="advertising" hidden <?php if (in_array($cl["cp_section"], array('ads_settings', 'manage_ads'))) {
                                                                echo ('checked');
                                                            } ?>>
            <label for="advertising">
                <a data-toggle-menu="1" class="menu-list-item-link">
                    <span class="icon">
                        <?php echo cl_ikon("horn"); ?>
                    </span>
                    <span class="text">
                        Advertising
                    </span>
                    <span class="chevron-down">
                        <?php echo cl_ikon("chevron-down"); ?>
                    </span>
                </a>
            </label>
            <div class="submenu-list">
                <a class="submenu-list-item <?php if ($cl["cp_section"] == 'ads_settings') {
                                                echo ('active');
                                            } ?>" href="<?php echo cl_link('admin_panel/ads_settings'); ?>">
                    Settings
                </a>
                <a class="submenu-list-item <?php if ($cl["cp_section"] == 'manage_ads') {
                                                echo ('active');
                                            } ?>" href="<?php echo cl_link('admin_panel/manage_ads'); ?>">
                    Manage ads
                </a>
            </div>
        </li>
        <li class="menu-list-item <?php if (in_array($cl["cp_section"], array('affiliate_settings', 'affiliate_payouts'))) {
                                        echo ('active open');
                                    } ?>">
            <input type="checkbox" id="affiliates" hidden <?php if (in_array($cl["cp_section"], array('affiliate_settings', 'affiliate_payouts'))) {
                                                                echo ('checked');
                                                            } ?>>
            <label for="affiliates">
                <a data-toggle-menu="1" class="menu-list-item-link">
                    <span class="icon">
                        <?php echo cl_ikon("support-alt"); ?>
                    </span>
                    <span class="text">
                        Affiliates
                    </span>
                    <span class="chevron-down">
                        <?php echo cl_ikon("chevron-down"); ?>
                    </span>
                </a>
            </label>
            <div class="submenu-list">
                <a class="submenu-list-item <?php if ($cl["cp_section"] == 'affiliate_settings') {
                                                echo ('active');
                                            } ?>" href="<?php echo cl_link('admin_panel/affiliate_settings'); ?>">
                    Settings
                </a>
                <a class="submenu-list-item <?php if ($cl["cp_section"] == 'affiliate_payouts') {
                                                echo ('active');
                                            } ?>" href="<?php echo cl_link('admin_panel/affiliate_payouts'); ?>">
                    Payouts
                </a>
            </div>
        </li>
        <li class="menu-list-item <?php if (in_array($cl["cp_section"], array('account_reports', 'post_reports'))) {
                                        echo ('active open');
                                    } ?>">
            <input type="checkbox" id="reports" hidden <?php if (in_array($cl["cp_section"], array('account_reports', 'post_reports'))) {
                                                            echo ('checked');
                                                        } ?>>
            <label for="reports">
                <a data-toggle-menu="1" class="menu-list-item-link">
                    <span class="icon">
                        <?php echo cl_ikon("danger"); ?>
                    </span>
                    <span class="text">
                        Reports
                    </span>
                    <span class="chevron-down">
                        <?php echo cl_ikon("chevron-down"); ?>
                    </span>
                </a>
            </label>
            <div class="submenu-list">
                <a class="submenu-list-item <?php if ($cl["cp_section"] == 'account_reports') {
                                                echo ('active');
                                            } ?>" href="<?php echo cl_link('admin_panel/account_reports'); ?>">
                    Account reports
                </a>
                <a class="submenu-list-item <?php if ($cl["cp_section"] == 'post_reports') {
                                                echo ('active');
                                            } ?>" href="<?php echo cl_link('admin_panel/post_reports'); ?>">
                    Publication reports
                </a>
            </div>
        </li>




        <li class="menu-list-item <?php if ($cl["cp_section"] == 'changelogs') {
                                        echo ('active');
                                    } ?>">
            <a href="<?php echo cl_link('admin_panel/changelogs'); ?>" class="menu-list-item-link">
                <span class="icon">
                    <?php echo cl_ikon("book"); ?>
                </span>
                <span class="text">
                    Changelogs
                </span>
            </a>
        </li>
        <li class="menu-list-item <?php if ($cl["cp_section"] == 'backups') {
                                        echo ('active');
                                    } ?>">
            <a href="<?php echo cl_link('admin_panel/backups'); ?>" class="menu-list-item-link">
                <span class="icon">
                    <?php echo cl_ikon("save"); ?>
                </span>
                <span class="text">
                    Backups
                </span>
            </a>
        </li>
        <li class="menu-list-item <?php if ($cl["cp_section"] == 'languages') {
                                        echo ('active');
                                    } ?>">
            <a href="<?php echo cl_link('admin_panel/languages'); ?>" class="menu-list-item-link">
                <span class="icon">
                    <?php echo cl_ikon("language"); ?>
                </span>
                <span class="text">
                    UI Languages <span class="badge">New</span>
                </span>
            </a>
        </li>

        <li class="menu-list-item <?php if ($cl["cp_section"] == 'sitemap') {
                                        echo ('active');
                                    } ?>">
            <a href="<?php echo cl_link('admin_panel/sitemap'); ?>" class="menu-list-item-link">
                <span class="icon">
                    <?php echo cl_ikon("map"); ?>
                </span>
                <span class="text">
                    Sitemap
                </span>
            </a>
        </li>
        <li class="menu-list-item <?php if ($cl["cp_section"] == 'app_links') {
                                        echo ('active');
                                    } ?>">
            <a href="<?php echo cl_link('admin_panel/app_links'); ?>" class="menu-list-item-link">
                <span class="icon">
                    <?php echo cl_ikon("iphone"); ?>
                </span>
                <span class="text">
                    Mobile App links
                </span>
            </a>
        </li>
        <li class="menu-list-item">
            <a href="https://www.colibri-sm.ru/docs/index.html" class="menu-list-item-link">
                <span class="icon">
                    <?php echo cl_ikon("help"); ?>
                </span>
                <span class="text">
                    Documentation
                </span>
            </a>
        </li>
    </ul>
    <div class="sb-footer">
        &copy; {%config name%} - <?php echo date('Y'); ?>. <b>(v<?php echo $cl["config"]["version"]; ?>)</b>
    </div>
</div>