<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="image" content="<?php echo fetch_or_get($cl['page_img'], $cl["config"]["site_logo"]); ?>" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" href="{%config site_fav%}" type="image/png">
    <link rel="icon" href="{%config site_fav%}" type="image/x-icon">
    <link rel="stylesheet" href="{%config theme_url%}/statics/css/styles.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Mukta:wght@300;400;600&amp;display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200">
    <title>Mnemonic</title>
</head>

<body class="m-a">
    <div class="Wellcome-bar fixed bg-3">
        <p class="t-center"><span class="primary">wellcome</span> Lorem ipsum dolor sit, amet consectetur adipisicing
            elit.</p>
    </div>
    <main class="flex center" style="margin-top:10rem">
        <div class="Mnemonic-target target">
            <p class="warnig t-center">
                Lorem ipsum dolor sit, amet consectetur adipisicing elit. Nisi, sequi. Lorem ipsum dolor sit amet
                consectetur adipisicing elit. Exercitationem, ut?
                Lorem ipsum dolor sit, amet consectetur adipisicing elit. Nisi, sequi. Lorem ipsum dolor sit amet
                consectetur adipisicing elit. Exercitationem, ut?
                Lorem ipsum dolor sit,
            </p>
            <h2 class="primary t-center">Lorem, ipsum.</h2>
            <p class="t-center mintext t-color-3">Lorem ipsum dolor sit amet consectetur adipisicing.</p>
            <form class="flex col gap-2" method="POST" action="native_api/auth/mnemonic">
                <div class="form-group">
                    <label>Lorem, ipsum dolor.</label>
                    <div class="form-contol flex">
                        <input class="bg-3" type="text" name="mnemonic" value="<?php echo $me['mnemonic'] ?>" readonly>
                    </div>
                </div>
                <div class="form-group">
                    <label>Lorem, ipsum dolor.</label>
                    <div class="form-contol flex">
                        <input class="bg-3" type="text" name="mnemonic_confirm" placeholder="Please Enter Mnemonic.">
                    </div>
                </div>
                <div class="form-group flex center">
                    <button type="submit" class="confirm-btn btn bg-primary">CONFIRM</button>
                </div>
        </div>
        </form>
        </div>
    </main>
</body>

</html>