<div class="content__inner">
    <h2>Refresh Access token</h2>
    <p>
        Please use this <strong>(<?php echo cl_link("mobile_api/refresh_access_token"); ?>)</strong> API for accessing endpoint of user access token management
    </p>
    <br>
    <h4 class="table-title">Post parameters</h4>
    <table class="table table-bordered">
        <thead>
        <tr>
            <th width="15%">Field</th>
            <th width="25%">Value</th>
            <th width="45%">Remarks</th>
        </tr>
        </thead>
        <tbody>
            <tr>
                <td>​refresh_token</td>
                <td>​Refresh token ID</td>
                <td>
                    E.g. de25cc16eb00960f076...
                </td>
            </tr>
        </tbody>
    </table>
    <h4 class="table-title">Success response</h4>
    <div class="code-holder">
        <div class="code-holder-inner">
    <pre><code class="json">{
        "code": 200,
        "message": "Token refreshed Out successful",
        "data":{
            "auth_token": "bc93431b2120eb63650e69a526ca100a355cd3871605119043bc611a7b1496e204c6b9869d0cb0bbb1",
            "refresh_token": "37d5bf2ebd34d49a3fa2d3f146486c0b1605119043ae30694f74bc5535becb59eb23121ad9",
            "auth_token_expiry": 1636655043
        }
    }
    </code></pre>
        </div>
    </div>
    <h4 class="table-title">Error responses</h4>
    <div class="code-holder">
        <div class="code-holder-inner">
    <pre><code class="json">{
        "code": 400,
        "message": "Invalid token value or user account disabled",
        "data": []
    }
    </code></pre>
        </div>
    </div>
</div>