<section class="main flex col nd gap-2">
    <!-- sidebar-widgets-->
    <div class="Sidebar-widgets target">
        <h2>Sidebar widgets</h2>
        <hr>
        <h2>Add Widget</h2>
        <hr>
        <div class="widgets-content flex">
            <input class="hidden" id="radio-1" type="radio" name="widget-select">
            <input class="hidden" id="radio-2" type="radio" name="widget-select">
            <input class="hidden" id="radio-3" type="radio" name="widget-select">
            <input class="hidden" id="radio-unselect" type="radio" name="widget-select">
            <div class="widget-labels-content flex col gap-1 nd">
                <label class="widget-label flex center bg-3 gap-1" for="radio-1">
                    <div>
                        <h4>Texarea</h4>
                        <p class="mintext t-color-3">Annoucements, quick links, etc.</p>
                    </div>
                </label>
                <label class="widget-label flex center bg-3 gap-1" for="radio-2">
                    <div>
                        <h4>Images</h4>
                        <p class="mintext t-color-3">Art display, more cat pics etc.</p>
                    </div>
                </label>
                <label class="widget-label flex center bg-3 gap-1" for="radio-3">
                    <div>
                        <h4>Community list</h4>
                        <p class="mintext t-color-3">Recommended, related communities etc.</p>
                    </div>
                </label>
            </div>
            <div class="config-1">
                <label class="back-btn btn circle wb hidden" for="radio-unselect"><i
                        class="material-symbols-outlined">arrow_back</i></label>
                <h3>config-1</h3>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore
                    et dolore magna aliqua.</p>
            </div>
            <div class="config-2">
                <label class="back-btn btn circle wb hidden" for="radio-unselect"><i
                        class="material-symbols-outlined">arrow_back</i></label>
                <h3>config-2</h3>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore
                    et dolore magna aliqua.</p>
            </div>
            <div class="config-3">
                <label class="back-btn btn circle wb hidden" for="radio-unselect"><i
                        class="material-symbols-outlined">arrow_back</i></label>
                <h3>config-3</h3>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore
                    et dolore magna aliqua.</p>
            </div>
        </div>
    </div>
</section>