<section class="main flex col nd gap-2">
    <!-- sidebar-widgets-->
    <div class="Sidebar-widgets target">
        <h2>Sidebar widgets</h2>
        <hr>
        <h2>Add Widget</h2>
        <hr>
        <div class="widgets-content flex">
            <input class="hidden" id="radio-1" type="radio" name="widget-select" checked>
            <input class="hidden" id="radio-2" type="radio" name="widget-select">
            <input class="hidden" id="radio-3" type="radio" name="widget-select">
            <input class="hidden" id="radio-unselect" type="radio" name="widget-select">
            <div class="widget-labels-content flex col gap-1 nd">
                <label class="widget-label flex center bg-3 gap-1" for="radio-1">
                    <div>
                        <h4>Texarea</h4>
                        <p class="mintext t-color-3">Annoucements, quick links, etc.</p>
                    </div>
                </label>
                <label class="widget-label flex center bg-3 gap-1" for="radio-2">
                    <div>
                        <h4>Images</h4>
                        <p class="mintext t-color-3">Art display, more cat pics etc.</p>
                    </div>
                </label>
                <label class="widget-label flex center bg-3 gap-1" for="radio-3">
                    <div>
                        <h4>Community list</h4>
                        <p class="mintext t-color-3">Recommended, related communities etc.</p>
                    </div>
                </label>
            </div>
            <div class="config-1">
                <label class="back-btn btn circle wb hidden" for="radio-unselect"><i
                        class="material-symbols-outlined">arrow_back</i></label>
                <h3>config-1</h3>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore
                    et dolore magna aliqua.</p>
            </div>
            <div class="config-2">
                <div class="Upload-image target">
                    <h2>Images</h2><a class="flex nd al-c gap-1" href="#"><i class="material-symbols-outlined">info</i>
                        Images</a>
                    <hr class="mt-1">
                    <p class="t-color-3">Lorem ipsum dolor sit amet consectetur adipisicing elit. Facere repellat nam
                        provident.</p>
                    <form class="flex col gap-1" name="upload-image-form">
                        <div class="form-group">
                            <label for="widgetTitle">Widget title</label>
                            <p class="mintext t-color-3">Lorem ipsum dolor sit amet consectetur, adipisicing elit.
                                Beatae animi, minus vel suscipit.</p>
                            <div class="form-control">
                                <input class="bg-3" id="widgetTitle" type="text" name="widgetTitle"
                                    placeholder="some title" value="My Image Stand">
                            </div>
                            <p class="mintext t-color-3">Lorem ipsum dolor sit amet consectetur.</p>
                        </div>
                        <div class="form-group drop-image-content">
                            <label for="imageFile">Image</label>
                            <p class="mintext t-color-3">Lorem ipsum dolor sit amet.</p>
                            <label class="dropImg btn flex center col nd bg-3" for="imageFile"><i
                                    class="material-symbols-outlined fill">backup</i></label>
                            <input class="hidden" id="imageFile" type="file" name="imageFile"
                                accept="image/png, image/jpeg">
                        </div>
                        <div class="btns-content flex col gap-1 mt-1">
                            <div class="btn round bg-primary">Save</div>
                            <div class="btn round wb">Cancel</div>
                        </div>
                    </form>
                    <div class="flex js-e nd mt-2">
                        <div class="delete-widget-btn btn primary">DELETE WIDGET</div>
                    </div>
                </div>
            </div>
            <div class="config-3">
                <div class="Community-list-widget-appearance target">
                    <h2>Community List Widget Appearance</h2><a class="flex nd al-c gap-1" href="#"><i
                            class="material-symbols-outlined">info</i> Community list widget appearance</a>
                    <hr class="mt-1">
                    <form class="flex col gap-1 mt-1" name="community-list-widget-appearance-from">
                        <div class="from-section">
                            <div class="from-group">
                                <label for="widgetTitle">Widget title</label>
                                <div class="form-control">
                                    <input class="bg-3" id="widgetTitle" type="text" name="widgetTitle"
                                        placeholder="some title">
                                </div>
                                <p class="mintext t-color-3">Lorem ipsum dolor sit amet.</p>
                            </div>
                        </div>
                        <div class="from-section">
                            <p class="t-color-3">Lorem ipsum dolor sit.</p>
                            <hr class="mt-1 mb-1">
                            <div class="annoucements-content flex nd js-sb al-c gap-1">
                                <p>annoucements</p><i class="material-symbols-outlined fill btn delete-btn">delete</i>
                            </div>
                        </div>
                        <div class="from-section">
                            <h3>Add New Community</h3>
                            <div class="form-select mt-1">
                                <select class="bg-3" id="communityChice" name="communityChice">
                                    <option value="Choose a community">Choose a community</option>
                                </select>
                            </div>
                            <div class="reorder btn mt-1">REORDER COMMINITIES</div>
                        </div>
                        <div class="btns-content flex col gap-1">
                            <div class="btn round bg-primary">Save</div>
                            <div class="btn round wb">Cancel</div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>