<div class="msg_container">
    <div class="chat_body row">
        <div class="left-sidebar">
            <div class="title flex">
                <div class="text">
                    Chat
                </div>


            </div>
            <div class="inbox_list">


                <?php global $user_list;
                if (not_empty($cl['conversations']))
                    foreach ($cl['conversations'] as $key => $conversation) : ?>
                <?php if (not_empty($_GET['community_id'])) : ?>
                <a
                    href="mod_mail?community_id=<?php echo $_GET['community_id'] ?>&conversation_id=<?php echo $conversation['id'] ?>">
                    <?php else : ?>
                    <a href="mod_mail?conversation_id=<?php echo $conversation['id'] ?>">
                        <?php endif; ?>
                        <div class="inbox_item flex row <?php if ($cl['conversation_id'] == $conversation['id']) {
                                                                echo "active";
                                                                global $client_avatar;
                                                                $client_avatar = $user_list[$key]['avatar'];
                                                            } ?>">
                            <div class="avatar user-image circle "> <img class=""
                                    src="<?php convert_into_base64($user_list[$key]['avatar']); ?>"></div>
                            <div class="content ">
                                <div class="name"><?php echo $user_list[$key]['username'] ?></div>
                                <div class="text"><?php echo $user_list[$key]['message']; ?></div>
                            </div>
                        </div>
                    </a>

                    <?php endforeach; ?>


            </div>
        </div>
        <div class="message ">
            <div class="title flex row">
                <div class="text">Title</div>
                <div class="icon">
                    <div>
                        <img src="<?php convert_into_base64("themes/default/statics/img/settings.png"); ?>">
                    </div>
                    <div>
                        <img src="<?php convert_into_base64("themes/default/statics/img/resize (1).png"); ?>">
                    </div>
                    <div>
                        <img src="<?php convert_into_base64("themes/default/statics/img/down.png"); ?>">
                    </div>
                    <div>
                        <img src="<?php convert_into_base64("themes/default/statics/img/close.png"); ?>">
                    </div>

                </div>
            </div>
            <div class="message_body row">
                <?php
                if (not_empty($_GET['community_id'])) :
                    $date = "";
                    foreach ($cl['messages'] as $key => $message) : ?>
                <?php if ($message['owner'] == 0) : ?>
                <div class="sender">
                    <div class="text">
                        <?php echo $message['message']; ?>
                        <div class="time"><?php echo date('H:i A', strtotime($message['created_at'])); ?>
                        </div>

                    </div>
                    <div class="avatar"><img src="<?php convert_into_base64($cl['community_icon']); ?>"></div>

                </div>
                <?php else : ?>
                <div class="receiver">
                    <div class="avatar"><img src="<?php convert_into_base64($client_avatar); ?>"></div>
                    <div class="text">
                        <?php echo $message['message']; ?>
                        <div class="time"><?php echo date('H:i A', strtotime($message['created_at'])); ?>
                        </div>

                    </div>
                </div>
                <?php endif; ?>

                <?php if (count($cl['messages']) == ($key + 1)) : ?>
                <div class="date"><?php output_date($message['created_at']); ?></div>
                <?php elseif (date('M, d, Y', strtotime($cl['messages'][$key]['created_at'])) != date('M, d, Y', strtotime($cl['messages'][$key + 1]['created_at']))) : ?>
                <div class="date"><?php output_date($message['created_at']); ?></div>
                <?php endif; ?>
                <?php endforeach; ?>
                <?php else : ?>
                <?php
                    $date = "";
                    foreach ($cl['messages'] as $key => $message) : ?>
                <?php if ($message['owner'] == $me['id']) : ?>
                <div class="sender">
                    <div class="text">
                        <?php echo $message['message']; ?>
                        <div class="time"><?php echo date('H:i A', strtotime($message['created_at'])); ?>
                        </div>

                    </div>
                    <div class="avatar"><img src="<?php convert_into_base64($me['avatar']); ?>"></div>

                </div>
                <?php else : ?>
                <div class="receiver">
                    <div class="avatar"><img src="<?php convert_into_base64($client_avatar); ?>"></div>
                    <div class="text">
                        <?php echo $message['message']; ?>
                        <div class="time"><?php echo date('H:i A', strtotime($message['created_at'])); ?>
                        </div>

                    </div>
                </div>
                <?php endif; ?>

                <?php if (count($cl['messages']) == ($key + 1)) : ?>
                <div class="date"><?php output_date($message['created_at']); ?></div>
                <?php elseif (date('M, d, Y', strtotime($cl['messages'][$key]['created_at'])) != date('M, d, Y', strtotime($cl['messages'][$key + 1]['created_at']))) : ?>
                <div class="date"><?php output_date($message['created_at']); ?></div>
                <?php endif; ?>
                <?php endforeach; ?>

                <?php endif; ?>

            </div>
            <form method="POST" action="native_api/inbox/send_mod_mail">
                <div class="footer row flex">
                    <div class="camera">
                        <img src="<?php convert_into_base64("themes/default/statics/img/camera.png"); ?>">
                    </div>
                    <div class="input_body flex">
                        <div class="type_content">
                            <textarea placeholder="Message" name="message"></textarea>
                        </div>
                        <div class="gif">
                            <img src="<?php convert_into_base64("themes/default/statics/img/gif.png"); ?>">
                        </div>
                        <div class="emoji">
                            <img src="<?php convert_into_base64("themes/default/statics/img/happy.png"); ?>">
                        </div>
                    </div>
                    <div class="send">
                        <button type="submit" class="submit">
                            <img src="<?php convert_into_base64("themes/default/statics/img/send.png"); ?>">
                        </button>
                    </div>
                </div>
                <?php if (not_empty($cl['conversation_id'])) : ?>
                <input type="hidden" name="conversation_id" value="<?php echo $cl['conversation_id'] ?>">
                <?php endif; ?>
                <?php if (not_empty($_GET['community_id'])) : ?>
                <input type="hidden" name="owner" value="true">
                <?php endif; ?>
            </form>

        </div>
    </div>
</div>