<div class="timeline-placeholder">
	<div class="icon">
		<div class="icon__bg">
			<?php echo cl_icon('sentiment_neutral'); ?>
		</div>
	</div>
	<div class="pl-message">
		<h4>
			<?php echo cl_translate("No posts yet!"); ?>
		</h4>
		<p>
			<?php echo cl_translate("It looks like there are no posts on your feed yet. All your posts and publications of people you follow will be displayed here."); ?>
		</p>
	</div>
	<div class="c2action-single">
		<button class="btn btn-custom main-outline lg" data-toggle="modal" data-target="#add_new_post">
			<?php echo cl_translate("Create my first post"); ?>
		</button>
	</div>
</div>