<div class="content__inner">
    <h2>Delete post media</h2>
    <p>
        Please use this <strong>(<?php echo cl_link("mobile_api/delete_post_media"); ?>)</strong> API endpoint for deleteing post multimedia files
    </p>
    <br>
    <h4 class="table-title">Post parameters</h4>
    <table class="table table-bordered">
        <thead>
        <tr>
            <th width="15%">Field</th>
            <th width="25%">Value</th>
            <th width="45%">Remarks</th>
        </tr>
        </thead>
        <tbody>
            <tr>
                <td>session_id</td>
                <td>​Access token ID</td>
                <td>
                    E.g. de25cc16eb00960f076...
                </td>
            </tr>
            <tr>
                <td>type</td>
                <td>​Media file type (Image/Video)</td>
                <td>
                    E.g. image
                </td>
            </tr>
            <tr>
                <td>media_id</td>
                <td>​Media file ID</td>
                <td>
                    E.g. 45
                </td>
            </tr>
        </tbody>
    </table>
    <h4 class="table-title">Success response</h4>
    <div class="code-holder">
        <div class="code-holder-inner">
    <pre><code class="json">{
        "code": 200,
        "data": [],
        "message": "Media deleted successfully"
    }
    </code></pre>
        </div>
    </div>
    <h4 class="table-title">Error responses</h4>
    <div class="code-holder">
        <div class="code-holder-inner">
    <pre><code class="json">{
        "code": 401,
        "data": [],
        "message": "Unauthorized Access"
    }

    {
    	"code": 400,
    	"message": "Media file type is missing or invalid",
    	"data": []
    }

    {
        "code": 500,
        "message": "An error occurred while processing your request. Please try again later.",
        "data": []
    }
    </code></pre>
        </div>
    </div>
</div>