<div class="content__inner">
	<h2>How it works?</h2>
	<p>
	    In order to create a post or reply to it using api, you need to know how it works in the backend.
	</p>
	<p>
		The post and the answer to it are absolutely the same thing, except that the answer is attributed to some post. As for his media structure and behavior, it is the same as a regular post.
	</p>
	<p>
		Just sending texts and media files at one time to create a post will not work, since it is created step by step.
	</p>
	<h3>Description of how the system works when creating a media post, that is (Image / Video) post. (Not gif)</h3>
	<ul>
		<li>
			1. First you upload media files (Video/Images)
		</li>
		<li>
			2. Then just publish the post or answer using the endpoints described below
		</li>
	</ul>
	<h3>Description of how the system works when creating a (GIF/Text) post</h3>
	<ul>
		<li>
			1. By creating a simple text post or a GIF image, we can send all with one request as shown below.
		</li>
	</ul>
</div>