<div class="content__inner">
    <h2>Change post privacy</h2>
    <p>
        Please use this <strong>(<?php echo cl_link("mobile_api/change_post_privacy"); ?>)</strong> API endpoint for changing post privacy
    </p>
    <p>
        You will need this endpoint if you want to change the privacy of the post, that is, the option <b>"Who can reply"</b>
    </p>
    <p>
        However, keep in mind that this option is only available for Posts that do not have a parent chain. That is, the post should be the original post and not the answer.
    </p>
    <br>
    <h4 class="table-title">Post parameters</h4>
    <table class="table table-bordered">
        <thead>
        <tr>
            <th width="15%">Field</th>
            <th width="25%">Value</th>
            <th width="45%">Remarks</th>
        </tr>
        </thead>
        <tbody>
            <tr>
                <td>session_id</td>
                <td>Access token ID</td>
                <td>
                    E.g. de25cc16eb00960f076...
                </td>
            </tr>
            <tr>
                <td>post_id</td>
                <td>Publication int ID</td>
                <td>
                    E.g. 11
                </td>
            </tr>
            <tr>
                <td>privacy</td>
                <td>Publication privacy settings (Ignored for replies to posts)</td>
                <td>
                    One of those values <code>(everyone, followers, mentioned)</code>
                </td>
            </tr>
        </tbody>
    </table>
    <h4 class="table-title">Success response</h4>
    <div class="code-holder">
        <div class="code-holder-inner">
    <pre><code class="json">{
        "code": 200,
        "message": "Post privacy changed successfully",
        "data": []
    }
    </code></pre>
        </div>
    </div>
    <h4 class="table-title">Error responses</h4>
    <div class="code-holder">
        <div class="code-holder-inner">
    <pre><code class="json">{
        "code": 401,
        "data": [],
        "message": "Unauthorized Access"
    }

    {
        "code": 400,
        "message": "Post ID is missing or invalid. Please check your details",
        "data": []
    }
    </code></pre>
        </div>
    </div>
</div>