<div class="content__inner">
    <h2>Upload post media</h2>
    <p>
        Please use this <strong>(<?php echo cl_link("mobile_api/upload_post_media"); ?>)</strong> API endpoint for uploading post multimedia files
    </p>
    <br>
    <h4 class="table-title">Post parameters</h4>
    <table class="table table-bordered">
        <thead>
        <tr>
            <th width="15%">Field</th>
            <th width="25%">Value</th>
            <th width="45%">Remarks</th>
        </tr>
        </thead>
        <tbody>
            <tr>
                <td>session_id</td>
                <td>​Access token ID</td>
                <td>
                    E.g. de25cc16eb00960f076...
                </td>
            </tr>
            <tr>
                <td>type</td>
                <td>​Media file type (image/video)</td>
                <td>
                    E.g. image
                </td>
            </tr>
            <tr>
                <td>file</td>
                <td>​Media file (Image/Video)</td>
                <td>
                    E.g. some-selfy-picture.jpeg
                </td>
            </tr>
        </tbody>
    </table>
    <h4 class="table-title">Success response (Image uplaod)</h4>
    <div class="code-holder">
        <div class="code-holder-inner">
    <pre><code class="json">{
    	"message": "Media file uploaded successfully",
    	"code": 200,
    	"data": {
    		"media_id": 4,
    		"url": "An absolute URL of new uploded media file",
    		"type": "Image/Video"
    	}
    }
    </code></pre>
        </div>
    </div>
    <h4 class="table-title">Success response (Video uplaod)</h4>
    <div class="code-holder">
        <div class="code-holder-inner">
    <pre><code class="json">{
    	"message": "Media file uploaded successfully",
    	"code": 200,
    	"data": {
        	"media_id": 18,
        	"type": "Video",
        	"source": "An absolute URL of new uploded video file",
        	"poster": "An absolute URL of auto generated video thumbnail file"
        }
    }
    </code></pre>
        </div>
    </div>
    <h4 class="table-title">Error responses</h4>
    <div class="code-holder">
        <div class="code-holder-inner">
    <pre><code class="json">{
        "code": 401,
        "data": [],
        "message": "Unauthorized Access"
    }

    {
    	"code": 500,
    	"message": "Media file is missing or invalid",
    	"data": []
    }


    {
    	"code": 400,
    	"message": "Media file type is missing or invalid",
    	"data": []
    }

    {
    	"code": 400,
    	"message": "You cannot attach more than 10 images to a post",
    	"data": []
    }

    {
    	"code": 500,
    	"message": "An error occurred while processing your request. Please try again later.",
    	"data": []
    }
    </code></pre>
        </div>
    </div>
</div>