<div class="content__inner">
    <h2>Clear Chat/Delete</h2>
    <p>
        Please use this <strong>(<?php echo cl_link("mobile_api/clear_chat"); ?>) API for accessing the endpoint of clearing & deleting chat history</strong> 
    </p>
    <br>
    <h4 class="table-title">Post parameters</h4>
    <table class="table table-bordered">
        <thead>
        <tr>
            <th width="15%">Field</th>
            <th width="25%">Value</th>
            <th width="45%">Remarks</th>
        </tr>
        </thead>
        <tbody>
            <tr>
                <td>session_id</td>
                <td>​Access token ID</td>
                <td>
                    E.g. de25cc16eb00960f076...
                </td>
            </tr>
            <tr>
                <td>user_id</td>
                <td>​User ID of the interlocutor</td>
                <td>
                    E.g. 4567
                </td>
            </tr>
            <tr>
                <td>delete_chat</td>
                <td>​Delete chat after clearing</td>
                <td>
                    E.g. One of these options (1/0)
                </td>
            </tr>
        </tbody>
    </table>
    <h4 class="table-title">Success response</h4>
    <div class="code-holder">
        <div class="code-holder-inner">
    <pre><code class="json">{
        "code": 200,
        "message": "Chat deleted successfully",
        "data": []
    }
    </code></pre>
        </div>
    </div>
    <h4 class="table-title">Error responses</h4>
    <div class="code-holder">
        <div class="code-holder-inner">
    <pre><code class="json">{
        "code": 401,
        "data": [],
        "message": "Unauthorized Access"
    }

    {
        "code": 400,
        "message": "Interlocutor ID is missing or invalid",
        "data": []
    }
    </code></pre>
        </div>
    </div>
</div>