<div class="content__inner">
    <h2>Delete Message</h2>
    <p>
        Please use this <strong>(<?php echo cl_link("mobile_api/delete_message"); ?>) API for accessing the endpoint of deleting a chat message</strong> 
    </p>
    <br>
    <h4 class="table-title">Post parameters</h4>
    <table class="table table-bordered">
        <thead>
        <tr>
            <th width="15%">Field</th>
            <th width="25%">Value</th>
            <th width="45%">Remarks</th>
        </tr>
        </thead>
        <tbody>
            <tr>
                <td>session_id</td>
                <td>​Access token ID</td>
                <td>
                    E.g. de25cc16eb00960f076...
                </td>
            </tr>
            <tr>
                <td>message_id</td>
                <td>​Deleted message int ID</td>
                <td>
                    E.g. `34`
                </td>
            </tr>
        </tbody>
    </table>
    <h4 class="table-title">Success response</h4>
    <div class="code-holder">
        <div class="code-holder-inner">
    <pre><code class="json">{
        "code": 200,
        "message": "Message deleted successfully",
        "data": []
    }
    </code></pre>
        </div>
    </div>
    <h4 class="table-title">Error responses</h4>
    <div class="code-holder">
        <div class="code-holder-inner">
    <pre><code class="json">{
        "code": 401,
        "data": [],
        "message": "Unauthorized Access"
    }

    {
        "code": 400,
        "message": "Message ID is missing or invalid",
        "data": []
    }

    {
        "code": 400,
        "message": "A message with this ID was not found. Please check your details!",
        "data": []
    }
    </code></pre>
        </div>
    </div>
</div>