<div class="content__inner">
    <h2>Search Messages</h2>
    <p>
        Please use this <strong>(<?php echo cl_link("mobile_api/search_messages"); ?>) API for accessing the message search endpoint</strong> 
    </p>
    <br>
    <h4 class="table-title">Get parameters</h4>
    <table class="table table-bordered">
        <thead>
        <tr>
            <th width="15%">Field</th>
            <th width="25%">Value</th>
            <th width="45%">Remarks</th>
        </tr>
        </thead>
        <tbody>
            <tr>
                <td>session_id</td>
                <td>​Access token ID</td>
                <td>
                    E.g. de25cc16eb00960f076...
                </td>
            </tr>
            <tr>
                <td>user_id</td>
                <td>​User ID of the interlocutor</td>
                <td>
                    E.g. 4567
                </td>
            </tr>
            <tr>
                <td>query</td>
                <td>Search keyword</td>
                <td>
                    E.g. `Hello`
                </td>
            </tr>
            <tr>
                <td>page_size</td>
                <td>Search result rows limit</td>
                <td>
                    Default is (50) rows
                </td>
            </tr>
            <tr>
                <td>offset_up</td>
                <td>First message offset ID</td>
                <td>
                    This is only needed when loading previous messages.
                </td>
            </tr>
            <tr>
                <td>offset_down</td>
                <td>Last message offset ID</td>
                <td>
                    This is only needed when loading next messages.
                </td>
            </tr>
        </tbody>
    </table>
    <h4 class="table-title">Success response</h4>
    <div class="code-holder">
        <div class="code-holder-inner">
    <pre><code class="json">{
        "code": 200,
        "total": 1,
        "data":[
            {
                "id": 8,
                "sent_by": 10,
                "sent_to": 5,
                "owner": true,
                "message": "Hello!",
                "media_file": "",
                "media_type": "none",
                "seen": "0",
                "deleted_fs1": "N",
                "deleted_fs2": "N",
                "time": "23 Mar, 2021 11:03",
                "side": "right",
                "media_raw": ""
            }
        ]
    }
    </code></pre>
        </div>
    </div>
    <h4 class="table-title">Error responses</h4>
    <div class="code-holder">
        <div class="code-holder-inner">
    <pre><code class="json">{
        "code": 401,
        "data": [],
        "message": "Unauthorized Access"
    }

    {
        "code": 400,
        "message": "Interlocutor ID is missing or invalid",
        "data": []
    }

    {
        "code": 204,
        "data": [],
        "message": "No data found"
    }
    </code></pre>
        </div>
    </div>
</div>