<tr>
    <td colspan="10">
        <div class="empty-table">
            <span class="icon">
                <?php echo cl_ikon("people"); ?>
            </span>
            <h4>
                No users found
            </h4>
            <p>
                It looks like there are no users in your database yet. All users of your site will be displayed here.
            </p>
        </div>
    </td>
</tr>