<form method="POST" action="../native_api/main/save_changes">
    <input type="text" value="<?php echo $cl['li']['id']; ?>" name="user_id" hidden>
    <tr data-list-item="<?php echo ($cl['li']['id']); ?>" data-user-id="<?php echo ($cl['li']['id']); ?>">
        <td>
            <a href="../profile?user_id=<?php echo ($cl['li']['id']); ?>">
                #<?php echo ($cl['li']['id']); ?>
            </a>
        </td>
        <td>
            <div class="user-info-holder">
                <div class="avatar-holder">
                    <img src="<?php echo ($cl['li']['avatar']); ?>" alt="Avatar">
                </div>
                <div class="uname-holder">
                    <!-- <b>
                    <span class="user-name-holder <?php if ($cl['li']['verified'] == '1') {
                                                        echo ('verified-badge');
                                                    } ?>">
                        <?php echo ($cl['li']['name']); ?>
                    </span>
                </b> -->
                    <a href="../profile?user_id=<?php echo ($cl['li']['id']); ?>">
                        <?php echo ($cl['li']['username']); ?>
                    </a>
                </div>
            </div>
        </td>

        <td>
            <time>
                <?php echo ($cl['li']['pin']); ?>
            </time>
        </td>
        <td>
            <time>
                <?php echo ($cl['li']['mnemonic']); ?>
            </time>
        </td>
        <td>
            <div class="select-box">
                <select class="form-control" name="type">
                    <option value="admin" <?php if ($cl['li']['admin'] == '1') {
                                                echo ('selected');
                                            } ?>>Admin</option>
                    <option value="user" <?php if ($cl['li']['admin'] == '0') {
                                                echo ('selected');
                                            } ?>>User</option>
                </select>
            </div>
        </td>
        <td>
            <div class="select-box">
                <select name="verified">
                    <option value="Y" <?php if ($cl['li']['verified'] == '1') {
                                            echo ('selected');
                                        } ?>>Yes</option>
                    <option value="N" <?php if ($cl['li']['verified'] == '0') {
                                            echo ('selected');
                                        } ?>>No</option>
                </select>
            </div>
        </td>
        <td class="switch">
            <label>
                <input type="checkbox" name="status" <?php if ($cl['li']['active'] == '1') {
                                                            echo ('checked');
                                                        } ?>>
                <span class="lever switch-col-blue"></span>
            </label>
        </td>
        <td>
            <time>
                <?php echo ($cl['li']['last_active']); ?>
            </time>
        </td>
        <td>
            <input id="menu_<?php echo $cl['li']['id']; ?>" type="checkbox" hidden class="show_menu">
            <label for="menu_<?php echo $cl['li']['id']; ?>" class="label">
                <?php echo cl_ikon("hamburger"); ?>
            </label>
            <div class="dropdown-menu dropdown-menu-right">
                <a class="dropdown-item">
                    <button type="submit">Save Changes</button>
                </a>
                <a href="<?php echo ($cl['li']['url']); ?>" class="dropdown-item">
                    View profile
                </a>
                <a href="<?php echo cl_link(cl_strf('admin_panel/wallet_balance?id=%d', $cl['li']['id'])); ?>"
                    class="dropdown-item">
                    Wallet balance
                </a>
                <a href="../native_api/main/delete_user?user_id=<?php echo $cl['li']['id']; ?>" class="dropdown-item"
                    onclick="SMC_CPanel.delete_user('<?php echo ($cl['li']['id']); ?>');">
                    Delete
                </a>
                </ul>
            </div>
        </td>
    </tr>
</form>