<section class="main flex col nd gap-1">
    <div class="Post-bar target flex timeline gap-1">

        <div class="controls-content">
            <p class="content_title">COMMUNITY LISTS</p>
            <p class="subtitle">This is where all communities you joined and members you followed will show
                up.</p>
        </div>

    </div>
    <div class="main-content grid col nd gap-1">
        <?php if (not_empty($cl["tl_feed"])) : ?>
        <?php foreach ($cl["tl_feed"] as $cl["li"]) : ?>
        <?php echo cl_template('timeline/community'); ?>
        <?php endforeach; ?>
        <?php else : ?>
        <?php echo cl_template('home/includes/no_posts'); ?>
        <?php endif; ?>
    </div>
    <div class="pagination">
        <a href="explorer?page=1">&laquo;</a>
        <?php if ($cl['page'] - 2 > 0) : ?>
        <a href="explorer?page=<?php echo $cl['page'] - 2 ?>"><?php echo $cl['page'] - 2 ?></a>
        <?php endif; ?>

        <?php if ($cl['page'] - 1 > 0) : ?>
        <a href="explorer?page=<?php echo $cl['page'] - 1 ?>"><?php echo $cl['page'] - 1 ?></a>
        <?php endif; ?>
        <?php if ($cl['page'] > 0) : ?>
        <a href="explorer?page=<?php echo $cl['page'] ?>" class="active"><?php echo $cl['page'] ?></a>
        <?php endif; ?>
        <?php if ($cl['page'] < $cl['total_number'] / 10) : ?>
        <a href="explorer?page=<?php echo $cl['page'] + 1 ?>"><?php echo $cl['page'] + 1 ?></a>
        <?php endif; ?>
        <?php if ($cl['page'] + 1 < $cl['total_number'] / 10) : ?>
        <a href="explorer?page=<?php echo $cl['page'] + 2 ?>"><?php echo $cl['page'] + 2 ?></a>
        <?php endif; ?>
        <a href="explorer?page=<?php echo ceil($cl['total_number'] / 10) ?>">&raquo;</a>
    </div>

</section>