<tr>
    <td colspan="8">
        <div class="empty-table">
            <span class="icon">
                <?php echo cl_ikon("flag"); ?>
            </span>
            <h4>No reports found</h4>
            <p>
                It looks like there are no account reports in your database yet. All of your site's account reports will be displayed here.
            </p>
        </div>
    </td>
</tr>