<div class="timeline-container" data-app="homepage">

    <div class="user-profile">


        <div class="user-profile__body" style="display:flex;">
            <div class="user-profile__name" style="padding-left:60px; padding-top:10px;">
                <h4>

                    <span class="user-name-holder__name" style="font-weight:bold">
                        <?php echo ("c/Torify Moderators"); ?>
                    </span>

                </h4>
            </div>
        </div>


    </div>
    <div style="background-color:#dae0e6;padding-left:10px;padding-top:10px;padding-right:10px;padding-bottom:10px;">
        <div style="background-color:#edeff1;padding-left:3%; padding-bottom:5px;padding-top:5px;">
            <form action="" class="">
                <div class="input-group col-sm-4  ">
                    <input type="text" class="form-control form-control-sm" placeholder="Search Here">
                    <button type="submit" class="input-group-text btn-success"><i class="fa fa-search"
                            style="z-index: 10;"></i>
                    </button>
                </div>
            </form>
        </div>
        <div class="container"
            style="margin-bottom:30px;padding-left:30px; align-items: center;padding-right:30px;padding-top:5px;padding-bottom:5px;display:flex;background-color:white;">

            <img src="{%config theme_url%}/Homepage_files/1.png"
                style="height: 30px; width:30px;border: 3px solid white;z-index: 300;">
            <div>Ok-Manufacturer3200</div>
            <div style="padding-left:40px;padding-right:40%;">2 days ago</div>
            <p style="font-weight:bold;margin-bottom:0px;">
                (Main Moderator)
            </p>

        </div>
        <p style="margin-bottom:5px;">You can edit these moderators</p>
        <div class="container"
            style="padding-left:30px; align-items: center;padding-right:30px;padding-top:5px;padding-bottom:5px;display:flex;background-color:white;">

            <img src="{%config theme_url%}/Homepage_files/1.png"
                style="height: 30px; width:30px;border: 3px solid white;z-index: 300;">
            <div>Ok-Manufacturer3200</div>
            <div style="padding-left:40px;padding-right:40%;">2 days ago</div>
            <button type="button" class="btn" style="color:blue;">Remove</button>

        </div>
        <div style="height: 300px;"></div>
    </div>
    <?php if ($cl["config"]["swift_system_status"] == "on"): ?>
    <?php echo cl_template("home/modals/swift_lightbox"); ?>
    <?php echo cl_template("home/modals/swift_pubbox"); ?>
    <?php endif; ?>

    <?php echo cl_template("main/includes/inline_statics/app_statics"); ?>
    <?php //echo cl_template("home/scripts/app_master_script"); ?>
</div>