<div class="timeline-container">
    <div class="timeline-header" data-el="tl-header">
        <div class="timeline-header__topline">
            <div data-el="timeline-bs-notifs" class="timeline-bs-notifs"></div>
        </div>
        <div class="timeline-header__botline">
            <div class="lp">
                <div class="nav-link-holder">
                    <a href="<?php echo cl_link("settings/language"); ?>" data-spa="true">
                        <?php echo cl_translate("Display language"); ?>
                    </a>
                </div>
            </div>
            <div class="cp">
                <a href="<?php echo cl_link("home"); ?>">
                    <img src="{%config site_logo%}" alt="Logo">
                </a>
            </div>
            <div class="rp">
                <a href="<?php echo $_SERVER['HTTP_REFERER']; ?>">
                    <div class="nav-link-holder">
                        <span class="go-back">
                            <?php echo cl_icon('arrow_back'); ?>
                        </span>
                    </div>
                </a>
            </div>
        </div>
    </div>
    <div class="profile-settings">
        <div class="profile-settings__title">
            <h4><?php echo cl_translate("Set display language"); ?></h4>
        </div>
        <div class="profile-settings__content">
            <div class="settings-form">
                <form class="form" id="cl-language-settings-vue-app" method="POST"
                    action="<?php echo cl_link("native_api/settings/save_profile_lang"); ?>">
                    <div class="form-group">
                        <label>
                            <?php echo cl_translate("Select display language"); ?>
                        </label>
                        <div class="dropdown vue-dropdown-select">
                            <!-- <button class="btn btn-secondary dropdown-toggle" type="button" data-toggle="dropdown"
                                aria-haspopup="true" aria-expanded="false">
                                <span>
                                    <?php echo cl_translate("Nothing selected"); ?>
                                </span>

                            </button>
                            <div class="dropdown-menu ">
                                <a v-for="(v,k) in langs" v-on:click="dropdown_select(k)" class="dropdown-item" href="">
                                    asdf
                                </a>
                                <a v-for="(v,k) in langs" v-on:click="dropdown_select(k)" class="dropdown-item" href="">
                                    asdf
                                </a>
                                <a v-for="(v,k) in langs" v-on:click="dropdown_select(k)" class="dropdown-item" href="">
                                    asdf
                                </a>
                            </div> -->
                            <select name="language" id="lang">
                                <option value="english">English</option>
                                <option value="french">French</option>
                                <option value="german">German</option>
                                <option value="italian">Italian</option>
                                <option value="russian">Russian</option>
                                <option value="portuguese">Portuguese</option>
                                <option value="spanish">Spanish</option>
                                <option value="turkish">Turkish</option>
                                <option value="dutch">Dutch</option>
                                <option value="ukraine">Ukraine</option>
                                <option value="arabic">Arabic</option>
                            </select>
                        </div>
                    </div>

                    <div class="form-group" v-else>
                        <div class="form-info-label">
                            <?php echo cl_translate("Choose your preferred language for your account interface. This does not affect the language of the content that you see in your stream."); ?>
                        </div>
                    </div>
                    <input type="hidden" class="d-none" value="<?php echo fetch_or_get($cl['csrf_token'], 'none'); ?>"
                        name="hash">
                    <!-- <input v-model="language" type="hidden" class="d-none" name="language"> -->
                    <div class="form-group no-mb">
                        <button v-if="submitting != true" v-bind:disabled="$v.$invalid == true" type="submit"
                            class="btn btn-block btn-custom main-inline lg">
                            <?php echo cl_translate("Save changes"); ?>
                        </button>

                    </div>
                </form>
            </div>
        </div>
    </div>


</div>