<div class="timeline-container">
    <div class="timeline-header" data-el="tl-header">
        <div class="timeline-header__topline">
            <div data-el="timeline-bs-notifs" class="timeline-bs-notifs"></div>
        </div>
        <div class="timeline-header__botline">
            <div class="lp">
                <div class="nav-link-holder">
                    <a href="<?php echo cl_link("settings/name"); ?>" data-spa="true">
                        <?php echo cl_translate("Username"); ?>
                    </a>
                </div>
            </div>
            <div class="cp">
                <a href="<?php echo cl_link("home"); ?>">
                    <img src="{%config site_logo%}" alt="Logo">
                </a>
            </div>
            <div class="rp">
                <a href="<?php echo $_SERVER['HTTP_REFERER']; ?>">
                    <div class="nav-link-holder">
                        <span class="go-back">
                            <?php echo cl_icon('arrow_back'); ?>
                        </span>
                    </div>
                </a>
            </div>

        </div>
    </div>
    <div class="profile-settings">
        <div class="profile-settings__title">
            <h4><?php echo cl_translate("Change username"); ?></h4>
        </div>
        <div class="profile-settings__content">
            <div class="settings-form">
                <form class="form" id="cl-name-settings-vue-app" method="POST"
                    action="<?php echo cl_link("native_api/settings/save_profile_name"); ?>">
                    <div class="row">
                        <div class="col-sm-6">
                            <div class="form-group">
                                <label><?php echo cl_translate("First name"); ?></label>
                                <input v-model.trim="$v.fname.$model" name="fname" type="text" class="form-control"
                                    placeholder="<?php echo cl_translate("Enter first name"); ?>"
                                    value="<?php echo ($me["fname"]) ?>">

                            </div>
                        </div>
                        <div class="col-sm-6">
                            <div class="form-group">
                                <label><?php echo cl_translate("Last name"); ?></label>
                                <input v-model.trim="$v.lname.$model" name="lname" type="text" class="form-control"
                                    placeholder="<?php echo cl_translate("Enter last name"); ?>"
                                    value="<?php echo ($me["lname"]) ?>">

                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-12">
                            <div class="form-group">
                                <label><?php echo cl_translate("Username"); ?></label>
                                <input v-model.trim="$v.uname.$model" name="uname" type="text" class="form-control"
                                    placeholder="<?php echo cl_translate("Enter username"); ?>"
                                    value="<?php echo ($me["raw_uname"]) ?>">

                            </div>
                        </div>
                    </div>


                    <input type="hidden" class="d-none" value="<?php echo fetch_or_get($cl['csrf_token'], 'none'); ?>"
                        name="hash">
                    <div class="form-group no-mb">
                        <button v-if="submitting != true" v-bind:disabled="$v.$invalid == true" type="submit"
                            class="btn btn-custom main-inline btn-block lg">
                            <?php echo cl_translate("Save changes"); ?>
                        </button>

                    </div>
                </form>
            </div>
        </div>
    </div>


</div>