<div class="timeline-container">
    <div class="timeline-header" data-el="tl-header">
        <div class="timeline-header__topline">
            <div data-el="timeline-bs-notifs" class="timeline-bs-notifs"></div>
        </div>
        <div class="timeline-header__botline">
            <div class="lp">
                <div class="nav-link-holder">
                    <a href="<?php echo cl_link("settings/password"); ?>" data-spa="true">
                        <?php echo cl_translate("User password"); ?>
                    </a>
                </div>
            </div>
            <div class="cp">
                <a href="<?php echo cl_link("home"); ?>">
                    <img src="{%config site_logo%}" alt="Logo">
                </a>
            </div>
            <div class="rp">
                <a href="<?php echo $_SERVER['HTTP_REFERER']; ?>">
                    <div class="nav-link-holder">
                        <span class="go-back">
                            <?php echo cl_icon('arrow_back'); ?>
                        </span>
                    </div>
                </a>
            </div>
        </div>
    </div>
    <div class="profile-settings">
        <div class="profile-settings__title">
            <h4>
                <?php echo cl_translate("Change your password"); ?>
            </h4>
        </div>
        <div class="profile-settings__content">
            <div class="settings-form">
                <form class="form" id="cl-password-settings-vue-app" method="POST"
                    action="<?php echo cl_link("native_api/settings/save_profile_pass"); ?>">
                    <div class="form-group">
                        <label>
                            <?php echo cl_translate("Current password"); ?>
                        </label>
                        <div class="password-ctrl">
                            <input v-model.trim.lazy="$v.password1.$model" name="curr_password"
                                v-bind:type="password1_display" class="form-control" type="password"
                                placeholder="<?php echo cl_translate("Enter your current password"); ?>">

                        </div>

                    </div>
                    <div class="form-group">
                        <label>
                            <?php echo cl_translate("New password"); ?>
                        </label>
                        <div class="password-ctrl">
                            <input v-model.trim.lazy="$v.password2.$model" name="new_password"
                                v-bind:type="password2_display" class="form-control" type="password"
                                placeholder="<?php echo cl_translate("Enter new password"); ?>">

                        </div>

                    </div>
                    <div class="form-group">
                        <label>
                            <?php echo cl_translate("Confirm new password"); ?>
                        </label>
                        <div class="password-ctrl">
                            <input v-model.trim="$v.password3.$model" name="new_conf_pass"
                                v-bind:type="password3_display" class="form-control" type="password"
                                placeholder="<?php echo cl_translate("Confirm new password"); ?>">

                        </div>

                    </div>

                    <div class="form-group" v-else>
                        <div class="form-info-label">
                            <?php echo cl_translate("Before changing your current password, please follow these tips: Indicate the minimum length (6 characters). Use uppercase and lowercase letters. Use numbers and special characters (&%$)"); ?>
                        </div>
                    </div>
                    <input type="hidden" class="d-none" value="<?php echo fetch_or_get($cl['csrf_token'], 'none'); ?>"
                        name="hash">
                    <div class="form-group no-mb">
                        <button v-if="submitting != true" v-bind:disabled="$v.$invalid == true" type="submit"
                            class="btn btn-block btn-custom main-inline lg">
                            <?php echo cl_translate("Save changes"); ?>
                        </button>

                    </div>
                </form>
            </div>
        </div>
    </div>


</div>