<div class="timeline-container">
    <div class="timeline-header" data-el="tl-header">
        <div class="timeline-header__topline">
            <div data-el="timeline-bs-notifs" class="timeline-bs-notifs"></div>
        </div>
        <div class="timeline-header__botline">
            <div class="lp">
                <div class="nav-link-holder">
                    <a href="<?php echo cl_link("settings/verification"); ?>" data-spa="true">
                        <?php echo cl_translate("Verification"); ?>
                    </a>
                </div>
            </div>
            <div class="cp">
                <a href="<?php echo cl_link("home"); ?>">
                    <img src="{%config site_logo%}" alt="Logo">
                </a>
            </div>
            <div class="rp">
                <a href="<?php echo $_SERVER['HTTP_REFERER']; ?>">
                    <div class="nav-link-holder">
                        <span class="go-back">
                            <?php echo cl_icon('arrow_back'); ?>
                        </span>
                    </div>
                </a>
            </div>
        </div>
    </div>
    <div class="profile-settings">
        <div class="profile-settings__title">
            <h4>
                <?php echo cl_translate("Verify my account"); ?>
            </h4>
        </div>
        <div class="profile-settings__content">
            <div class="settings-form">
                <form class="form" id="cl-verif-settings-vue-app" v-on:submit="submit_form($event)" method="POST">
                    <div class="d-block" v-if="verification_status == '0'">
                        <div class="form-group">
                            <label>
                                <?php echo cl_translate("Full name"); ?>
                            </label>
                            <input v-model.trim="$v.full_name.$model" name="full_name" type="text" class="form-control"
                                placeholder="<?php echo cl_translate("Enter your full name"); ?>">

                        </div>
                        <div class="form-group">
                            <label>
                                <?php echo cl_translate("Message to reviewer"); ?>

                            </label>

                            <textarea v-model.trim="$v.text_message.$model" name="text_message" rows="2"
                                class="form-control"
                                placeholder="<?php echo cl_translate("Enter message to reviewer"); ?>"></textarea>

                        </div>
                        <div class="form-group">
                            <label>
                                <?php echo cl_translate("Video message"); ?>
                            </label>
                            <div class="form-dropzone" v-on:click="select_video">

                                <div class="form-dropzone__empty" v-else>
                                    <div class="form-dropzone__header">
                                        <div class="form-dropzone__icon">
                                            <?php echo cl_icon('slideshow'); ?>
                                        </div>
                                    </div>
                                    <div class="form-dropzone__body">
                                        <?php echo cl_translate("Please select a video appeal to the reviewer!"); ?>
                                    </div>
                                    <div class="form-dropzone__footer">
                                        <button type="button" class="btn btn-custom lg main-grey">
                                            <?php echo cl_translate("Click to select file"); ?>
                                        </button>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="form-group" v-else>
                            <div class="form-info-label">
                                <?php echo cl_translate("Please note that this material will not be published or shared with third parties. We request this information solely to verify the authenticity of your identity in order to further verify your account! To do this, we need you to record a video of no more than 1 minute in length, holding your Passport / ID in your right hand in a clear vision of your face and the data of your document, besides giving your full name and also the user nickname that you use on our website"); ?>
                            </div>
                        </div>
                        <input v-on:change="display_filename($event)" type="file" name="video" class="d-none"
                            accept="video/*" data-an="video-message-input">
                        <input type="hidden" class="d-none"
                            value="<?php echo fetch_or_get($cl['csrf_token'], 'none'); ?>" name="hash">
                        <div class="form-group no-mb">
                            <button v-if="submitting != true" v-bind:disabled="is_valid_form != true" type="submit"
                                class="btn btn-block btn-custom main-inline lg">
                                <?php echo cl_translate("Submit request"); ?>
                            </button>

                        </div>
                    </div>


                </form>
            </div>
        </div>
    </div>


</div>