<section class="main flex col nd gap-2">
    <!-- Theme-preferences-->
    <div class="Theme-preferences target">
        <h3>Menu</h3>
        <hr>
        <div class="link-color-content">
            <div class="flex">
                <p>Link Colors</p>
            </div>
            <div class="flex nd js-sb">
                <p class="t-color-3">Link</p>
                <input id="link-color" type="color" value="#EB0026">
            </div>
        </div>
        <div class="theme-color-content">
            <h3>Theme Colors</h3>
            <div class="flex nd js-sb">
                <p class="t-color-3">Base</p>
                <input id="link-color" type="color" value="#359D47">
            </div>
            <div class="flex nd js-sb">
                <p class="t-color-3">Highlight</p>
                <input id="link-color" type="color" value="#0179D2">
            </div>
        </div>
        <div class="btns-content flex col gap-1">
            <div class="btn round bg-primary">Save</div>
            <div class="btn round wb">Cancel</div>
        </div>
    </div>
</section>