<div class="cp-app-container" data-app="push-notifications">
    <div class="current-page-name">
        <div class="lp">
            <h2>
                Push notifications
            </h2>
            <ol class="breadcrumb">
                <li>
                    <a href="<?php echo cl_link('admin_panel'); ?>">
                        Control panel
                    </a>
                </li>
                <li class="active">
                    <a href="">
                        Push notifications
                    </a>
                </li> 
            </ol>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card">
                <div class="header">
                    <h2>
                        Manage push notifications API settings
                    </h2>
                </div>
                <div class="body">
                    <form class="form" data-an="form">
                    	<div class="form-group" data-an="firebase_api_key-input">
                            <label>
                                Firebase API key
                            </label>
                            <div class="form-line">
                                <input value="{%config firebase_api_key%}" name="firebase_api_key" type="text" class="form-control" placeholder="Firebase API key">
                            </div>
                        </div>
                        <div class="form-group" data-an="push_notifs-input">
                            <label>
                                Status
                            </label>
                            <div class="form-line">
                                <select name="push_notifs" class="form-control selectpicker">
                                    <option value="on" <?php if($cl['config']['push_notifs'] == 'on') { echo('selected'); } ?>>On</option>
                                    <option value="off" <?php if($cl['config']['push_notifs'] == 'off') { echo('selected'); } ?>>Off</option>
                                </select>
                            </div>
                        </div>
                       <div class="form-group no-mb">
                       		<button data-an="submit-ctrl" type="submit" class="btn bg-blue btn-block btn-lg waves-effect ttup">
                                Save changes
                            </button>
                       </div>
                        <input type="hidden" class="d-none" value="<?php echo fetch_or_get($cl['csrf_token'],'none'); ?>" name="hash">
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
<?php //echo cl_template('cpanel/assets/push_notifications/scripts/app_master_script'); ?>