<div class="content__inner">
    <h2>Delete swift media</h2>
    <p>
        Please use this <strong>(<?php echo cl_link("mobile_api/delete_swift_media"); ?>)</strong> API endpoint for deleteing swift media file
    </p>
    <p>
        In this case, you just need to send the above request to delete the swift media file, that is, a request without additional parameters, since the system itself will determine which file was last uploaded and delete it
    </p>
    <br>
    <h4 class="table-title">Post parameters</h4>
    <table class="table table-bordered">
        <thead>
        <tr>
            <th width="15%">Field</th>
            <th width="25%">Value</th>
            <th width="45%">Remarks</th>
        </tr>
        </thead>
        <tbody>
            <tr>
                <td>session_id</td>
                <td>​Access token ID</td>
                <td>
                    E.g. de25cc16eb00960f076...
                </td>
            </tr>
        </tbody>
    </table>
    <h4 class="table-title">Success response</h4>
    <div class="code-holder">
        <div class="code-holder-inner">
    <pre><code class="json">{
        "code": 200,
        "data": [],
        "message": "Media deleted successfully"
    }
    </code></pre>
        </div>
    </div>
    <h4 class="table-title">Error responses</h4>
    <div class="code-holder">
        <div class="code-holder-inner">
    <pre><code class="json">{
        "code": 401,
        "data": [],
        "message": "Unauthorized Access"
    }
    </code></pre>
        </div>
    </div>
</div>