<div class="content__inner">
	<h2>How it works?</h2>
	<p>
	    In order to create a swift using our api, you need to know how it works in the backend.
	</p>
	<p>
		Just sending texts and media files at one time to create a swift will not work, since it is created step by step.
	</p>
	<h3>Description of how the system works when creating a swift, that is (Image / Video) story</h3>
	<ul>
		<li>
			1. First you upload 1 media file Video or Image
		</li>
		<li>
			2. Then just publish the swift using the endpoints described below
		</li>
	</ul>
</div>
