<div class="cp-app-container" data-app="edit-user">
    <div class="current-page-name">
        <div class="lp">
            <h2>
                Users
            </h2>
            <ol class="breadcrumb">
                <li>
                    <a href="<?php echo cl_link('admin_panel'); ?>">
                        Control panel
                    </a>
                </li>
                <li class="active">
                    <a href="<?php echo cl_link('admin_panel/users'); ?>">
                        Users
                    </a>
                </li> 
                <li class="active">
                    <a href="">
                        Edit user data
                    </a>
                </li> 
            </ol>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card">
                <div class="header">
                    <h2>
                        User wallet balance
                    </h2>
                </div>
                <div class="body">
                    <form class="form" data-an="form">
                        <div class="form-group" data-an="wallet-input">
                            <label>
                                Wallet balance <a href="<?php echo cl_link($cl["user_data"]["username"]); ?>" target="_blank"><b>(@<?php echo($cl["user_data"]["username"]); ?>)</b></a>
                            </label>
                            <div class="form-line">
                                <input value="<?php echo($cl["user_data"]["wallet"]); ?>" name="wallet" type="text" class="form-control" placeholder="E.g. <?php echo cl_money($cl["config"]["wallet_min_amount"]); ?>">
                            </div>
                        </div>
                        <div class="form-group no-mb">
                        	<button data-an="submit-ctrl" type="submit" class="btn bg-blue btn-block btn-lg waves-effect ttup">
                                Save changes
                            </button>
                        </div>
                        <input type="hidden" class="d-none" value="<?php echo($cl["user_data"]["id"]); ?>" name="user_id">
                        <input type="hidden" class="d-none" value="<?php echo fetch_or_get($cl['csrf_token'],'none'); ?>" name="hash">
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
<?php //echo cl_template('cpanel/assets/wallet_balance/scripts/app_master_script'); ?>