<div class="modal fadeIn" data-app="post-likes-list" tabindex="-1" role="dialog" aria-hidden="true" data-keyboard="false" data-backdrop="static" data-onclose="remove">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
			<div class="modal-header">
                <div class="modal-header__inner">
                    <h5 class="modal-title">
                        <?php echo cl_translate("People who liked"); ?> (<?php echo($cl['likes_count']); ?>)
                    </h5>
                    <span class="dismiss-modal" data-dismiss="modal">
                        <?php echo cl_icon('close'); ?>
                    </span>
                </div>
            </div>
            <div class="modal-body no-padding">
                <div class="post-likes">
                    <?php if (not_empty($cl['post_likes'])): ?>
                        <div class="timeline-users-container">
                            <div class="timeline-user-ls" data-an="users-ls">
                                <?php foreach ($cl['post_likes'] as $cl['li']): ?>
                                    <?php echo cl_template('timeline/includes/like_li'); ?>
                                <?php endforeach; ?>
                            </div>
                        </div>
                        <?php if (count($cl['post_likes']) == 30): ?>
                            <div class="timeline-data-loader">
                                <button onclick="SMColibri.load_likes('<?php echo($cl['liked_post']); ?>', this);" class="btn btn-custom main-outline lg">
                                    <?php echo cl_translate("Show more"); ?>
                                </button>
                            </div>
                        <?php endif; ?>
                    <?php endif; ?>
                </div>                
            </div>
        </div>
    </div>
</div>