<nav class="tab-navigation">
	<div class="nav nav-tabs" id="nav-tab" role="tablist">
		<a class="nav-item nav-link active" id="nav-1-tab" data-toggle="tab" href="#nav-1" role="tab" aria-controls="nav-1" aria-selected="true">
			How it works - 1
		</a>
		<a class="nav-item nav-link" id="nav-2-tab" data-toggle="tab" href="#nav-2" role="tab" aria-controls="nav-2" aria-selected="true">
			Upload media - 2
		</a>
		<a class="nav-item nav-link" id="nav-3-tab" data-toggle="tab" href="#nav-3" role="tab" aria-controls="nav-3" aria-selected="true">
			Delete media - 3
		</a>
		<a class="nav-item nav-link" id="nav-4-tab" data-toggle="tab" href="#nav-4" role="tab" aria-controls="nav-4" aria-selected="true">
			Publish - 4
		</a>
		<a class="nav-item nav-link" id="nav-5-tab" data-toggle="tab" href="#nav-5" role="tab" aria-controls="nav-5" aria-selected="true">
			Delete - 5
		</a>
		<a class="nav-item nav-link" id="nav-6-tab" data-toggle="tab" href="#nav-6" role="tab" aria-controls="nav-6" aria-selected="true">
			Get swifts - 6
		</a>
		<a class="nav-item nav-link" id="nav-7-tab" data-toggle="tab" href="#nav-7" role="tab" aria-controls="nav-7" aria-selected="true">
			Register view - 7
		</a>
	</div>
</nav>
<div class="tab-content" id="nav-tabContent">
	<div class="tab-pane fade show active" id="nav-1" role="tabpanel" aria-labelledby="nav-1-tab">
		<?php require_once("endpoints/create_swift/includes/how-it-works.phtml"); ?>
	</div>
	<div class="tab-pane fade" id="nav-2" role="tabpanel" aria-labelledby="nav-2-tab">
		<?php require_once("endpoints/create_swift/includes/upload-media.phtml"); ?>
	</div>
	<div class="tab-pane fade" id="nav-3" role="tabpanel" aria-labelledby="nav-3-tab">
		<?php require_once("endpoints/create_swift/includes/delete-media.phtml"); ?>
	</div>
	<div class="tab-pane fade" id="nav-4" role="tabpanel" aria-labelledby="nav-4-tab">
		<?php require_once("endpoints/create_swift/includes/publish.phtml"); ?>
	</div>
	<div class="tab-pane fade" id="nav-5" role="tabpanel" aria-labelledby="nav-5-tab">
		<?php require_once("endpoints/create_swift/includes/delete-swift.phtml"); ?>
	</div>
	<div class="tab-pane fade" id="nav-6" role="tabpanel" aria-labelledby="nav-6-tab">
		<?php require_once("endpoints/create_swift/includes/get-swifts.phtml"); ?>
	</div>
	<div class="tab-pane fade" id="nav-7" role="tabpanel" aria-labelledby="nav-7-tab">
		<?php require_once("endpoints/create_swift/includes/register-view.phtml"); ?>
	</div>
</div>
