<input type="checkbox" id="modal" style="<?php if (empty($cl['popup_modal'])) echo "display: none" ?>">
<?php if (not_empty($cl['popup_modal'])) print_r($cl['popup_modal']); ?>
<tr data-list-item="<?php echo ($cl['li']['id']); ?>">
    <td>
        <?php echo ($cl['li']['id']); ?>
    </td>
    <td>
        <div class="user-info-holder">
            <div class="avatar-holder">
                <img src="<?php echo ($cl['li']['avatar']); ?>" alt="Avatar">
            </div>
            <div class="uname-holder">
                <b>
                    <?php echo ($cl['li']['full_name']); ?>
                </b>
                <a href="<?php echo ($cl['li']['url']); ?>">
                    <?php echo ($cl['li']['username']); ?>
                </a>
            </div>
        </div>
    </td>

    <td>
        <time>
            <?php echo ($cl['li']['last_active']); ?>
        </time>
    </td>
    <td>
        <?php if ($cl['li']['verified'] == '1') : ?>
        <span class="badge bg-blue">Verified</span>
        <?php else : ?>
        <span class="badge bg-orange">Pending</span>
        <?php endif; ?>
    </td>
    <td>
        <time>
            <?php echo ($cl['li']['time']); ?>
        </time>
    </td>
    <td>
        <input id="menu_<?php echo $cl['li']['id']; ?>" type="checkbox" hidden class="show_menu">
        <label for="menu_<?php echo $cl['li']['id']; ?>" class="label">
            <?php echo cl_ikon("hamburger"); ?>
        </label>
        <div class="dropdown-menu dropdown-menu-right">
            <a href="account_verification?id=<?php echo ($cl['li']['id']); ?>" class="dropdown-item">
                Show details
            </a>
            <a href="../native_api/cpanel/verify_user_account?id=<?php echo ($cl['li']['id']); ?>"
                class="dropdown-item">
                Verify account
            </a>
            <a href="../native_api/capnel/delete_verifreq_data?id=<?php echo ($cl['li']['id']); ?>"
                class="dropdown-item" onclick="SMC_CPanel.delete_user('<?php echo ($cl['li']['id']); ?>');">
                Delete
            </a>
            </ul>
        </div>

    </td>
</tr>