<nav class="tab-navigation">
	<div class="nav nav-tabs" id="nav-tab" role="tablist">
		<a class="nav-item nav-link active" id="nav-1-tab" data-toggle="tab" href="#nav-1" role="tab" aria-controls="nav-1" aria-selected="true">
			Send message - 1
		</a>
		<a class="nav-item nav-link" id="nav-2-tab" data-toggle="tab" href="#nav-2" role="tab" aria-controls="nav-2" aria-selected="true">
			Get chats - 2
		</a>
		<a class="nav-item nav-link" id="nav-3-tab" data-toggle="tab" href="#nav-3" role="tab" aria-controls="nav-3" aria-selected="true">
			Get messages - 3
		</a>
		<a class="nav-item nav-link" id="nav-4-tab" data-toggle="tab" href="#nav-4" role="tab" aria-controls="nav-4" aria-selected="true">
			Search messages - 4
		</a>
		<a class="nav-item nav-link" id="nav-5-tab" data-toggle="tab" href="#nav-5" role="tab" aria-controls="nav-5" aria-selected="true">
			Delete Message - 5
		</a>
		<a class="nav-item nav-link" id="nav-6-tab" data-toggle="tab" href="#nav-6" role="tab" aria-controls="nav-6" aria-selected="true">
			Clear chat - 6
		</a>
	</div>
</nav>
<div class="tab-content" id="nav-tabContent">
	<div class="tab-pane fade show active" id="nav-1" role="tabpanel" aria-labelledby="nav-1-tab">
		<?php require_once("endpoints/messaging/includes/send-message.phtml"); ?>
	</div>
	<div class="tab-pane fade" id="nav-2" role="tabpanel" aria-labelledby="nav-2-tab">
		<?php require_once("endpoints/messaging/includes/get-chats.phtml"); ?>
	</div>
	<div class="tab-pane fade" id="nav-3" role="tabpanel" aria-labelledby="nav-3-tab">
		<?php require_once("endpoints/messaging/includes/get-messages.phtml"); ?>
	</div>
	<div class="tab-pane fade" id="nav-4" role="tabpanel" aria-labelledby="nav-4-tab">
		<?php require_once("endpoints/messaging/includes/search-messages.phtml"); ?>
	</div>
	<div class="tab-pane fade" id="nav-5" role="tabpanel" aria-labelledby="nav-5-tab">
		<?php require_once("endpoints/messaging/includes/delete-message.phtml"); ?>
	</div>
	<div class="tab-pane fade" id="nav-6" role="tabpanel" aria-labelledby="nav-6-tab">
		<?php require_once("endpoints/messaging/includes/clear-chat.phtml"); ?>
	</div>
</div>
