<div class="cp-app-container" data-app="google-ads">
    <div class="current-page-name">
        <div class="lp">
            <h2>
                Google AdSense
            </h2>
            <ol class="breadcrumb">
                <li>
                    <a href="<?php echo cl_link('admin_panel'); ?>">
                        Control panel
                    </a>
                </li>
                <li class="active">
                    <a href="">
                        Google AdSense
                    </a>
                </li>
            </ol>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card">
                <div class="header">
                    <h2>
                        Manage (Google AdSense) system settings
                    </h2>
                </div>
                <div class="body">
                    <form class="form" data-an="form">
                        <div class="row">
                            <div class="col-sm-12">
                                <div class="form-group" data-an="google_ad_horiz-input">
                                    <label>
                                        Horizontal ads banner
                                    </label>
                                    <div class="form-line">
                                        <textarea name="google_ad_horiz" class="form-control" rows="2"
                                            placeholder="Enter a JS for horizontal ads banner"
                                            spellcheck="false">{%config google_ad_horiz%}</textarea>
                                    </div>
                                </div>
                            </div>
                            <div class="col-sm-12">
                                <div class="form-group" data-an="google_ad_vert-input">
                                    <label>
                                        Vertical ads banner
                                    </label>
                                    <div class="form-line">
                                        <textarea name="google_ad_vert" class="form-control" rows="2"
                                            placeholder="Enter a JS for vertical ads banner"
                                            spellcheck="false">{%config google_ad_vert%}</textarea>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-sm-12 no-mb">
                                <button data-an="submit-ctrl" type="submit" class="btn bg-blue btn-block btn-lg ttup">
                                    Save changes
                                </button>
                            </div>
                        </div>
                        <input type="hidden" class="d-none"
                            value="<?php echo fetch_or_get($cl['csrf_token'], 'none'); ?>" name="hash">
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
<?php //echo cl_template('cpanel/assets/google_ads/scripts/app_master_script'); ?>