<section class="main flex col nd gap-2">
    <div class="Post-flair target flex col gap-2 mintext">
        <table class="table" data-table="table-1">
            <tbody class="tbody flex col gap-1">
                <tr class="flex gap-1">
                    <th class="flex nd center fl-2">POST FLAIR PREVIEW</th>
                    <th class="flex nd center">Flair background color</th>
                    <th class="flex nd center">Flair text color</th>
                    <th class="flex nd center">Post background color</th>
                    <th class="flex nd center gap-1">FLAIR ID <i class="material-symbols-outlined"
                            data-icon="info">info</i></th>
                </tr>
                <tr class="flex gap-1">
                    <td class="fl-2">👀 SIMPLE POST 🕵️‍♀️</td>
                    <td class="flex nd center">
                        <input type="color" name="color" value="#EB0026">
                    </td>
                    <td class="flex nd center">
                        <input type="color" name="color" value="#EB0026">
                    </td>
                    <td class="flex nd center">
                        <input type="color" name="color" value="#303030">
                    </td>
                    <td class="flex nd min-w-max center gap-1"><a href="#">COPY ID</a><i
                            class="delete-btn material-symbols-outlined fill btn">delete</i></td>
                </tr>
                <tr class="flex gap-1">
                    <td class="fl-2">👀 SIMPLE POST 🕵️‍♀️</td>
                    <td class="flex nd center">
                        <input type="color" name="color" value="#EB0026">
                    </td>
                    <td class="flex nd center">
                        <input type="color" name="color" value="#EB0026">
                    </td>
                    <td class="flex nd center">
                        <input type="color" name="color" value="#303030">
                    </td>
                    <td class="flex nd min-w-max center gap-1"><a href="#">COPY ID</a><i
                            class="delete-btn material-symbols-outlined fill btn">delete</i></td>
                </tr>
                <tr class="flex gap-1">
                    <td class="fl-2">👀 SIMPLE POST 🕵️‍♀️</td>
                    <td class="flex nd center">
                        <input type="color" name="color" value="#EB0026">
                    </td>
                    <td class="flex nd center">
                        <input type="color" name="color" value="#EB0026">
                    </td>
                    <td class="flex nd center">
                        <input type="color" name="color" value="#303030">
                    </td>
                    <td class="flex nd min-w-max center gap-1"><a href="#">COPY ID</a><i
                            class="delete-btn material-symbols-outlined fill btn">delete</i></td>
                </tr>
                <tr class="flex gap-1">
                    <td class="fl-2">👀 SIMPLE POST 🕵️‍♀️</td>
                    <td class="flex nd center">
                        <input type="color" name="color" value="#EB0026">
                    </td>
                    <td class="flex nd center">
                        <input type="color" name="color" value="#EB0026">
                    </td>
                    <td class="flex nd center">
                        <input type="color" name="color" value="#303030">
                    </td>
                    <td class="flex nd min-w-max center gap-1"><a href="#">COPY ID</a><i
                            class="delete-btn material-symbols-outlined fill btn">delete</i></td>
                </tr>
                <tr class="flex gap-1">
                    <td class="fl-2">👀 SIMPLE POST 🕵️‍♀️</td>
                    <td class="flex nd center">
                        <input type="color" name="color" value="#EB0026">
                    </td>
                    <td class="flex nd center">
                        <input type="color" name="color" value="#EB0026">
                    </td>
                    <td class="flex nd center">
                        <input type="color" name="color" value="#303030">
                    </td>
                    <td class="flex nd min-w-max center gap-1"><a href="#">COPY ID</a><i
                            class="delete-btn material-symbols-outlined fill btn">delete</i></td>
                </tr>
            </tbody>
        </table>
        <div class="table-2-content">
            <p class="t-color-3">Flair apearence</p>
            <table class="table" data-table="table-2">
                <tbody class="tbody flex col gap-1">
                    <tr class="flex gap-1">
                        <th class="flex nd center fl-2">
                            <label for="flairText">Flair text</label>
                        </th>
                        <th class="flex nd center">Flair backgorond color</th>
                        <th class="flex nd center">Flair text color</th>
                        <th class="flex nd center">Post backgorond color</th>
                    </tr>
                    <tr class="flex gap-1">
                        <td class="fl-2">
                            <div class="form-control">
                                <input class="bg-3 mintext" id="flairText" type="text" name="flairText"
                                    value="👀 SIMPLE POST 🕵️‍♀️">
                            </div>
                        </td>
                        <td class="flex nd center">
                            <input type="color" name="color" value="#EB0026">
                        </td>
                        <td class="flex nd center">
                            <input type="color" name="color" value="#EB0026">
                        </td>
                        <td class="flex nd center">
                            <input type="color" name="color" value="#EB0026">
                        </td>
                    </tr>
                </tbody>
            </table>
            <p class="mintext t-color-3">Lorem ipsum dolor sit amet consectetur adipisicing.</p>
        </div>
        <div class="btns-content flex col gap-1">
            <div class="btn bg-primary round">Add Flairs</div>
            <div class="btn round wb">Cancel</div>
        </div>
    </div>
</section>