<div class="content__inner">
    <h2>Approve follow requests</h2>
    <p>
        Please use this <strong>(<?php echo cl_link("mobile_api/accept_follow"); ?>) API for accessing endpoint of user (follow requests) accepting</strong> 
    </p>
    <br>
    <h4 class="table-title">Post parameters</h4>
    <table class="table table-bordered">
        <thead>
        <tr>
            <th width="15%">Field</th>
            <th width="25%">Value</th>
            <th width="45%">Remarks</th>
        </tr>
        </thead>
        <tbody>
            <tr>
                <td>session_id</td>
                <td>​Access token ID (Optional)</td>
                <td>
                    E.g. de25cc16eb00960f076...
                </td>
            </tr>
            <tr>
                <td>req_id</td>
                <td>​Follow request int ID</td>
                <td>
                    E.g. 34
                </td>
            </tr>
        </tbody>
    </table>
    <h4 class="table-title">Success response</h4>
    <div class="code-holder">
        <div class="code-holder-inner">
    <pre><code class="json">{
        "message": "Subscription request successfully accepted",
        "code": 200,
        "data": {
            "total": 0
        }
    }
    </code></pre>
        </div>
    </div>
    <h4 class="table-title">Error responses</h4>
    <div class="code-holder">
        <div class="code-holder-inner">
    <pre><code class="json">{
        "code": 401,
        "data": [],
        "message": "Unauthorized Access"
    }

    {
        "code": 400,
        "message": "Follow request ID is missing or invalid",
        "data": []
    }
    </code></pre>
        </div>
    </div>
</div>
