<div class="content__inner">
    <h2>Change display language</h2>
    <p>
        Please use this <strong>(<?php echo cl_link("mobile_api/language"); ?>) API endpoint for changing display language</strong> 
    </p>
    <br>
    <h4 class="table-title">Post parameters</h4>
    <table class="table table-bordered">
        <thead>
        <tr>
            <th width="15%">Field</th>
            <th width="25%">Value</th>
            <th width="45%">Remarks</th>
        </tr>
        </thead>
        <tbody>
            <tr>
                <td>session_id</td>
                <td>​Access token ID</td>
                <td>
                    E.g. de25cc16eb00960f076...
                </td>
            </tr>
            <tr>
                <td>lang_name</td>
                <td>​Display language name</td>
                <td>
                    E.g. One of these options (english, french, german, italian, russian, portuguese, spanish, turkish, dutch, ukraine)
                </td>
            </tr>
        </tbody>
    </table>
    <h4 class="table-title">Success response</h4>
    <div class="code-holder">
        <div class="code-holder-inner">
    <pre><code class="json">{
    	"code": 200,
    	"message": "Language changed successfully",
    	"data": []
    }
    </code></pre>
        </div>
    </div>
    <h4 class="table-title">Error responses</h4>
    <div class="code-holder">
        <div class="code-holder-inner">
    <pre><code class="json">{
        "code": 401,
        "data": [],
        "message": "Unauthorized Access"
    }

    {
    	"code": 400,
    	"message": "Display language name is invalid or missing",
    	"data": []
    }
    </code></pre>
        </div>
    </div>
</div>