<div class="content__inner">
    <h2>Change password</h2>
    <p>
        Please use this <strong>(<?php echo cl_link("mobile_api/change_password"); ?>)</strong> API for accessing endpoint of user password management
    </p>
    <br>
    <h4 class="table-title">Post parameters</h4>
    <table class="table table-bordered">
        <thead>
        <tr>
            <th width="15%">Field</th>
            <th width="25%">Value</th>
            <th width="45%">Remarks</th>
        </tr>
        </thead>
        <tbody>
            <tr>
                <td>session_id</td>
                <td>​Access token ID</td>
                <td>
                    E.g. de25cc16eb00960f076...
                </td>
            </tr>
            <tr>
                <td>old_password</td>
                <td>User old password</td>
                <td>
                    E.g. 123456
                </td>
            </tr>
            <tr>
                <td>new_password</td>
                <td>User new password</td>
                <td>
                    E.g. secret123
                </td>
            </tr>
        </tbody>
    </table>
    <h4 class="table-title">Success response</h4>
    <div class="code-holder">
        <div class="code-holder-inner">
    <pre><code class="json">{
        "code": 200,
        "message": "Password changed",
        "data": []
    }
    </code></pre>
        </div>
    </div>
    <h4 class="table-title">Error responses</h4>
    <div class="code-holder">
        <div class="code-holder-inner">
    <pre><code class="json">{
        "code": 402,
        "message": "Incorrect old password value",
        "data": []
    }

    {
        "code": 402,
        "message": "Incorrect new password value",
        "data": []
    }
    </code></pre>
        </div>
    </div>
</div>