<?php
# @*************************************************************************@
# @ Software author: Mansur Altamirov (Mansur_TL)                           @
# @ Author_url 1: https://www.instagram.com/mansur_tl                       @
# @ Author_url 2: http://codecanyon.net/user/mansur_tl                      @
# @ Author E-mail: vayart.help@gmail.com                                    @
# @*************************************************************************@
# @ ColibriSM - The Ultimate Modern Social Media Sharing Platform           @
# @ Copyright (c) 2020 - 2021 ColibriSM. All rights reserved.               @
# @*************************************************************************@

$cl                 = array();
$applications       = array(
  "main"          => true,
  "home"          => true,
  "guest"         => true,
  "404"           => true,
  "auth"          => true,
  "logout"        => true,
  "settings"      => true,
  "profile"       => true,
  "connections"   => true,
  "suggested"     => true,
  "trending"      => true,
  "search"        => true,
  "chats"         => true,
  "conversation"  => true,
  "thread"        => true,
  "bookmarks"     => true,
  "stat_pages"    => true,
  "notifications" => true,
  "affiliates"    => true,
  "ads"           => true,
  "cpanel"        => true,
  "oauth"         => true,
  "err404"        => true,
  "confirm_reg"   => true,
  "confirm_email" => true,
  "wallet"        => true,
  "err500"        => true,
  "swift"         => true,
  "ad_item"       => true,
  "download_info" => true,
  "edit_post"     => true,
  "start_up"      => true,
  "spa_load"      => true,
  "create_post" => true,
);

$cl['profile_report_types'] = array(
  '1' => 'This user using this account for smap',
  '2' => 'This user pretended to be someone',
  '3' => 'This user posting inappropriate content',
  '4' => 'This is a fake account',
  '5' => 'This is a fraudulent account',
  '6' => 'Other',
);

$cl['post_report_types'] = array(
  '1' => 'This is spam',
  '2' => 'Misleading or fraudulent',
  '3' => 'Publication of private information',
  '4' => 'Threats of violence or physical harm',
  '5' => 'I am not interested in this post',
  '6' => 'Other'
);

$cl['site_currencies'] = array(
  'usd' => array(
    'name' => 'United states dollar',
    'symbol' => '$'
  ),
  'eur' => array(
    'name' => 'EU Euro',
    'symbol' => '€'
  ),
  'rub' => array(
    'name' => 'Russian ruble',
    'symbol' => '₽'
  ),
  'brl' => array(
    'name' => 'Brazilian real',
    'symbol' => 'R$'
  ),
  'gbp' => array(
    'name' => 'Pound sterling',
    'symbol' => '£'
  ),
  'tl' => array(
    'name' => 'Turkish lira',
    'symbol' => '₺'
  ),
  'inr' => array(
    'name' => 'Indian rupee',
    'symbol' => '₹'
  ),
  'jpy' => array(
    'name' => 'Japanese yen',
    'symbol' => '¥'
  ),
  'ghs' => array(
    'name' => 'Ghanaian cedi',
    'symbol' => 'GH₵'
  ),
  'ngn' => array(
    'name' => 'Nigerian naira',
    'symbol' => '₦'
  ),
  'zar' => array(
    'name' => 'South African rand',
    'symbol' => 'ZAR'
  )
);

$cl["ui_rand_colors"] = array(
  "#9857BC",
  "#1ABC9C",
  "#F1C40F",
  "#F39C12",
  "#2ECC71",
  "#C0392B",
  "#34495E",
  "#B49255",
  "#3498DB",
  "#EC87BF",
  "#873202",
  "#8E44AD",
  "#34495E",
  "#95A5A6",
  "#2980B9"
);

$cl["color_schemes"] = array(
  "default" => array(
    "name" => "Default",
    "color" => "#1DA1F2",
    "icon" => "whale"
  ),
  "yellow" => array(
    "name" => "Yellow",
    "color" => "#FDAD1F",
    "icon" => "lemon"
  ),
  "pink" => array(
    "name" => "Pink",
    "color" => "#E0245E",
    "icon" => "tomato"
  ),
  "purple" => array(
    "name" => "Purple",
    "color" => "#794BC4",
    "icon" => "grape"
  ),
  "orange" => array(
    "name" => "Orange",
    "color" => "#F45D22",
    "icon" => "orange"
  ),
  "green" => array(
    "name" => "Green",
    "color" => "#2FBF63",
    "icon" => "avocado"
  )
);

$cl["bg_colors"] = array(
  "default" => array(
    "name" => "Default",
    "color" => "#fff",
    "icon" => "white-mode"
  ),
  "dark" => array(
    "name" => "Dark",
    "color" => "#15202b",
    "icon" => "dim-mode"
  )
);

$cl["media_mime_types"] = array(
  'image/png',
  'image/jpeg',
  'image/gif',
  'image/webp',
  'video/mp4',
  'video/quicktime',
  'video/3gpp',
  'video/x-flv',
  'video/mpeg',
  'audio/wav',
  'audio/x-wav',
  'audio/mpeg',
  'video/ogg',
  'video/webm',
  'video/x-ms-wmv',
  'video/3gpp2',
);

$cl['countries'] = array(
  '1' => 'United States',
  '2' => 'Canada',
  '3' => 'Afghanistan',
  '4' => 'Albania',
  '5' => 'Algeria',
  '6' => 'American Samoa',
  '7' => 'Andorra',
  '8' => 'Angola',
  '9' => 'Anguilla',
  '10' => 'Antarctica',
  '11' => 'Antigua and/or Barbuda',
  '12' => 'Argentina',
  '13' => 'Armenia',
  '14' => 'Aruba',
  '15' => 'Australia',
  '16' => 'Austria',
  '17' => 'Azerbaijan',
  '18' => 'Bahamas',
  '19' => 'Bahrain',
  '20' => 'Bangladesh',
  '21' => 'Barbados',
  '22' => 'Belarus',
  '23' => 'Belgium',
  '24' => 'Belize',
  '25' => 'Benin',
  '26' => 'Bermuda',
  '27' => 'Bhutan',
  '28' => 'Bolivia',
  '29' => 'Bosnia and Herzegovina',
  '30' => 'Botswana',
  '31' => 'Bouvet Island',
  '32' => 'Brazil',
  '34' => 'Brunei Darussalam',
  '35' => 'Bulgaria',
  '36' => 'Burkina Faso',
  '37' => 'Burundi',
  '38' => 'Cambodia',
  '39' => 'Cameroon',
  '40' => 'Cape Verde',
  '41' => 'Cayman Islands',
  '42' => 'Central African Republic',
  '43' => 'Chad',
  '44' => 'Chile',
  '45' => 'China',
  '46' => 'Christmas Island',
  '47' => 'Cocos (Keeling) Islands',
  '48' => 'Colombia',
  '49' => 'Comoros',
  '50' => 'Congo',
  '51' => 'Cook Islands',
  '52' => 'Costa Rica',
  '53' => 'Croatia (Hrvatska)',
  '54' => 'Cuba',
  '55' => 'Cyprus',
  '56' => 'Czech Republic',
  '57' => 'Denmark',
  '58' => 'Djibouti',
  '59' => 'Dominica',
  '60' => 'Dominican Republic',
  '61' => 'East Timor',
  '62' => 'Ecuador',
  '63' => 'Egypt',
  '64' => 'El Salvador',
  '65' => 'Equatorial Guinea',
  '66' => 'Eritrea',
  '67' => 'Estonia',
  '68' => 'Ethiopia',
  '69' => 'Falkland Islands (Malvinas)',
  '70' => 'Faroe Islands',
  '71' => 'Fiji',
  '72' => 'Finland',
  '73' => 'France',
  '74' => 'France, Metropolitan',
  '75' => 'French Guiana',
  '76' => 'French Polynesia',
  '77' => 'French Southern Territories',
  '78' => 'Gabon',
  '79' => 'Gambia',
  '80' => 'Georgia',
  '81' => 'Germany',
  '82' => 'Ghana',
  '83' => 'Gibraltar',
  '84' => 'Greece',
  '85' => 'Greenland',
  '86' => 'Grenada',
  '87' => 'Guadeloupe',
  '88' => 'Guam',
  '89' => 'Guatemala',
  '90' => 'Guinea',
  '91' => 'Guinea-Bissau',
  '92' => 'Guyana',
  '93' => 'Haiti',
  '94' => 'Heard and Mc Donald Islands',
  '95' => 'Honduras',
  '96' => 'Hong Kong',
  '97' => 'Hungary',
  '98' => 'Iceland',
  '99' => 'India',
  '100' => 'Indonesia',
  '101' => 'Iran (Islamic Republic of)',
  '102' => 'Iraq',
  '103' => 'Ireland',
  '104' => 'Israel',
  '105' => 'Italy',
  '106' => 'Ivory Coast',
  '107' => 'Jamaica',
  '108' => 'Japan',
  '109' => 'Jordan',
  '110' => 'Kazakhstan',
  '111' => 'Kenya',
  '112' => 'Kiribati',
  '113' => 'Korea, Democratic People\'s Republic of',
  '114' => 'Korea, Republic of',
  '115' => 'Kosovo',
  '116' => 'Kuwait',
  '117' => 'Kyrgyzstan',
  '118' => 'Lao People\'s Democratic Republic',
  '119' => 'Latvia',
  '120' => 'Lebanon',
  '121' => 'Lesotho',
  '122' => 'Liberia',
  '123' => 'Libyan Arab Jamahiriya',
  '124' => 'Liechtenstein',
  '125' => 'Lithuania',
  '126' => 'Luxembourg',
  '127' => 'Macau',
  '128' => 'Macedonia',
  '129' => 'Madagascar',
  '130' => 'Malawi',
  '131' => 'Malaysia',
  '132' => 'Maldives',
  '133' => 'Mali',
  '134' => 'Malta',
  '135' => 'Marshall Islands',
  '136' => 'Martinique',
  '137' => 'Mauritania',
  '138' => 'Mauritius',
  '139' => 'Mayotte',
  '140' => 'Mexico',
  '141' => 'Micronesia, Federated States of',
  '142' => 'Moldova, Republic of',
  '143' => 'Monaco',
  '144' => 'Mongolia',
  '145' => 'Montenegro',
  '146' => 'Montserrat',
  '147' => 'Morocco',
  '148' => 'Mozambique',
  '149' => 'Myanmar',
  '150' => 'Namibia',
  '151' => 'Nauru',
  '152' => 'Nepal',
  '153' => 'Netherlands',
  '154' => 'Netherlands Antilles',
  '155' => 'New Caledonia',
  '156' => 'New Zealand',
  '157' => 'Nicaragua',
  '158' => 'Niger',
  '159' => 'Nigeria',
  '160' => 'Niue',
  '161' => 'Norfork Island',
  '162' => 'Northern Mariana Islands',
  '163' => 'Norway',
  '164' => 'Oman',
  '165' => 'Pakistan',
  '166' => 'Palau',
  '167' => 'Panama',
  '168' => 'Papua New Guinea',
  '169' => 'Paraguay',
  '170' => 'Peru',
  '171' => 'Philippines',
  '172' => 'Pitcairn',
  '173' => 'Poland',
  '174' => 'Portugal',
  '175' => 'Puerto Rico',
  '176' => 'Qatar',
  '177' => 'Reunion',
  '178' => 'Romania',
  '179' => 'Russian Federation',
  '180' => 'Rwanda',
  '181' => 'Saint Kitts and Nevis',
  '182' => 'Saint Lucia',
  '183' => 'Saint Vincent and the Grenadines',
  '184' => 'Samoa',
  '185' => 'San Marino',
  '186' => 'Sao Tome and Principe',
  '187' => 'Saudi Arabia',
  '188' => 'Senegal',
  '189' => 'Serbia',
  '190' => 'Seychelles',
  '191' => 'Sierra Leone',
  '192' => 'Singapore',
  '193' => 'Slovakia',
  '194' => 'Slovenia',
  '195' => 'Solomon Islands',
  '196' => 'Somalia',
  '197' => 'South Africa',
  '198' => 'South Georgia South Sandwich Islands',
  '199' => 'Spain',
  '200' => 'Sri Lanka',
  '201' => 'St. Helena',
  '202' => 'St. Pierre and Miquelon',
  '203' => 'Sudan',
  '204' => 'Suriname',
  '205' => 'Svalbarn and Jan Mayen Islands',
  '206' => 'Swaziland',
  '207' => 'Sweden',
  '208' => 'Switzerland',
  '209' => 'Syrian Arab Republic',
  '210' => 'Taiwan',
  '211' => 'Tajikistan',
  '212' => 'Tanzania, United Republic of',
  '213' => 'Thailand',
  '214' => 'Togo',
  '215' => 'Tokelau',
  '216' => 'Tonga',
  '217' => 'Trinidad and Tobago',
  '218' => 'Tunisia',
  '219' => 'Turkey',
  '220' => 'Turkmenistan',
  '221' => 'Turks and Caicos Islands',
  '222' => 'Tuvalu',
  '223' => 'Uganda',
  '224' => 'Ukraine',
  '225' => 'United Arab Emirates',
  '226' => 'United Kingdom',
  '227' => 'United States minor outlying islands',
  '228' => 'Uruguay',
  '229' => 'Uzbekistan',
  '230' => 'Vanuatu',
  '231' => 'Vatican City State',
  '232' => 'Venezuela',
  '233' => 'Vietnam',
  '238' => 'Yemen',
  '239' => 'Yugoslavia',
  '241' => 'Zambia',
  '242' => 'Zimbabwe'
);

$cl['country_codes'] = array(
  '1' => 'us',
  '2' => 'ca',
  '3' => 'af',
  '4' => 'al',
  '5' => 'dz',
  '6' => 'as',
  '7' => 'ad',
  '8' => 'ao',
  '9' => 'ai',
  '10' => 'aq',
  '11' => 'ag',
  '12' => 'ar',
  '13' => 'am',
  '14' => 'aw',
  '15' => 'au',
  '16' => 'at',
  '17' => 'az',
  '18' => 'bs',
  '19' => 'bh',
  '20' => 'bd',
  '21' => 'bb',
  '22' => 'by',
  '23' => 'be',
  '24' => 'bz',
  '25' => 'bj',
  '26' => 'bm',
  '27' => 'bt',
  '28' => 'bo',
  '29' => 'ba',
  '30' => 'bw',
  '31' => 'bv',
  '32' => 'br',
  '34' => 'bn',
  '35' => 'bg',
  '36' => 'bf',
  '37' => 'bi',
  '38' => 'kh',
  '39' => 'cm',
  '40' => 'cv',
  '41' => 'ky',
  '42' => 'cf',
  '43' => 'td',
  '44' => 'cl',
  '45' => 'cn',
  '46' => 'cx',
  '47' => 'cc',
  '48' => 'co',
  '49' => 'cm',
  '50' => 'cg',
  '51' => 'ck',
  '52' => 'cr',
  '53' => 'hr',
  '54' => 'cu',
  '55' => 'cy',
  '56' => 'cz',
  '57' => 'dk',
  '58' => 'dj',
  '59' => 'dm',
  '60' => 'do',
  '61' => 'tl',
  '62' => 'ec',
  '63' => 'eg',
  '64' => 'sv',
  '65' => 'gq',
  '66' => 'er',
  '67' => 'ee',
  '68' => 'et',
  '69' => 'fk',
  '70' => 'fo',
  '71' => 'fj',
  '72' => 'fi',
  '73' => 'fr',
  '74' => 'fr',
  '75' => 'gf',
  '76' => 'pf',
  '77' => 'tf',
  '78' => 'ga',
  '79' => 'gm',
  '80' => 'ge',
  '81' => 'de',
  '82' => 'gh',
  '83' => 'gi',
  '84' => 'gr',
  '85' => 'gl',
  '86' => 'gd',
  '87' => 'gp',
  '88' => 'gu',
  '89' => 'gt',
  '90' => 'gn',
  '91' => 'gw',
  '92' => 'gy',
  '93' => 'ht',
  '94' => 'hm',
  '95' => 'hn',
  '96' => 'hk',
  '97' => 'hu',
  '98' => 'is',
  '99' => 'in',
  '100' => 'id',
  '101' => 'ir',
  '102' => 'iq',
  '103' => 'ie',
  '104' => 'il',
  '105' => 'it',
  '106' => 'ci',
  '107' => 'jm',
  '108' => 'jp',
  '109' => 'jo',
  '110' => 'kz',
  '111' => 'ke',
  '112' => 'ki',
  '113' => 'kp',
  '114' => 'kr',
  '115' => 'al',
  '116' => 'kw',
  '117' => 'kg',
  '118' => 'la',
  '119' => 'lv',
  '120' => 'lb',
  '121' => 'ls',
  '122' => 'lr',
  '123' => 'ly',
  '124' => 'li',
  '125' => 'lt',
  '126' => 'lu',
  '127' => 'mo',
  '128' => 'mk',
  '129' => 'mg',
  '130' => 'mw',
  '131' => 'my',
  '132' => 'mv',
  '133' => 'ml',
  '134' => 'mt',
  '135' => 'mh',
  '136' => 'mq',
  '137' => 'mr',
  '138' => 'mu',
  '139' => 'yt',
  '140' => 'mx',
  '141' => 'fm',
  '142' => 'md',
  '143' => 'mk',
  '144' => 'mn',
  '145' => 'me',
  '146' => 'ms',
  '147' => 'ma',
  '148' => 'mz',
  '149' => 'mm',
  '150' => 'na',
  '151' => 'nr',
  '152' => 'np',
  '153' => 'nl',
  '154' => 'nl',
  '155' => 'nc',
  '156' => 'nz',
  '157' => 'ni',
  '158' => 'ne',
  '159' => 'ng',
  '160' => 'nu',
  '161' => 'nf',
  '162' => 'mp',
  '163' => 'no',
  '164' => 'om',
  '165' => 'pk',
  '166' => 'pw',
  '167' => 'pa',
  '168' => 'pg',
  '169' => 'py',
  '170' => 'cn',
  '171' => 'ph',
  '172' => 'pn',
  '173' => 'pl',
  '174' => 'pt',
  '175' => 'pr',
  '176' => 'qa',
  '177' => 're',
  '178' => 'ro',
  '179' => 'ru',
  '180' => 'rw',
  '181' => 'kn',
  '182' => 'lc',
  '183' => 'vc',
  '184' => 'ws',
  '185' => 'sm',
  '186' => 'st',
  '187' => 'sa',
  '188' => 'sn',
  '189' => 'rs',
  '190' => 'sc',
  '191' => 'sl',
  '192' => 'sg',
  '193' => 'sk',
  '194' => 'si',
  '195' => 'sb',
  '196' => 'so',
  '197' => 'za',
  '198' => 'gs',
  '199' => 'es',
  '200' => 'lk',
  '201' => 'sh',
  '202' => 'pm',
  '203' => 'sd',
  '204' => 'sr',
  '205' => 'sj',
  '206' => 'sz',
  '207' => 'se',
  '208' => 'ch',
  '209' => 'sy',
  '210' => 'tw',
  '211' => 'tj',
  '212' => 'tz',
  '213' => 'th',
  '214' => 'tg',
  '215' => 'tk',
  '216' => 'to',
  '217' => 'tt',
  '218' => 'tn',
  '219' => 'tr',
  '220' => 'tm',
  '221' => 'tc',
  '222' => 'tv',
  '223' => 'ug',
  '224' => 'ua',
  '225' => 'ae',
  '226' => 'gb',
  '227' => 'um',
  '228' => 'uy',
  '229' => 'uz',
  '230' => 'vu',
  '231' => 'va',
  '232' => 've',
  '233' => 'vn',
  '238' => 'ye',
  '239' => 'rs',
  '240' => 'zm',
  '242' => 'zw'
);

$cl['language_codes'] = array(
  'afrikaans' => array(
    'name' => 'Afrikaans',
    'code' => 'af',
  ),
  'albanian' => array(
    'name' => 'Albanian - shqip',
    'code' => 'sq',
  ),
  'amharic' => array(
    'name' => 'Amharic - አማርኛ',
    'code' => 'am',
  ),
  'aragonese' => array(
    'name' => 'Aragonese - aragonés',
    'code' => 'an',
  ),
  'armenian' => array(
    'name' => 'Armenian - հայերեն',
    'code' => 'hy',
  ),
  'asturian' => array(
    'name' => 'Asturian - asturianu',
    'code' => 'ast',
  ),
  'azerbaijani' => array(
    'name' => 'Azerbaijani - azərbaycan dili',
    'code' => 'az',
  ),
  'basque' => array(
    'name' => 'Basque - euskara',
    'code' => 'eu',
  ),
  'belarusian' => array(
    'name' => 'Belarusian - беларуская',
    'code' => 'be',
  ),
  'bengali' => array(
    'name' => 'Bengali - বাংলা',
    'code' => 'bn',
  ),
  'bosnian' => array(
    'name' => 'Bosnian - bosanski',
    'code' => 'bs',
  ),
  'breton' => array(
    'name' => 'Breton - brezhoneg',
    'code' => 'br',
  ),
  'bulgarian' => array(
    'name' => 'Bulgarian - български',
    'code' => 'bg',
  ),
  'catalan' => array(
    'name' => 'Catalan - català',
    'code' => 'ca',
  ),
  'central_kurdish' => array(
    'name' => 'Central Kurdish - کوردی (دەستنوسی عەرەبی)',
    'code' => 'ckb',
  ),
  'chinese' => array(
    'name' => 'Chinese - 中文',
    'code' => 'zh',
  ),
  'corsican' => array(
    'name' => 'Corsican',
    'code' => 'co',
  ),
  'croatian' => array(
    'name' => 'Croatian - hrvatski',
    'code' => 'hr',
  ),
  'czech' => array(
    'name' => 'Czech - čeština',
    'code' => 'cs',
  ),
  'danish' => array(
    'name' => 'Danish - dansk',
    'code' => 'da',
  ),
  'esperanto' => array(
    'name' => 'Esperanto - esperanto',
    'code' => 'eo',
  ),
  'estonian' => array(
    'name' => 'Estonian - eesti',
    'code' => 'et',
  ),
  'faroese' => array(
    'name' => 'Faroese - føroyskt',
    'code' => 'fo',
  ),
  'filipino' => array(
    'name' => 'Filipino',
    'code' => 'fil',
  ),
  'finnish' => array(
    'name' => 'Finnish - suomi',
    'code' => 'fi',
  ),
  'galician' => array(
    'name' => 'Galician - galego',
    'code' => 'gl',
  ),
  'georgian' => array(
    'name' => 'Georgian - ქართული',
    'code' => 'ka',
  ),
  'greek' => array(
    'name' => 'Greek - Ελληνικά',
    'code' => 'el',
  ),
  'guarani' => array(
    'name' => 'Guarani',
    'code' => 'gn',
  ),
  'gujarati' => array(
    'name' => 'Gujarati - ગુજરાતી',
    'code' => 'gu',
  ),
  'hausa' => array(
    'name' => 'Hausa',
    'code' => 'ha',
  ),
  'hawaiian' => array(
    'name' => 'Hawaiian - ʻŌlelo Hawaiʻi',
    'code' => 'haw',
  ),
  'hebrew' => array(
    'name' => 'Hebrew - עברית',
    'code' => 'he',
  ),
  'hindi' => array(
    'name' => 'Hindi - हिन्दी',
    'code' => 'hi',
  ),
  'hungarian' => array(
    'name' => 'Hungarian - magyar',
    'code' => 'hu',
  ),
  'icelandic' => array(
    'name' => 'Icelandic - íslenska',
    'code' => 'is',
  ),
  'indonesian' => array(
    'name' => 'Indonesian - Indonesia',
    'code' => 'id',
  ),
  'interlingua' => array(
    'name' => 'Interlingua',
    'code' => 'ia',
  ),
  'irish' => array(
    'name' => 'Irish - Gaeilge',
    'code' => 'ga',
  ),
  'japanese' => array(
    'name' => 'Japanese - 日本語',
    'code' => 'ja',
  ),
  'kannada' => array(
    'name' => 'Kannada - ಕನ್ನಡ',
    'code' => 'kn',
  ),
  'kazakh' => array(
    'name' => 'Kazakh - қазақ тілі',
    'code' => 'kk',
  ),
  'khmer' => array(
    'name' => 'Khmer - ខ្មែរ',
    'code' => 'km',
  ),
  'korean' => array(
    'name' => 'Korean - 한국어',
    'code' => 'ko',
  ),
  'kurdish' => array(
    'name' => 'Kurdish - Kurdî',
    'code' => 'ku',
  ),
  'kyrgyz' => array(
    'name' => 'Kyrgyz - кыргызча',
    'code' => 'ky',
  ),
  'lao' => array(
    'name' => 'Lao - ລາວ',
    'code' => 'lo',
  ),
  'latin' => array(
    'name' => 'Latin',
    'code' => 'la',
  ),
  'latvian' => array(
    'name' => 'Latvian - latviešu',
    'code' => 'lv',
  ),
  'lingala' => array(
    'name' => 'Lingala - lingála',
    'code' => 'ln',
  ),
  'lithuanian' => array(
    'name' => 'Lithuanian - lietuvių',
    'code' => 'lt',
  ),
  'macedonian' => array(
    'name' => 'Macedonian - македонски',
    'code' => 'mk',
  ),
  'malay' => array(
    'name' => 'Malay - Bahasa Melayu',
    'code' => 'ms',
  ),
  'malayalam' => array(
    'name' => 'Malayalam - മലയാളം',
    'code' => 'ml',
  ),
  'maltese' => array(
    'name' => 'Maltese - Malti',
    'code' => 'mt',
  ),
  'marathi' => array(
    'name' => 'Marathi - मराठी',
    'code' => 'mr',
  ),
  'mongolian' => array(
    'name' => 'Mongolian - монгол',
    'code' => 'mn',
  ),
  'nepali' => array(
    'name' => 'Nepali - नेपाली',
    'code' => 'ne',
  ),
  'norwegian' => array(
    'name' => 'Norwegian',
    'code' => 'no',
  ),
  'occitan' => array(
    'name' => 'Occitan',
    'code' => 'oc',
  ),
  'oriya' => array(
    'name' => 'Oriya - ଓଡ଼ିଆ',
    'code' => 'or',
  ),
  'oromo' => array(
    'name' => 'Oromo - Oromoo',
    'code' => 'om',
  ),
  'pashto' => array(
    'name' => 'Pashto - پښتو',
    'code' => 'ps',
  ),
  'persian' => array(
    'name' => 'Persian - فارسی',
    'code' => 'fa',
  ),
  'polish' => array(
    'name' => 'Polish - polski',
    'code' => 'pl',
  ),
  'punjabi' => array(
    'name' => 'Punjabi - ਪੰਜਾਬੀ',
    'code' => 'pa',
  ),
  'quechua' => array(
    'name' => 'Quechua',
    'code' => 'qu',
  ),
  'romanian' => array(
    'name' => 'Romanian - română',
    'code' => 'ro',
  ),
  'romansh' => array(
    'name' => 'Romansh - rumantsch',
    'code' => 'rm',
  ),
  'scottish_gaelic' => array(
    'name' => 'Scottish Gaelic',
    'code' => 'gd',
  ),
  'serbian' => array(
    'name' => 'Serbian - српски',
    'code' => 'sr',
  ),
  'serbo' => array(
    'name' => 'Serbo - Croatian',
    'code' => 'sh',
  ),
  'shona' => array(
    'name' => 'Shona - chiShona',
    'code' => 'sn',
  ),
  'sindhi' => array(
    'name' => 'Sindhi',
    'code' => 'sd',
  ),
  'sinhala' => array(
    'name' => 'Sinhala - සිංහල',
    'code' => 'si',
  ),
  'slovak' => array(
    'name' => 'Slovak - slovenčina',
    'code' => 'sk',
  ),
  'slovenian' => array(
    'name' => 'Slovenian - slovenščina',
    'code' => 'sl',
  ),
  'somali' => array(
    'name' => 'Somali - Soomaali',
    'code' => 'so',
  ),
  'southern_sotho' => array(
    'name' => 'Southern Sotho',
    'code' => 'st',
  ),
  'sundanese' => array(
    'name' => 'Sundanese',
    'code' => 'su',
  ),
  'swahili' => array(
    'name' => 'Swahili - Kiswahili',
    'code' => 'sw',
  ),
  'swedish' => array(
    'name' => 'Swedish - svenska',
    'code' => 'sv',
  ),
  'tajik' => array(
    'name' => 'Tajik - тоҷикӣ',
    'code' => 'tg',
  ),
  'tamil' => array(
    'name' => 'Tamil - தமிழ்',
    'code' => 'ta',
  ),
  'tatar' => array(
    'name' => 'Tatar',
    'code' => 'tt',
  ),
  'telugu' => array(
    'name' => 'Telugu - తెలుగు',
    'code' => 'te',
  ),
  'thai' => array(
    'name' => 'Thai - ไทย',
    'code' => 'th',
  ),
  'tigrinya' => array(
    'name' => 'Tigrinya - ትግርኛ',
    'code' => 'ti',
  ),
  'tongan' => array(
    'name' => 'Tongan - lea fakatonga',
    'code' => 'to',
  ),
  'turkmen' => array(
    'name' => 'Turkmen',
    'code' => 'tk',
  ),
  'twi' => array(
    'name' => 'Twi',
    'code' => 'tw',
  ),
  'urdu' => array(
    'name' => 'Urdu - اردو',
    'code' => 'ur',
  ),
  'uyghur' => array(
    'name' => 'Uyghur',
    'code' => 'ug',
  ),
  'uzbek' => array(
    'name' => 'Uzbek - o‘zbek',
    'code' => 'uz',
  ),
  'vietnamese' => array(
    'name' => 'Vietnamese - Tiếng Việt',
    'code' => 'vi',
  ),
  'walloon' => array(
    'name' => 'Walloon - wa',
    'code' => 'wa',
  ),
  'welsh' => array(
    'name' => 'Welsh - Cymraeg',
    'code' => 'cy',
  ),
  'western_frisian' => array(
    'name' => 'Western Frisian',
    'code' => 'fy',
  ),
  'xhosa' => array(
    'name' => 'Xhosa',
    'code' => 'xh',
  ),
  'yiddish' => array(
    'name' => 'Yiddish',
    'code' => 'yi',
  ),
  'yoruba' => array(
    'name' => 'Yoruba - Èdè Yorùbá',
    'code' => 'yo',
  ),
  'zulu' => array(
    'name' => 'Zulu - isiZulu',
    'code' => 'zu',
  )
);