<div class="content__inner">
    <h2>Report user profile</h2>
    <p>
        Please use this <strong>(<?php echo cl_link("mobile_api/profile_report"); ?>) API for access user profile reporting endpoint</strong> 
    </p>
    <br>
    <h4 class="table-title">Post parameters</h4>
    <table class="table table-bordered">
        <thead>
        <tr>
            <th width="15%">Field</th>
            <th width="25%">Value</th>
            <th width="45%">Remarks</th>
        </tr>
        </thead>
        <tbody>
            <tr>
                <td>session_id</td>
                <td>​Access token ID</td>
                <td>
                    E.g. de25cc16eb00960f076...
                </td>
            </tr>
            <tr>
                <td>user_id</td>
                <td>User int ID</td>
                <td>
                    E.g. 12
                </td>
            </tr>
            <tr>
                <td>reason</td>
                <td>​
                    Report reason int ID (This value must be an int number as shown on the right)
                    <br>
                    <br>
                    <div>
                        For example, if you want to report spam account, then this value should be <b>1</b>
                    </div>
                </td>
                <td>
                    <ul>
                        <li>
                            1 = This user using this account for smap
                        </li>
                        <li>
                            2 = This user pretended to be someone
                        </li>
                        <li>
                            3 = This user posting inappropriate content
                        </li>
                        <li>
                            4 = This is a fake account
                        </li>
                        <li>
                            5 = This is a fraudulent account
                        </li>
                        <li>
                            6 = Other
                        </li>
                    </ul>
                </td>
            </tr>
            <tr>
                <td>comment</td>
                <td>​Comment to the reviwer</td>
                <td>
                    `Please take some actions. Thanks!`
                </td>
            </tr>
        </tbody>
    </table>
    <h4 class="table-title">Success response</h4>
    <div class="code-holder">
        <div class="code-holder-inner">
    <pre><code class="json">{
    "code": 200,
    "message": "Report sent successfully",
    "data": []
}
</code></pre>
        </div>
    </div>
    <h4 class="table-title">Error responses</h4>
    <div class="code-holder">
        <div class="code-holder-inner">
    <pre><code class="json">{
    "code": 401,
    "data": [],
    "message": "Unauthorized Access"
}

{
    "code": 400,
    "message": "User id is missing or invalid",
    "data": []
}

{
    "code": 400,
    "message": "Report reason id is missing or invalid",
    "data": []
}
</code></pre>
        </div>
    </div>
</div>
