<section class="main flex col nd gap-2">
    <div class="Create-comunity target">
        <h1 class="t-center">Create a New Comunity</h1>
        <p>
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Doloremque illum ipsa cum voluptatibus nesciunt
            illo
            voluptatem neque suscipit perferendis, aspernatur distinctio
            dignissimos ut et corrupti quae est iure porro perspiciatis.
        </p>
        <form name="create-comunity-form" method="POST" action="native_api/main/create_community">
            <h3>Name</h3>
            <p class="mintext t-color-3">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sed, fuga!</p>
            <div class="form-group">
                <label for="">Title *</label>
                <div class="form-control">
                    <input class="bg-3" type="text" name="title" placeholder="lorem">
                </div>
            </div>
            <div class="form-group">
                <label for="">Name *</label>
                <div class="form-control"><span class="r-name mintext t-color-3 absolute">r/</span>
                    <input class="bg-3" type="text" placeholder="lorem" name="name">
                </div><span class="mintext t-color-3">Lorem ipsum dolor sit amet consectetur.</span>
            </div>
            <div class="form-group community-type-content">
                <label>Comunuty Type</label>
                <div class="radio-group flex col gap-1">
                    <div class="radio flex nd gap-1">
                        <input id="r1" type="radio" name="property" value="public" checked>
                        <label class="flex nd al-c gap-1" for="r1"><i class="material-symbols-outlined fill">person</i>
                            Public <span class="mintext t-color-3">Lorem ipsum dolor sit amet consectetur, adipisicing
                                elit. Aut, officia.</span></label>
                    </div>
                    <div class="radio flex nd gap-1">
                        <input id="r2" type="radio" name="property" value="private">
                        <label class="flex nd al-c gap-1" for="r2"><i class="material-symbols-outlined fill">lock</i>
                            Private <span class="mintext t-color-3">Lorem ipsum dolor sit amet consectetur, adipisicing
                                elit. Aut, officia.</span></label>
                    </div>
                </div>
            </div>
            <div class="btns-content flex gap-2 nd js-e">
                <button class="btn round wb">Cancel</button>
                <button class="btn round bg-primary" type="submit">Create Community</button>
            </div>
        </form>
    </div>
</section>