<div class="timeline-container" data-app="homepage">
    <?php global $community, $is_joined;

    ?>
    <div class="user-profile">

        <div class="user-profile__header" id="vue-profile-cover-app">
            <div class="user-profile__header-cover">
                <?php
                if ($community['banner'] != "") :

                ?>
                <img src="<?php
                                echo $community['banner']; ?>" style="width:100%; height:100px;">
                <?php else :

                ?>

                <div style="background-color: <?php echo $cl["display_set"]["base"]; ?>; width:968px;height:100px;">
                </div>
                <?php endif; ?>
            </div>
        </div>

        <div class="user-profile__body" style="display:flex;">
            <?php if (not_empty($community['icon'])) : ?>
            <img src="<?php echo $community['icon']; ?>"
                style="height: 70px; width:70px;border: 3px solid white;border-radius: 34px;position: relative;top: -17px;left: 43px;z-index: 300;">
            <?php else : ?>
            <div
                style="font-size:50px; color:white; background-color: <?php echo $cl["display_set"]["base"]; ?>;height: 70px; width:70px;border: 3px solid white;border-radius: 34px;position: relative;top: -17px;left: 43px;z-index: 300;">
                <div class="icon_name">r/</div>
            </div>
            <?php endif; ?>
            <div class="user-profile__name" style="padding-left:60px; ">
                <h4>
                    <span class="user-name-holder">
                        <span class="user-name-holder__name" style="font-weight:bold">

                            <?php echo $community['name']; ?>

                        </span>


                    </span>
                </h4>
                <a href="" data-spa="true" style="display: block;
					color: var(--cl-secondary-text-color);
					font-size: var(--cl-primary-name-size);
					line-height: 1;
					text-decoration: none;">
                    Karma-&nbsp;&nbsp;
                    <span><img
                            src="https://img.icons8.com/external-creatype-blue-field-colourcreatype/64/000000/external-setting-interface-a2-creatype-blue-field-colourcreatype.png"
                            style="width: 15px; height:15px;" />9562</span>
                </a>

            </div>
            <?php if (!not_empty($is_joined)) : ?>
            <form method="POST" action="native_api/main/join_community">
                <input type="hidden" name="community_id" value="<?php echo $community['community_id']; ?>">
                <input type="hidden" name="user_id" value="<?php echo $me['id']; ?>">
                <button type="submit" class="btn btn-outline-primary">Join</button>
            </form>
            <?php else : ?>
            <form>
                <button type="button" class="btn btn-outline-primary">Joined</button>
            </form> <?php endif; ?>

            <!-- <div class="user-profile__counter">

                <a class="counter-item" href="<?php echo (cl_strf('%s/posts', $cl['prof_user']['url'])); ?>">
                    <span>
                        <?php echo cl_number(0); ?>
                    </span>
                    <span>
                        <?php echo cl_translate("Tweets"); ?>
                    </span>
                </a>
                <a class="counter-item" href="<?php echo (cl_strf('%s/posts', $cl['prof_user']['url'])); ?>">
                    <span>
                        <?php echo cl_number(0); ?>
                    </span>
                    <span>
                        <?php echo cl_translate("Retweet"); ?>
                    </span>
                </a>
                <a class="counter-item" href="<?php echo (cl_strf('%s/posts', $cl['prof_user']['url'])); ?>">
                    <span>
                        <?php echo cl_number($cl['prof_user']['posts']); ?>
                    </span>
                    <span>
                        <?php echo cl_translate("Comments"); ?>
                    </span>
                </a>

                <?php if (not_empty($cl["can_view"])) : ?>
                <a href="<?php echo (cl_strf('%s/followers', $cl['prof_user']['url'])); ?>" class="counter-item"
                    data-spa="true">
                    <?php else : ?>
                    <a href="" class="counter-item" onclick="SMColibri.PS.profile.privacy_alert();">
                        <?php endif; ?>
                        <span>
                            <?php echo cl_number($cl['prof_user']['followers']); ?>
                        </span>
                        <span>
                            <?php echo cl_translate("Followers"); ?>
                        </span>
                    </a>

                    <?php if (not_empty($cl["can_view"])) : ?>
                    <a href="<?php echo (cl_strf('%s/following', $cl['prof_user']['url'])); ?>" class="counter-item"
                        data-spa="true">
                        <?php else : ?>
                        <a href="" class="counter-item" onclick="SMColibri.PS.profile.privacy_alert();">
                            <?php endif; ?>
                            <span>
                                <?php echo cl_number($cl['prof_user']['following']); ?>
                            </span>
                            <span>
                                <?php echo cl_translate("Following"); ?>
                            </span>
                        </a>
            </div> -->


        </div>

        <div style="background-color:grey;padding-left:5%; padding-bottom:10px;padding-top:10px;">
            <button type="button" class="btn btn-dark">Button</button>
            <button type="button" class="btn btn-dark">Button</button>
            <button type="button" class="btn btn-dark">Button</button>
            <button type="button" class="btn btn-dark">Button</button>
        </div>
    </div>
    <div class="homepage">
        <!-- <div class="homepage__pubbox">
			<?php // $cl['pb_id'] = 1; //echo cl_template('timeline/pubbox'); 
            ?>
		</div> -->

        <?php if ($cl["config"]["swift_system_status"] == "on") : ?>
        <div class="homepage__swifts">
            <div class="swifts-slider">
                <div class="swiper" id="homepage-swifts-slider">
                    <div class="swiper-wrapper">
                        <div class="swiper-slide">
                            <div class="swift-item" onclick="SMColibri.PS.new_swift.add_swift();">
                                <div class="swift-item__body create-swift">
                                    <div class="swift-item__avatar">
                                        <img src="" alt="Avatar">
                                    </div>
                                    <span class="add-ikon">
                                        <?php echo cl_icon("add"); ?>
                                    </span>
                                </div>
                                <div class="swift-item__footer">
                                    <?php echo cl_translate("Create new swift"); ?>
                                </div>
                            </div>
                        </div>

                        <?php if (not_empty($cl["tl_swifts"])) : ?>
                        <?php foreach ($cl["tl_swifts"] as $swift_id => $swift_data) : ?>
                        <div class="swiper-slide">
                            <div data-an="swift-item-<?php echo ($swift_data['id']); ?>"
                                class="swift-item <?php if (not_empty($swift_data['has_unseen'])) {
                                                                                                                            echo ('active');
                                                                                                                        } ?>"
                                onclick="SMColibri.PS.play_swift.show('<?php echo ($swift_id); ?>');">
                                <div class="swift-item__body">
                                    <div class="swift-item__avatar">
                                        <img src="<?php echo ($swift_data['avatar']); ?>" alt="Avatar">
                                    </div>
                                </div>
                                <div class="swift-item__footer">
                                    <?php if (not_empty($swift_data["is_user"])) : ?>
                                    <?php echo cl_translate("Your swifts"); ?>
                                    <?php else : ?>
                                    <?php echo ($swift_data['name']); ?>
                                    <?php endif; ?>
                                </div>
                            </div>
                        </div>
                        <?php endforeach; ?>
                        <?php endif; ?>
                    </div>
                </div>
                <div class="swifts-slider__footer">
                    <div class="swiper-scrollbar" id="homepage-swifts-scrollbar"></div>
                </div>
            </div>
        </div>
        <?php endif; ?>
    </div>
    <div class="container" style="padding-left:30px; padding-right:30px; background-color:#dae0e6;padding-top:30px;">

        <div class="timeline-header" data-el="tl-header"
            style="border: 3px solid #dddfe4; margin-bottom: 14px;font-size: 13px;">
            <div style="align-items: center; padding-left: 18px;padding-top: 12px;padding-bottom: 12px;"
                class="timeline-pubbox__textinput row">
                <div class="pubbox-avatar col-sm-2" style="color:<?php echo $cl["display_set"]["highlight"]; ?>;">
                    <img src="https://img.icons8.com/material/24/228BE6/sun--v1.png"
                        style="background-color:<?php echo $cl["display_set"]["highlight"]; ?>;width: 20px; height:20px;">
                    New
                </div>
                <div class="pubbox-avatar col-sm-2">
                    <img src="https://img.icons8.com/small/16/737373/fire-element.png"
                        style="width: 20px; height:20px;">
                    Hot
                </div>
                <div class="pubbox-avatar col-sm-2">
                    <img src="https://img.icons8.com/external-yogi-aprelliyanto-detailed-outline-yogi-aprelliyanto/64/737373/external-upload-arrow-yogi-aprelliyanto-detailed-outline-yogi-aprelliyanto.png"
                        style="width: 20px; height:20px;">
                    Top
                </div>
            </div>
        </div>
        <div class="timeline-posts-container">
            <?php if (not_empty($cl["tl_feed"])) :  ?>
            <div class="timeline-posts-ls" data-an="entry-list">
                <?php foreach ($cl["tl_feed"] as $cl["li"]) : ?>
                <?php echo cl_template('timeline/post_community'); ?>
                <?php endforeach; ?>
            </div>
            <?php else : ?>
            <?php echo cl_template('home/includes/no_posts'); ?>
            <?php endif; ?>
        </div>
    </div>

    <?php if ($cl["config"]["swift_system_status"] == "on") : ?>
    <?php echo cl_template("home/modals/swift_lightbox"); ?>
    <?php echo cl_template("home/modals/swift_pubbox"); ?>
    <?php endif; ?>

    <?php echo cl_template("main/includes/inline_statics/app_statics"); ?>
    <?php //echo cl_template("home/scripts/app_master_script"); 
    ?>
</div>