<section class="main flex col nd gap-2">
    <div class="Post-bar flex target gap-1">
        <div class="user-image-content">
            <div class="user-image s-2 circle">
                <img src="<?php convert_into_base64($me['avatar']); ?>" alt="Avatar">
            </div>
        </div>
        <div class="controls-content">
            <textarea class="bg-3 t-color-3" for="tweet-input" rows="1" name="tweet-input"
                placeholder="Make a Tweet..."></textarea>
            <input type="radio" name="modal" id="tweet-input"
                <?php if (not_empty($_SESSION['image_path']) || not_empty($_SESSION['poll_data'])) echo "checked"; ?>>
            <input type="radio" name="modal" id="cancel_window">
            <input type="radio" name="modal" id="poll">
            <div class="overlay overlay-hugeinc" id="create_post">
                <div class="overlay_widget">
                    <div class="header">
                        <div class="title">Post</div>
                        <div class="cancel">
                            <form action="<?php echo cl_link("native_api/home/exit_post"); ?>">
                                <button type="submit">
                                    <label for="cancel_window">✖</label>
                                </button>
                            </form>
                        </div>
                    </div>
                    <form autocomplete="off" action="<?php echo cl_link("native_api/home/upload_image"); ?>"
                        enctype="multipart/form-data" method="POST">
                        <div class="text">Make a Tweet :</div>
                        <div class="textarea">
                            <textarea name="post_description"
                                placeholder="Say anything..."><?php if (not_empty($_SESSION['post_description'])) echo $_SESSION['post_description']; ?></textarea>
                        </div>
                        <div class="preview">
                            <img
                                src="<?php echo $_SESSION['image_path'] ? convert_into_base64($_SESSION['image_path']) : ""; ?>">
                        </div>

                        <div class="add_image">
                            <label class="btn" for="open_image">+ Add Image</label>
                            <button type="submit" name="submit" value="preview">Preview</button>
                            <label class="btn" for="isPopupVisible">Create Poll</label>
                            <input type="file" name="image" id="open_image" hidden>

                        </div>
                        <input type="hidden" value="<?php echo $cl['community_id']; ?>" name="community_id">
                        <div class="submit">
                            <button type="submit" name="submit" value="tweet">Tweet</button>
                        </div>
                    </form>
                </div>
            </div>
            <input class="hidden" id="isPopupVisible" type="radio" name="modal">
            <div class="Poll-popup fixed flex center bg-glass">
                <form autocomplete="off" action="<?php echo cl_link("native_api/home/create_poll"); ?>"
                    enctype="multipart/form-data" method="POST">
                    <label class="quit-btn absolute btn t-color-3" for="tweet-input">⨯</label>
                    <h3 class="t-center">Create a poll</h3>
                    <div class="form-group">
                        <label for="subject">Question / Subject</label>
                        <div class="form-control">
                            <input class="bg-3" id="subject" type="text" name="subject" placeholder="hola">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="answer-1">answer-1</label>
                        <div class="form-control">
                            <input class="bg-3" id="answer-1" type="text" name="answer-1" placeholder="hola">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="answer-2">answer-2</label>
                        <div class="form-control">
                            <input class="bg-3" id="answer-2" type="text" name="answer-2" placeholder="hola">
                        </div>
                    </div>
                    <input class="hidden" id="showHiddenAnwers" type="checkbox">
                    <div class="other-anwers-content flex col">
                        <div class="form-group">
                            <label for="answer-3">answer-3</label>
                            <div class="form-control">
                                <input class="bg-3" id="answer-3" type="text" name="answer-3" placeholder="hola">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="answer-4">answer-4</label>
                            <div class="form-control">
                                <input class="bg-3" id="answer-4" type="text" name="answer-4" placeholder="hola">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="answer-5">answer-5</label>
                            <div class="form-control">
                                <input class="bg-3" id="answer-5" type="text" name="answer-5" placeholder="hola">
                            </div>
                        </div>
                    </div>
                    <label class="add-answer-btn btn wb t-color-3" for="showHiddenAnwers"></label>
                    <div class="form-group">
                        <div class="submit">
                            <button type="submit" name="submit" value="poll" id="post__poll">Post Poll</button>
                        </div>

                    </div>
                </form>
            </div>
        </div>
    </div>
    <div class="main-content grid col nd gap-1">
        <?php if (not_empty($cl["tl_feed"])) : ?>
        <?php foreach ($cl["tl_feed"] as $cl["li"]) : ?>
        <?php echo cl_template('timeline/post_community'); ?>
        <?php endforeach; ?>
        <?php else : ?>
        <?php echo cl_template('home/includes/no_posts'); ?>
        <?php endif; ?>
    </div>
    <?php global $community; ?>
    <div class="pagination">
        <a href="community?community_id=<?php echo $community['community_id'] ?>&page=1">&laquo;</a>
        <?php if ($cl['page'] - 2 > 0) : ?>
        <a
            href="community?community_id=<?php echo $community['community_id'] ?>&page=<?php echo $cl['page'] - 2 ?>"><?php echo $cl['page'] - 2 ?></a>
        <?php endif; ?>

        <?php if ($cl['page'] - 1 > 0) : ?>
        <a
            href="community?community_id=<?php echo $community['community_id'] ?>&page=<?php echo $cl['page'] - 1 ?>"><?php echo $cl['page'] - 1 ?></a>
        <?php endif; ?>
        <?php if ($cl['page'] > 0) : ?>
        <a href="community?community_id=<?php echo $community['community_id'] ?>&page=<?php echo $cl['page'] ?>"
            class="active"><?php echo $cl['page'] ?></a>
        <?php endif; ?>
        <?php if ($cl['page'] < $cl['total_number'] / 5) : ?>
        <a
            href="community?community_id=<?php echo $community['community_id'] ?>&page=<?php echo $cl['page'] + 1 ?>"><?php echo $cl['page'] + 1 ?></a>
        <?php endif; ?>
        <?php if ($cl['page'] + 1 < $cl['total_number'] / 5) : ?>
        <a
            href="community?community_id=<?php echo $community['community_id'] ?>&page=<?php echo $cl['page'] + 2 ?>"><?php echo $cl['page'] + 2 ?></a>
        <?php endif; ?>
        <a
            href="community?community_id=<?php echo $community['community_id'] ?>&page=<?php echo ceil($cl['total_number'] / 5) ?>">&raquo;</a>
    </div>
</section>