<div class="timeline-container" data-app="profile">


    <div class="user-profile">
        <?php if (empty($cl['prof_user']['owner'])) : ?>
        <div class="user-profile__header">
            <div class="user-profile__header-cover">
                <a href="<?php echo cl_get_media($cl['prof_user']['cover_orig']); ?>" class="image-wrapper fbox-media">
                    <img class="viewable" src="<?php echo ($cl['prof_user']['cover']); ?>" alt="IMG">
                </a>
            </div>
            <div class="user-profile__header-avatar">
                <a href="<?php echo ($cl['prof_user']['avatar']); ?>" class="image-wrapper fbox-media">
                    <div class="profile-avatar">
                        <img src="<?php echo ($cl['prof_user']['avatar']); ?>" alt="IMG">
                    </div>
                </a>
            </div>
        </div>
        <?php else : ?>
        <div class="user-profile__header" id="vue-profile-cover-app">
            <div class="user-profile__header-cover" v-show="rep_opened != true">
                <?php if (not_empty($me['community_banner'])) : ?>
                <img src="<?php echo $me['community_banner']; ?>" style="width:100%; height:100px;">
                <?php else : ?>
                <div style="background-color: <?php if (not_empty($cl["display_set"]["base"]))  echo $cl["display_set"]["base"];else echo "#0000ff"; ?>; width:968px;height:300px;">
                </div>
                <?php endif; ?>

                <div class="cover-corrector">
                    <div class="cover-corrector__body">
                        <button title="<?php echo cl_translate('Upload new cover'); ?>" class="cover-corrector__btn"
                            v-on:click="select_cover" v-bind:disabled="submitting">
                            <?php echo cl_icon('add_photo_inline'); ?>
                        </button>
                        <button title="<?php echo cl_translate('Adjust cover (Vertically)'); ?>"
                            class="cover-corrector__btn" v-on:click="rep_start" v-bind:disabled="submitting">
                            <?php echo cl_icon('swap_vert'); ?>
                        </button>
                    </div>
                </div>
            </div>

            <div class="user-profile__header-avatar">
                <div class="profile-avatar">
                    <img src="<?php echo ($cl['prof_user']['avatar']); ?>" alt="IMG">
                    <button title="<?php echo cl_translate('Upload new avatar'); ?>" class="upload-avatar"
                        v-on:click="select_avatar" v-bind:disabled="submitting">
                        <?php echo cl_icon('add_a_photo_inline'); ?>
                    </button>
                </div>
            </div>
            <div class="user-profile__inputs">
                <input id="f1" v-on:change="upload_cover($event)" type="file" accept="image/*">
                <input id="f2" v-on:change="upload_avatar($event)" type="file" accept="image/*">
            </div>
        </div>
        <?php endif; ?>

        <div class="user-profile__body">
            <div class="user-profile__controls">
                <?php if (empty($cl['prof_user']['owner'])) : ?>
                <div class="user-profile__controls-item">
                    <button class="dropleft">
                        <input type="checkbox" class="visuallyhidden" id="drop_menu_1">
                        <label for="drop_menu_1">
                            <div class="dropdown-toggle" data-toggle="dropdown">
                                <?php echo cl_icon('more_horiz'); ?>
                            </div>
                        </label>
                        <div id="dropdown_1" class="dropdown-menu dropdown-icons show">
                            <?php if (empty($cl['prof_user']['is_blocked']) && empty($cl['prof_user']['me_blocked'])) : ?>
                            <?php if (not_empty($cl['is_logged'])) : ?>
                            <a class="dropdown-item" href="<?php echo ($cl['prof_user']['chaturl']); ?>"
                                data-spa="true">
                                <span class="flex-item dropdown-item-icon">
                                    <?php echo cl_icon("chat"); ?>
                                </span>
                                <span class="flex-item">
                                    <?php echo cl_translate('Write a message'); ?>
                                </span>
                                <span class="flex-item dropdown-item-icon dropdown-item-icon_adinfo">
                                    <?php echo cl_icon("navigate_next"); ?>
                                </span>
                            </a>
                            <?php endif; ?>
                            <?php endif; ?>
                            <div class="dropdown-divider"></div>
                            <?php if (not_empty($cl["can_view"])) : ?>
                            <a class="dropdown-item"
                                href="<?php echo (cl_strf('%s/following', $cl['prof_user']['url'])); ?>"
                                data-spa="true">
                                <?php else : ?>
                                <a class="dropdown-item" onclick="SMColibri.PS.profile.privacy_alert();">
                                    <?php endif; ?>
                                    <span class="flex-item dropdown-item-icon">
                                        <?php echo cl_icon("people_alt"); ?>
                                    </span>
                                    <span class="flex-item">
                                        <?php echo cl_translate('Show followings'); ?>
                                    </span>
                                    <span class="flex-item dropdown-item-icon dropdown-item-icon_adinfo">
                                        <?php echo cl_icon("navigate_next"); ?>
                                    </span>
                                </a>
                                <?php if (not_empty($cl["can_view"])) : ?>
                                <a class="dropdown-item"
                                    href="<?php echo (cl_strf('%s/followers', $cl['prof_user']['url'])); ?>"
                                    data-spa="true">
                                    <?php else : ?>
                                    <a class="dropdown-item" onclick="SMColibri.PS.profile.privacy_alert();">
                                        <?php endif; ?>
                                        <span class="flex-item dropdown-item-icon">
                                            <?php echo cl_icon("groups"); ?>
                                        </span>
                                        <span class="flex-item">
                                            <?php echo cl_translate('Show followers'); ?>
                                        </span>
                                        <span class="flex-item dropdown-item-icon dropdown-item-icon_adinfo">
                                            <?php echo cl_icon("navigate_next"); ?>
                                        </span>
                                    </a>
                                    <div class="dropdown-divider"></div>
                                    <a data-clipboard-text="<?php echo ($cl['prof_user']['url']); ?>"
                                        class="dropdown-item clip-board-copy" href="javascript:void(0);">
                                        <span class="flex-item dropdown-item-icon">
                                            <?php echo cl_icon("content_copy"); ?>
                                        </span>
                                        <span class="flex-item">
                                            <?php echo cl_translate('Copy link to profile'); ?>
                                        </span>
                                    </a>
                                    <div class="dropdown-divider"></div>
                                    <a class="dropdown-item" onclick="SMColibri.PS.profile_report.open();"
                                        href="javascript:void(0);">
                                        <span class="flex-item dropdown-item-icon">
                                            <?php echo cl_icon("flag"); ?>
                                        </span>
                                        <span class="flex-item">
                                            <?php echo cl_translate('Report abuse'); ?>
                                        </span>
                                        <span class="flex-item dropdown-item-icon dropdown-item-icon_adinfo">
                                            <?php echo cl_icon("info"); ?>
                                        </span>
                                    </a>

                                    <?php if (not_empty($cl['prof_user']['is_blocked'])) : ?>
                                    <a class="dropdown-item col-red" href="javascript:void(0);">
                                        <span class="flex-item dropdown-item-icon">
                                            <?php echo cl_icon("no_accounts"); ?>
                                        </span>
                                        <span class="flex-item" data-action="unblock" onclick="SMColibri.block(this);"
                                            data-id="<?php echo ($cl['prof_user']['id']); ?>">
                                            <?php echo cl_translate('Unblock'); ?>
                                        </span>
                                    </a>
                                    <?php else : ?>
                                    <a class="dropdown-item col-red" href="javascript:void(0);">
                                        <span class="flex-item dropdown-item-icon">
                                            <?php echo cl_icon("no_accounts"); ?>
                                        </span>
                                        <span class="flex-item" data-action="block" onclick="SMColibri.block(this);"
                                            data-id="<?php echo ($cl['prof_user']['id']); ?>">
                                            <?php echo cl_translate('Block'); ?>
                                        </span>
                                    </a>
                                    <?php endif; ?>
                        </div>
                    </button>
                </div>

                <?php if (not_empty($cl['is_logged'])) : ?>
                <?php if (empty($cl['prof_user']['is_blocked']) && empty($cl['prof_user']['me_blocked'])) : ?>
                <!-- <div class="user-profile__controls-item ml-offset">
                                <a href="<?php echo ($cl['prof_user']['chaturl']); ?>" class="block-link" data-spa="true">
                                    <div class="ctrl-single-btn">
                                        <?php echo cl_icon('chat'); ?>
                                    </div>
                                </a>
                            </div> -->
                <?php endif; ?>
                <?php endif; ?>

                <?php if (empty($cl['prof_user']['is_blocked'])) : ?>
                <?php if (empty($cl['prof_user']['me_blocked'])) : ?>
                <?php if ($cl['prof_user']['follow_privacy'] == 'approved') : ?>
                <?php if (not_empty($cl['prof_user']['is_following'])) : ?>
                <div class="user-profile__controls-item ml-offset">
                    <button onclick="SMColibri.req_follow(this);"
                        data-user-name="<?php echo ($cl['prof_user']['name']); ?>" class="btn btn-custom main-inline md"
                        data-action="unfollow" data-id="<?php echo ($cl['prof_user']['id']); ?>">
                        <?php echo cl_translate("Unfollow"); ?>
                    </button>
                </div>
                <?php elseif (not_empty($cl['prof_user']['follow_requested'])) : ?>
                <div class="user-profile__controls-item ml-offset">
                    <button onclick="SMColibri.req_follow(this);"
                        data-user-name="<?php echo ($cl['prof_user']['name']); ?>" class="btn btn-custom main-inline md"
                        data-action="cancel" data-id="<?php echo ($cl['prof_user']['id']); ?>">
                        <?php echo cl_translate("Pending"); ?>
                    </button>
                </div>
                <?php else : ?>
                <div class="user-profile__controls-item ml-offset">
                    <button onclick="SMColibri.req_follow(this);"
                        data-user-name="<?php echo ($cl['prof_user']['name']); ?>"
                        class="btn btn-custom main-outline md" data-action="follow"
                        data-id="<?php echo ($cl['prof_user']['id']); ?>">
                        <?php echo cl_translate("Follow"); ?>
                    </button>
                </div>
                <?php endif; ?>
                <?php else : ?>
                <?php if (not_empty($cl['prof_user']['is_following'])) : ?>
                <div class="user-profile__controls-item ml-offset">
                    <button onclick="SMColibri.follow(this);" data-user-name="<?php echo ($cl['prof_user']['name']); ?>"
                        class="btn btn-custom main-inline md" data-action="unfollow"
                        data-id="<?php echo ($cl['prof_user']['id']); ?>">
                        <?php echo cl_translate("Unfollow"); ?>
                    </button>
                </div>
                <?php else : ?>
                <div class="user-profile__controls-item ml-offset">
                    <button onclick="SMColibri.follow(this);" data-user-name="<?php echo ($cl['prof_user']['name']); ?>"
                        class="btn btn-custom main-outline md" data-action="follow"
                        data-id="<?php echo ($cl['prof_user']['id']); ?>">
                        <?php echo cl_translate("Follow"); ?>
                    </button>
                </div>
                <?php endif; ?>
                <?php endif; ?>
                <?php endif; ?>
                <?php else : ?>
                <div class="user-profile__controls-item ml-offset">
                    <button onclick="SMColibri.block(this);" class="btn btn-custom main-outline md"
                        data-action="unblock" data-id="<?php echo ($cl['prof_user']['id']); ?>">
                        <?php echo cl_translate("Unblock"); ?>
                    </button>
                </div>
                <?php endif; ?>
                <?php else : ?>
                <div class="user-profile__controls-item">
                    <button class="dropleft">
                        <input type="checkbox" class="visuallyhidden" id="drop_menu">
                        <label for="drop_menu">
                            <div class="dropdown-toggle" data-toggle="dropdown">
                                <?php echo cl_icon('more_horiz'); ?>
                            </div>
                        </label>
                        <div id="dropdown_menu" class="dropdown-menu dropdown-icons show">
                            <a class="dropdown-item"
                                href="<?php echo (cl_strf('%s/following', $cl['prof_user']['url'])); ?>"
                                data-spa="true">
                                <span class="flex-item dropdown-item-icon">
                                    <?php echo cl_icon("people_alt"); ?>
                                </span>
                                <span class="flex-item">
                                    <?php echo cl_translate('Show followings'); ?>
                                </span>
                                <span class="flex-item dropdown-item-icon dropdown-item-icon_adinfo">
                                    <?php echo cl_icon("navigate_next"); ?>
                                </span>
                            </a>
                            <a class="dropdown-item"
                                href="<?php echo (cl_strf('%s/followers', $cl['prof_user']['url'])); ?>"
                                data-spa="true">
                                <span class="flex-item dropdown-item-icon">
                                    <?php echo cl_icon("groups"); ?>
                                </span>
                                <span class="flex-item">
                                    <?php echo cl_translate('Show followers'); ?>
                                </span>
                                <span class="flex-item dropdown-item-icon dropdown-item-icon_adinfo">
                                    <?php echo cl_icon("navigate_next"); ?>
                                </span>
                            </a>
                            <div class="dropdown-divider"></div>
                            <a data-clipboard-text="<?php echo ($cl['prof_user']['url']); ?>"
                                class="dropdown-item clip-board-copy" href="javascript:void(0);">
                                <span class="flex-item dropdown-item-icon">
                                    <?php echo cl_icon("content_copy"); ?>
                                </span>
                                <span class="flex-item">
                                    <?php echo cl_translate('Copy link to profile'); ?>
                                </span>
                            </a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item"
                                href="<?php echo (cl_strf('%s/followers', $cl['prof_user']['url'])); ?>"
                                data-spa="true">
                                <span class="flex-item dropdown-item-icon">
                                    <img src="https://img.icons8.com/ios/50/000000/flag--v1.png" />
                                </span>
                                <span class="flex-item">
                                    <?php echo cl_translate('Report abuse'); ?>
                                </span>
                                <span class="flex-item dropdown-item-icon dropdown-item-icon_adinfo">
                                    <?php echo cl_icon("navigate_next"); ?>
                                </span>
                            </a>
                            <a data-clipboard-text="<?php echo ($cl['prof_user']['url']); ?>"
                                class="dropdown-item clip-board-copy" href="javascript:void(0);">
                                <span class="flex-item dropdown-item-icon">
                                    <?php echo cl_icon("content_copy"); ?>
                                </span>
                                <span class="flex-item" style="color:red;">
                                    <?php echo cl_translate('Block'); ?>
                                </span>
                            </a>
                        </div>
                    </button>
                </div>
                <div class="user-profile__controls-item ml-offset">
                    <button data-anchor="<?php echo cl_link('settings'); ?>" class="btn btn-custom main-outline md">
                        <?php echo cl_translate("FOLLOW"); ?>
                    </button>
                </div>
                <?php endif; ?>
            </div>

            <div class="user-profile__name">
                <h4>
                    <span class="user-name-holder">
                        <span class="user-name-holder__name">
                            <?php echo ($cl['prof_user']['name']); ?>
                        </span>

                        <?php if ($cl['prof_user']['verified'] == '1') : ?>
                        <span class="user-name-holder__badge">
                            <?php echo cl_icon("verified_user_badge"); ?>
                        </span>
                        <?php endif; ?>
                    </span>
                </h4>
                <a href="<?php echo ($cl['prof_user']['url']); ?>" data-spa="true">
                    @<?php echo ($cl['prof_user']['username']); ?>
                </a>
            </div>
            <div class="user-profile__counter">
                <a class="counter-item" href="<?php echo (cl_strf('%s/posts', $cl['prof_user']['url'])); ?>">
                    <span>
                        <?php echo cl_number($cl['prof_user']['posts']); ?>
                    </span>
                    <span>
                        <?php echo cl_translate("Posts"); ?>
                    </span>
                </a>

                <?php if (not_empty($cl["can_view"])) : ?>
                <a href="<?php echo (cl_strf('%s/followers', $cl['prof_user']['url'])); ?>" class="counter-item"
                    data-spa="true">
                    <?php else : ?>
                    <a href="javascript:void(0);" class="counter-item" onclick="SMColibri.PS.profile.privacy_alert();">
                        <?php endif; ?>
                        <span>
                            <?php echo cl_number($cl['prof_user']['followers']); ?>
                        </span>
                        <span>
                            <?php echo cl_translate("Followers"); ?>
                        </span>
                    </a>

                    <?php if (not_empty($cl["can_view"])) : ?>
                    <a href="<?php echo (cl_strf('%s/following', $cl['prof_user']['url'])); ?>" class="counter-item"
                        data-spa="true">
                        <?php else : ?>
                        <a href="javascript:void(0);" class="counter-item"
                            onclick="SMColibri.PS.profile.privacy_alert();">
                            <?php endif; ?>
                            <span>
                                <?php echo cl_number($cl['prof_user']['following']); ?>
                            </span>
                            <span>
                                <?php echo cl_translate("Following"); ?>
                            </span>
                        </a>
            </div>

            <?php if (not_empty($cl['prof_user']['about']) || not_empty($cl['prof_user']['website'])) : ?>
            <div class="user-profile__bio">
                <div class="user-profile__bio-topline">
                    <?php if (not_empty($cl['prof_user']['about'])) : ?>
                    <?php echo cl_linkify_urls($cl['prof_user']['about']); ?>
                    <?php endif; ?>
                </div>

                <div class="user-profile__bio-botline">
                    <?php if (not_empty($cl['prof_user']['website'])) : ?>
                    <a href="<?php echo ($cl['prof_user']['website']); ?>" target="_blank">
                        <?php echo ($cl['prof_user']['website']); ?>
                    </a>
                    <?php endif; ?>
                </div>
            </div>
            <?php endif; ?>
        </div>
        <div class="user-profile__footer">
            <div class="profile-shortinfo">
                <div class="profile-shortinfo__item">


                    <div class="profile-shortinfo__item">
                        <span class="icon"><?php echo cl_icon('perm_contact_calendar'); ?></span>
                        <span class="text">
                            <?php echo cl_translate("Member since - {@date@}", array('date' => $cl['prof_user']['joined'])); ?>
                        </span>
                    </div>
                </div>
            </div>
            <?php if (not_empty($cl['prof_user']['common_follows']) || not_empty($cl['prof_user']['is_myfollower'])) : ?>
            <div class="profile-common-follows">
                <div class="common-follows">
                    <div class="common-follows__title">
                        <?php if (not_empty($cl['prof_user']['common_follows']) && not_empty($cl['prof_user']['is_myfollower'])) : ?>
                        <?php if (count($cl['prof_user']['common_follows']) > 1) : ?>
                        <?php echo cl_translate("{@user_name@} is your follower and has {@common_follows@} followers you know", array('user_name' => $cl['prof_user']['name'], "common_follows" => cl_html_el("strong", count($cl['prof_user']['common_follows'])))); ?>
                        <?php else : ?>
                        <?php echo cl_translate("{@user_name@} is your follower and has {@common_follows@} follower you know", array('user_name' => $cl['prof_user']['name'], "common_follows" => cl_html_el("strong", count($cl['prof_user']['common_follows'])))); ?>
                        <?php endif; ?>
                        <?php elseif (not_empty($cl['prof_user']['common_follows']) && empty($cl['prof_user']['is_myfollower'])) : ?>
                        <?php if (count($cl['prof_user']['common_follows']) > 1) : ?>
                        <?php echo cl_translate("Has {@common_follows@} followers you know", array("common_follows" => cl_html_el("strong", count($cl['prof_user']['common_follows'])))); ?>
                        <?php else : ?>
                        <?php echo cl_translate("Has {@common_follows@} follower you know", array("common_follows" => cl_html_el("strong", count($cl['prof_user']['common_follows'])))); ?>
                        <?php endif; ?>
                        <?php else : ?>
                        <?php echo cl_translate("{@user_name@} is your follower", array('user_name' => $cl['prof_user']['name'])); ?>
                        <?php endif; ?>
                    </div>

                    <?php if (not_empty($cl['prof_user']['common_follows'])) : ?>
                    <div class="common-follows__list">
                        <?php foreach ($cl['prof_user']['common_follows'] as $index => $udata) : ?>
                        <?php if ($index <= 4) : ?>
                        <div class="common-follows__item"
                            title="<?php echo $udata["name"]; ?> | @<?php echo $udata["username"]; ?>">
                            <a href="<?php echo $udata["url"]; ?>" data-spa="true">
                                <img src="<?php echo $udata["avatar"]; ?>" alt="IMG">
                            </a>
                        </div>
                        <?php endif; ?>
                        <?php endforeach; ?>

                        <?php if (count($cl['prof_user']['common_follows']) > 5) : ?>
                        <div class="common-follows__item common-follows__item_total">
                            <span>
                                +<?php echo (count($cl['prof_user']['common_follows']) - 5); ?>
                            </span>
                        </div>
                        <?php endif; ?>
                    </div>
                    <?php endif; ?>
                </div>
            </div>
            <?php endif; ?>
        </div>
    </div>



    <?php if (not_empty($cl['prof_user']['is_blocked']) || not_empty($cl['prof_user']['me_blocked'])) : ?>
    <div class="timeline-posts-container">
        <div class="timeline-posts-ls">
            <?php echo cl_template('profile/includes/blocked_profile'); ?>
        </div>
    </div>
    <?php else : ?>
    <?php if (not_empty($cl["can_view"])) : ?>
    <?php if (in_array($cl['page_tab'], array('posts', 'media'))) : ?>
    <div class="timeline-posts-container"
        style="padding-left:30px; padding-right:30px; background-color:#dae0e6;padding-top:30px;">
        <div class="timeline-posts-ls" data-an="entry-list">
            <?php if (not_empty($cl["user_posts"])) : ?>
            <?php foreach ($cl["user_posts"] as $cl['li']) : ?>
            <?php echo cl_template('timeline/post'); ?>
            <?php endforeach; ?>
            <?php else : ?>
            <?php echo cl_template('profile/includes/no_posts'); ?>
            <?php endif; ?>
        </div>
    </div>
    <?php else : ?>
    <div class="timeline-posts-container" style="padding-left:30px; padding-right:30px; background-color:#dae0e6;">
        <div class="timeline-posts-ls" data-an="entry-list">
            <?php if (not_empty($cl["user_likes"])) : ?>
            <?php foreach ($cl["user_likes"] as $cl['li']) : ?>
            <?php echo cl_template('timeline/post'); ?>
            <?php endforeach; ?>
            <?php else : ?>
            <?php echo cl_template('profile/includes/no_posts'); ?>
            <?php endif; ?>
        </div>
    </div>
    <?php endif; ?>
    <?php else : ?>
    <div class="timeline-posts-container">
        <div class="timeline-posts-ls">
            <?php echo cl_template('profile/includes/private_profile'); ?>
        </div>
    </div>
    <?php endif; ?>
    <?php endif; ?>

    <?php //echo cl_template('profile/scripts/app_master_script'); 
    ?>

    <?php if (empty($cl['prof_user']['owner'])) : ?>
    <?php echo cl_template('profile/modals/report_profile'); ?>
    <?php endif; ?>

    <?php //echo cl_template("main/includes/inline_statics/app_statics"); 
    ?>
</div>