<div class="content__inner">
    <h2>Reset user password</h2>
    <p>
        Please use this <strong>(<?php echo cl_link("mobile_api/resetpassword"); ?>)</strong> API to access user password recovery endpoint
    </p>
    <br>
    <h4 class="table-title">Post parameters</h4>
    <table class="table table-bordered">
        <thead>
        <tr>
            <th width="15%">Field</th>
            <th width="25%">Value</th>
            <th width="45%">Remarks</th>
        </tr>
        </thead>
        <tbody>
            <tr>
                <td>email</td>
                <td>User email address</td>
                <td>
                    E.g. testuser@gmail.com​
                </td>
            </tr>
        </tbody>
    </table>
    <h4 class="table-title">Success response</h4>
    <div class="code-holder">
        <div class="code-holder-inner">
    <pre><code class="json">{
        "code": 200,
        "message": "Check your email for resetting your password",
        "data":[]
    }
    </code></pre>
        </div>
    </div>
    <h4 class="table-title">Error responses</h4>
    <div class="code-holder">
        <div class="code-holder-inner">
    <pre><code class="json">{
        "code": 411,
        "message": "Email address is unknown"
    }
    </code></pre>
        </div>
    </div>
    <div class="code-holder">
        <div class="code-holder-inner">
    <pre><code class="json">{
        "code": 411,
        "message": "Email address is not valid"
    }
    </code></pre>
        </div>
    </div>
</div>