<div class="cp-app-container" data-app="delete-swifts">
    <div class="current-page-name">
        <div class="lp">
            <h2>
                Remove expired swifts
            </h2>
            <ol class="breadcrumb">
                <li>
                    <a href="<?php echo cl_link('admin_panel'); ?>">
                        Control panel
                    </a>
                </li>
                <li class="active">
                    <a href="">
                        Remove expired swifts
                    </a>
                </li>
            </ol>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card">
                <div class="header">
                    <h2>
                        Remove expired user swifts
                    </h2>
                </div>
                <div class="body">
                    <div class="inline-alertbox-wrapper">
                        <div class="inline-alertbox info">
                            <div class="icon">
                                <?php echo cl_ikon("info"); ?>
                            </div>
                            <div class="alert-message">
                                <p>
                                    This function will remove all expired swifts of your users. Please note, that this
                                    process may take some time. Please wait until the process is complete without
                                    leaving the page
                                </p>
                            </div>
                        </div>
                    </div>
                    <hr>
                    <form class="form" data-an="form">
                        <div class="form-group no-mb">
                            <button data-an="submit-ctrl" type="submit" class="btn bg-blue btn-block btn-lg ttup">
                                Delete
                            </button>
                        </div>
                        <input type="hidden" class="d-none"
                            value="<?php echo fetch_or_get($cl['csrf_token'], 'none'); ?>" name="hash">
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
<?php //echo cl_template('cpanel/assets/delete_swifts/scripts/app_master_script'); ?>