<div class="content__inner">
    <h2>User timeline feed</h2>
    <p>
        Please use this <strong>(<?php echo cl_link("mobile_api/feeds"); ?>)</strong> API to access user timeline feed endpoint
    </p>
    <br>
    <h4 class="table-title">Get parameters</h4>
    <table class="table table-bordered">
        <thead>
        <tr>
            <th width="15%">Field</th>
            <th width="25%">Value</th>
            <th width="45%">Remarks</th>
        </tr>
        </thead>
        <tbody>
            <tr>
                <td>offset</td>
                <td>Last post offset ID</td>
                <td>
                    This is only needed when loading posts of the pagination system.
                </td>
            </tr>
            <tr>
                <td>session_id</td>
                <td>​Access token ID</td>
                <td>
                    E.g. de25cc16eb00960f076...
                </td>
            </tr>
            <tr>
                <td>page_size</td>
                <td>​Total post limit for each request</td>
                <td>
                    Recommended: 20
                </td>
            </tr>
        </tbody>
    </table>
    <h4 class="table-title">Success response</h4>
    <div class="code-holder">
        <div class="code-holder-inner">
    <pre><code class="json">{
        "code": 200,
        "message": "Feeds fetched successfully",
        "data": {
            "feeds": [
                {
                    "id": 238,
                    "user_id": 2,
                    "text": "lorejm egwtwer",
                    "type": "text",
                    "replys_count": "0",
                    "reposts_count": "0",
                    "likes_count": "0",
                    "status": "active",
                    "thread_id": 0,
                    "target": "publication",
                    "og_data": "",
                    "time": "9 hours ago",
                    "offset_id": 18,
                    "is_repost": false,
                    "is_reposter": false,
                    "attrs": "",
                    "advertising": false,
                    "time_raw": "1601368136",
                    "og_text": "lorejm egwtwer",
                    "og_image": "statics/img/logo.png",
                    "url": "http://colibri.loc/thread/238",
                    "can_delete": true,
                    "media": [],
                    "is_owner": false,
                    "has_liked": false,
                    "has_saved": false,
                    "has_reposted": false,
                    "reply_to": [],
                    "owner": {
                        "id": null,
                        "url": null,
                        "avatar": null,
                        "username": null,
                        "name": null,
                        "verified": null
                    }
                },
                {
                    "id": 237,
                    "user_id": 2,
                    "text": "",
                    "type": "gif",
                    "replys_count": "0",
                    "reposts_count": "0",
                    "likes_count": "0",
                    "status": "active",
                    "thread_id": 0,
                    "target": "publication",
                    "og_data": "",
                    "time": "9 hours ago",
                    "offset_id": 17,
                    "is_repost": false,
                    "is_reposter": false,
                    "attrs": "",
                    "advertising": false,
                    "time_raw": "1601368106",
                    "og_text": "",
                    "og_image": "statics/img/logo.png",
                    "url": "http://colibri.loc/thread/237",
                    "can_delete": true,
                    "media": [
                        {
                            "id": 14,
                            "pub_id": 237,
                            "type": "gif",
                            "src": "https://media3.giphy.com/media/IdmZ0ECRI5OzJZwEpT/giphy.gif",
                            "json_data": "[]",
                            "time": "1601368106",
                            "x": []
                        }
                    ],
                    "is_owner": false,
                    "has_liked": false,
                    "has_saved": false,
                    "has_reposted": false,
                    "reply_to": [],
                    "owner": {
                        "id": null,
                        "url": null,
                        "avatar": null,
                        "username": null,
                        "name": null,
                        "verified": null
                    },
                    "gif": null
                }
            ]
        }
    }
    </code></pre>
        </div>
    </div>
    <h4 class="table-title">Error responses</h4>
    <div class="code-holder">
        <div class="code-holder-inner">
    <pre><code class="json">{
        "code": 401,
        "data": [],
        "message": "Unauthorized Access"
    }
    </code></pre>
        </div>
    </div>
    <div class="code-holder">
        <div class="code-holder-inner">
    <pre><code class="json">{
        "message": "No data found",
        "code": 204,
        "data": []
    }
    </code></pre>
        </div>
    </div>
</div>