<div class="cp-app-container" data-app="delete-spam-accounts">
    <div class="current-page-name">
        <div class="lp">
            <h2>
                Remove spam accounts
            </h2>
            <ol class="breadcrumb">
                <li>
                    <a href="<?php echo cl_link('admin_panel'); ?>">
                        Control panel
                    </a>
                </li>
                <li class="active">
                    <a href="">
                        Remove spam accounts
                    </a>
                </li>
            </ol>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card">
                <div class="header">
                    <h2>
                        Delete unconfirmed user accounts
                    </h2>
                </div>
                <div class="body">
                    <p>
                        <b>(<?php echo cl_number($cl["total_accounts"]); ?>)</b> Unconfirmed accounts found
                    </p>
                    <br>
                    <div class="inline-alertbox-wrapper">
                        <div class="inline-alertbox info">
                            <div class="icon">
                                <?php echo cl_ikon("info"); ?>
                            </div>
                            <div class="alert-message">
                                <p>
                                    This function will delete all expired user registrations that have not been
                                    confirmed within 7 days via a code by email.
                                    <br>
                                    Please note, that this process may take some time. Please wait for the process to
                                    complete without leaving the page
                                </p>
                            </div>
                        </div>
                    </div>
                    <hr>
                    <form class="form" data-an="form">
                        <div class="form-group no-mb">
                            <button data-an="submit-ctrl" type="submit" class="btn bg-blue btn-block btn-lg ttup">
                                Delete
                            </button>
                        </div>
                        <input type="hidden" class="d-none"
                            value="<?php echo fetch_or_get($cl['csrf_token'], 'none'); ?>" name="hash">
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
<?php //echo cl_template('cpanel/assets/delete_spam_accounts/scripts/app_master_script'); ?>