<div class="timeline-container" data-app="affiliates">
    <div class="timeline-header" data-el="tl-header">
        <div class="timeline-header__topline">
            <div data-el="timeline-bs-notifs" class="timeline-bs-notifs"></div>
        </div>
        <div class="timeline-header__botline">
            <div class="lp">
                <div class="nav-link-holder">
                    <a href="<?php echo cl_link('affiliates'); ?>">
                        <?php echo cl_translate('Affiliates'); ?>
                    </a>
                </div>
            </div>
            <div class="cp">
                <a href="<?php echo cl_link('/'); ?>">
                    <img src="{%config site_logo%}" alt="Logo">
                </a>
            </div>
            <div class="rp">
                <a href="<?php echo $_SERVER['HTTP_REFERER']; ?>">
                    <div class="nav-link-holder">
                        <span class="go-back">
                            <?php echo cl_icon('arrow_back'); ?>
                        </span>
                    </div>
                </a>
            </div>
        </div>
    </div>
    <div class="affiliates">
        <div class="affiliates__header">
            <div class="icon">
                <div class="icon__bg">
                    <?php echo cl_icon('group_work'); ?>
                </div>
            </div>
            <h4>
                <?php echo cl_translate('Join our affiliate program'); ?>
            </h4>
            <p>
                <?php echo cl_translate('Just share your affiliate URL and every time someone signs up with your referral link you will earn {@aff_bonus_rate@}', array(
                    'aff_bonus_rate' => cl_html_el("b", cl_money($cl['config']['aff_bonus_rate']))
                )); ?>
            </p>
            <div class="icon icon-2">
                <?php echo cl_icon('arrow_down'); ?>
            </div>
        </div>
        <div class="affiliates__body">
            <div class="affiliates__body-topline">
                <?php echo cl_translate('This is your affiliate URL'); ?>
            </div>
            <div class="affiliates__body-midline">
                <?php echo cl_strf("%s?ref=%s", $cl['config']['url'], $me['raw_uname']); ?>
            </div>
            <div class="affiliates__body-botline">
                <a href="" class="social-link-btn copy-link clip-board-copy"
                    data-clipboard-text="<?php echo cl_strf("%s?ref=%s", $cl['config']['url'], $me['raw_uname']); ?>">
                    <span class="social-link-btn__icon">
                        <?php echo cl_icon('content_copy'); ?>
                    </span>
                </a>
                <a target="_blank"
                    href="https://www.facebook.com/sharer/sharer.php?u=<?php echo cl_strf("%s?ref=%s", $cl['config']['url'], $me['raw_uname']); ?>"
                    class="social-link-btn facebook">
                    <span class="social-link-btn__icon">
                        <?php echo cl_icon('logos/logo-facebook'); ?>
                    </span>
                </a>
                <a target="_blank"
                    href="https://twitter.com/intent/tweet?text=<?php echo cl_strf("%s?ref=%s", $cl['config']['url'], $me['raw_uname']); ?>"
                    class="social-link-btn twitter">
                    <span class="social-link-btn__icon">
                        <?php echo cl_icon('logos/logo-twitter'); ?>
                    </span>
                </a>
                <a target="_blank"
                    href="https://api.whatsapp.com/send?text=<?php echo cl_strf("%s?ref=%s", $cl['config']['url'], $me['raw_uname']); ?>"
                    class="social-link-btn whatsapp">
                    <span class="social-link-btn__icon">
                        <?php echo cl_icon('logos/logo-whatsapp'); ?>
                    </span>
                </a>
                <a target="_blank"
                    href="https://www.pinterest.ru/pin/create/button/?url=<?php echo cl_strf("%s?ref=%s", $cl['config']['url'], $me['raw_uname']); ?>"
                    class="social-link-btn pinterest">
                    <span class="social-link-btn__icon">
                        <?php echo cl_icon('logos/logo-pinterest'); ?>
                    </span>
                </a>
                <a target="_blank"
                    href="https://www.linkedin.com/shareArticle?mini=true&url=<?php echo cl_strf("%s?ref=%s", $cl['config']['url'], $me['raw_uname']); ?>"
                    class="social-link-btn linkedin">
                    <span class="social-link-btn__icon">
                        <?php echo cl_icon('logos/logo-linkedin'); ?>
                    </span>
                </a>
            </div>
        </div>
        <div class="affiliates__footer">
            <div class="affiliates__footer-topline">
                <div class="payout-request-cta">
                    <?php echo cl_translate('Submit a request to pay your earnings'); ?>
                </div>
                <?php if (cl_aff_request_exists()) : ?>
                <button disabled="true" class="btn btn-custom main-inline lg btn-block">
                    <?php echo cl_translate('Your request is pending'); ?>
                </button>
                <?php else : ?>
                <button onclick="SMCAffiliates.new_req();" class="btn btn-custom main-inline lg btn-block">
                    <?php echo cl_translate('Request payout'); ?> <?php echo cl_money(cl_calc_affiliate_bonuses()); ?>
                </button>
                <?php endif; ?>
            </div>
            <div class="affiliates__footer-botline">
                <span onclick="SMCAffiliates.how_it_works();">
                    <?php echo cl_translate('How it works?'); ?>
                </span>

                <?php if (not_empty($cl["payout_history"])) : ?>
                <span class="show-history" onclick="SMCAffiliates.show_prev_reqs();">
                    <?php echo cl_translate('Show payout request history'); ?>
                </span>
                <?php endif; ?>
            </div>
        </div>
    </div>

    <?php echo cl_template("affiliates/modals/payout_req"); ?>

    <?php echo cl_template("affiliates/modals/howit_works"); ?>

    <?php echo cl_template("affiliates/modals/payout_history"); ?>

    <?php //echo cl_template("affiliates/scripts/app_master_script"); 
    ?>
</div>