<section class="main flex col nd gap-2">
    <div class="Post-bar flex target gap-1">

        <div class="controls-content">
            <p class="title">Your Timeline</p>
            <p class="subtitle">This is where all posts from communities you joined and members you followed will show
                up.</p>
        </div>

    </div>
    <div class="main-content grid col nd gap-2">
        <?php if (not_empty($cl["tl_feed"])) : ?>
        <?php foreach ($cl["tl_feed"] as $cl["li"]) : ?>
        <?php echo cl_template('timeline/post'); ?>
        <?php endforeach; ?>
        <?php else : ?>
        <?php echo cl_template('home/includes/no_posts'); ?>
        <?php endif; ?>
    </div>

</section>