<?php if (not_empty($cl["ads_ls"])): ?>
	<div class="timeline-posts-container">
		<div class="timeline-posts-ls" data-an="ads-ls">
			<?php foreach ($cl["ads_ls"] as $cl['li']): ?>
				<?php echo cl_template("timeline/ad"); ?>
			<?php endforeach; ?>
		</div>
	</div>
<?php else: ?>
	<div class="timeline-placeholder">
		<div class="icon">
			<div class="icon__bg">
				<?php echo cl_icon('archive'); ?>
			</div>
		</div>
		<div class="pl-message">
			<h4>
				<?php echo cl_translate("No archive ads yet!"); ?>
			</h4>
			<p>
				<?php echo cl_translate("It looks like you don't have any archived ads yet. All inactive or unsaved ads will be displayed here. To activate or edit your ad, click the edit button in the ad's drop-down menu."); ?>
			</p>
		</div>
		<div class="c2action-single">
			<a href="<?php echo cl_link('ads/new'); ?>" data-spa="true">
				<button class="btn btn-custom main-outline lg">
					<?php echo cl_translate("Create new ad"); ?>
				</button>
			</a>
		</div>
	</div>
<?php endif; ?>
