<div class="content__inner">
    <div class="content__inner">
        <h2>My / User profile data</h2>
        <p>
            Please use this <strong>(<?php echo cl_link("mobile_api/profile"); ?>)</strong> API to access user profile data fetching endpoint
        </p>
        <br>
        <h4 class="table-title">Get parameters</h4>
        <table class="table table-bordered">
            <thead>
            <tr>
                <th width="15%">Field</th>
                <th width="25%">Value</th>
                <th width="45%">Remarks</th>
            </tr>
            </thead>
            <tbody>
                <tr>
                    <td>user_id</td>
                    <td>Profile user ID</td>
                    <td>
                        In order to get information about the profile, you must send a valid ID or username
                    </td>
                </tr>
                <tr>
                    <td>username</td>
                    <td>Profile username</td>
                    <td>
                        Unique username. E.g. "mansur_tl"
                    </td>
                </tr>
                <tr>
                    <td>session_id</td>
                    <td>User auth token (Optional)</td>
                    <td>
                        In this case, authorization is not required, but it is desirable to determine whether you are subscribed to this profile or not, blocked or not, etc.
                    </td>
                </tr>
            </tbody>
        </table>
        <h4 class="table-title">Success response</h4>
        <div class="code-holder">
            <div class="code-holder-inner">
    <pre><code class="json">{
        "code": 200,
        "message": "Profile fetched successfully",
        "data":{
            "id": 79,
            "first_name": "rwefwe",
            "last_name": "werwer",
            "avatar": "<?php echo cl_link("upload/avatars/2020/05/thumbnail_120x120.png"); ?>",
            "cover": "<?php echo cl_link("upload/covers/2020/11/image_cover.jpg"); ?>",
            "user_name": "3324",
            "email": "dan_kassings@gmail.com",
            "is_verified": false,
            "website": "",
            "about_you": "",
            "gender": "M",
            "country": "United States",
            "post_count": 0,
            "about": "",
            "ip_address": "127.0.0.1",
            "following_count": 0,
            "follower_count": 0,
            "language": "english",
            "last_active": "1601390105",
            "profile_privacy": "everyone",
            "member_since": "Sep 2020",
            "is_blocked_visitor": false,
            "is_following": false,
            "can_view_profile": true
        }
    }</code></pre>
            </div>
        </div>
        <h4 class="table-title">Error responses</h4>
        <div class="code-holder">
            <div class="code-holder-inner">
    <pre><code class="json">{
        "code": 400,
        "message": "User ID is missing or invalid",
        "data": []
    }

    {
        "code": 400,
        "message": "User ID is missing or invalid",
        "data": []
    }
    </code></pre>
            </div>
        </div>
    </div>
</div>