<div class="content__inner">
    <h2>Fetch Following Users</h2>
    <p>
        Please use this <strong>(<?php echo cl_link("mobile_api/fetch_following"); ?>) API for accessing endpoint of user (following) list</strong> 
    </p>
    <br>
    <h4 class="table-title">Get parameters</h4>
    <table class="table table-bordered">
        <thead>
        <tr>
            <th width="15%">Field</th>
            <th width="25%">Value</th>
            <th width="45%">Remarks</th>
        </tr>
        </thead>
        <tbody>
            <tr>
                <td>offset</td>
                <td>Last user offset ID</td>
                <td>
                    This is only needed when loading users of the pagination system.
                </td>
            </tr>
            <tr>
                <td>session_id</td>
                <td>​Access token ID (Optional)</td>
                <td>
                    E.g. de25cc16eb00960f076...
                </td>
            </tr>
            <tr>
                <td>user_id</td>
                <td>​User int ID</td>
                <td>
                    E.g. 12
                </td>
            </tr>
            <tr>
                <td>page_size</td>
                <td>​Total users limit for each request</td>
                <td>
                    Recommended: 20
                </td>
            </tr>
        </tbody>
    </table>
    <h4 class="table-title">Success response</h4>
    <div class="code-holder">
        <div class="code-holder-inner">
    <pre><code class="json">{
        "code": 200,
        "message": "Following fetched successfully",
        "data": [
            {
                "offset_id": 34,
                "id": 11,
                "about": "",
                "followers": 2,
                "posts": 0,
                "avatar": "http://colibri.loc/upload/avatars/xxx/xxx/AfPCXr9D7Gome6nAlwr...f15_thumbnail_512x512.png",
                "last_active": "12 Mar, 21 11:03 PM",
                "username": "@defgdfg",
                "fname": "Admin",
                "lname": "user",
                "email": "dfgdf@fdgdfg.com",
                "verified": "0",
                "follow_privacy": "everyone",
                "name": "Admin user",
                "url": "http:\/\/colibri.loc\/@defgdfg",
                "is_following": true,
                "follow_requested": false,
                "is_user": false
            },
            ...
        ]
    }
    </code></pre>
        </div>
    </div>
    <h4 class="table-title">Error responses</h4>
    <div class="code-holder">
        <div class="code-holder-inner">
    <pre><code class="json">{
        "message": "No data found",
        "code": 204,
        "data": []
    }

    {
        "code": 404,
        "message": "User with this ID does not exist",
        "data": []
    }

    {
        "code": 400,
        "message": "This profile data is not available for viewing",
        "data": []
    }
    </code></pre>
        </div>
    </div>
</div>
