<div class="search-result__list-item search-result__list-item_user">
	<a href="<?php echo($cl['li']['url']); ?>" data-spa="true">
		<div class="result-item-data">
			<div class="result-item-data__avatar">
				<div class="avatar">
					<img src="<?php echo($cl['li']['avatar']); ?>" alt="Avatar">
				</div>
			</div>
			<div class="result-item-data__data">
				<div class="result-item-data__topline">
					<span class="user-name-holder">
						<span class="user-name-holder__name">
							<?php echo($cl['li']['name']); ?>
						</span>

						<?php if ($cl['li']['verified'] == '1'): ?>
							<span class="user-name-holder__badge">
								<?php echo cl_icon("verified_user_badge"); ?>
							</span>
						<?php endif; ?>
					</span>
				</div>
				<div class="result-item-data__botline">
					@<?php echo($cl['li']['username']); ?>
				</div>
			</div>
		</div>
	</a>
</div>