<section class="main flex col nd gap-2">
    <div class="target">
        <div class="notification_title">My Notifications</div>
        <div class="notifications container-fluid">
            <div class="notification row">
                <div class="col-md-9 col-sm-9 col-xs-9 col-lg-9 flex">
                    <div class="avatar">
                        <img src="<?php convert_into_base64($me['avatar']); ?>" alt="Avatar">
                    </div>
                    <div class="content ">
                        jane invited you to join 'Familia' group.
                    </div>
                </div>
                <div class="actions col-md-3 col-sm-3 col-xs-3 col-lg-3">
                    <form method="POST" action="#">
                        <button class="view" type="submit" value="view">View</button>
                        <button type="submit" class="dismiss" value="dismiss">Dismiss</button>

                    </form>
                </div>
            </div>
            <div class="notification viewed row">
                <div class="col-md-9 col-sm-9 col-xs-9 col-lg-9 flex">
                    <div class="avatar">
                        <img src="<?php convert_into_base64($me['avatar']); ?>" alt="Avatar">
                    </div>
                    <div class="content ">
                        jane invited you to join 'Familia' group.
                    </div>
                </div>
                <div class="actions col-md-3 col-sm-3 col-xs-3 col-lg-3">
                    <form method="POST" action="#">
                        <!-- <button class="view" type="submit" value="view">View</button> -->
                        <button type="submit" class="dismiss" value="dismiss">Dismiss</button>

                    </form>
                </div>
            </div>
            <div class="notification row">
                <div class="col-md-9 col-sm-9 col-xs-9 col-lg-9 flex">
                    <div class="avatar">
                        <img src="<?php convert_into_base64($me['avatar']); ?>" alt="Avatar">
                    </div>
                    <div class="content ">
                        jane invited you to join 'Familia' group.
                    </div>
                </div>
                <div class="actions col-md-3 col-sm-3 col-xs-3 col-lg-3">
                    <form method="POST" action="#">
                        <button class="view" type="submit" value="view">View</button>
                        <button type="submit" class="dismiss" value="dismiss">Dismiss</button>

                    </form>
                </div>
            </div>
        </div>
    </div>

</section>